# W01 วันอังคาร (2 คาบ 120 นาที) — ทบทวนกระบวนการ Get Data และการสำรวจคุณภาพข้อมูลเบื้องต้น (ส่วนที่ 1: ขั้นที่ 1–9 + แบบฝึกหัดท้ายคาบ 30 นาที)

## เป้าหมายการเรียนรู้
- ทบทวนกระบวนการ Get Data: นำเข้าไฟล์ข้อมูล CSV พร้อมกำหนดชนิดข้อมูล (dtype) ของหมายเลขโทรศัพท์ได้
- ใช้ฟังก์ชันสำรวจโครงสร้างตาราง (head, tail, shape, columns, info) เพื่อตรวจสอบความครบถ้วนของข้อมูลทีละขั้นตอนได้
- เชื่อมโยงสู่กระบวนการ ETL เบื้องต้น: ใช้ฟังก์ชันตรวจสอบค่าทางสถิติ (describe) และนับจำนวนค่าว่าง (isna().sum()) เพื่อระบุปัญหาในชุดข้อมูลได้

## ชุดข้อมูลสำหรับการฝึกปฏิบัติ
- `nvc_tech_store.csv` (ข้อมูลรายการคำสั่งซื้อร้านอุปกรณ์ไอที NVC Tech Store: 36 แถว 7 คอลัมน์)

อัปโหลดไฟล์ `nvc_tech_store.csv` เข้าสู่ Google Colab ปฏิบัติการเขียนคำสั่งพร้อมผู้สอนทีละขั้นตอน (ขั้นที่ 1–9 ใช้เวลา 90 นาที) และทำแบบฝึกหัดปฏิบัติการท้ายคาบ 5 ข้อ (ใช้เวลา 30 นาที)

## ขั้นที่ 1: [Get Data] นำเข้าไลบรารี pandas

เริ่มต้นสภาพแวดล้อมการประมวลผลด้วยการนำเข้าไลบรารี pandas ในชื่อย่อ pd

```python
import pandas as pd
```

- `import pandas`: คำสั่งนำเข้าไลบรารีสำหรับการจัดการและวิเคราะห์ข้อมูลตาราง
- `as pd`: กำหนดชื่อย่อเป็น pd เพื่อความสะดวกในการเรียกใช้ฟังก์ชัน

เขียนคำสั่งและกด Shift + Enter ก่อนอ่านผลด้านล่าง

In [1]:
import pandas as pd

### การตรวจผล

```text
ไม่มีผลลัพธ์แสดงใต้เซลล์ และไม่มีข้อความผิดพลาด
```

ระบบพร้อมสำหรับการเรียกใช้ฟังก์ชัน pd.read_csv() และเมธอดของ DataFrame ในขั้นตอนถัดไป

**เมื่อเกิดข้อผิดพลาด:** หากเริ่มต้นสภาพแวดล้อมการทำงาน (Runtime) ใหม่โดยไม่ประมวลผลเซลล์นี้ จะเกิดข้อผิดพลาด NameError: name 'pd' is not defined

**ตรวจความเข้าใจ:** เหตุใดการเขียนชุดคำสั่งวิเคราะห์ข้อมูลด้วย Python จึงต้องเริ่มต้นด้วยการนำเข้าไลบรารี pandas

## ขั้นที่ 2: [Get Data / Extract] pd.read_csv() นำเข้าไฟล์ข้อมูลและกำหนดชนิดข้อมูลหมายเลขโทรศัพท์

ฟังก์ชัน pd.read_csv() ทำหน้าที่ดึงข้อมูล (Extract) จากไฟล์ CSV เข้าสู่ DataFrame โดยใช้พารามิเตอร์ dtype กำหนดให้คอลัมน์หมายเลขโทรศัพท์เป็นข้อความเพื่อรักษาเลข 0 นำหน้า

```python
df = pd.read_csv('nvc_tech_store.csv', dtype={'customer_phone': 'string'})
df
```

- `df =`: จัดเก็บตารางข้อมูลต้นฉบับไว้ในตัวแปร df
- `pd.read_csv('nvc_tech_store.csv', ...)`: ฟังก์ชันอ่านไฟล์ข้อมูล CSV ของร้านอุปกรณ์ไอที NVC Tech Store
- `dtype={'customer_phone': 'string'}`: พารามิเตอร์กำหนดชนิดข้อมูลของคอลัมน์ customer_phone ให้เป็นข้อความ (string)

เขียนคำสั่งและกด Shift + Enter ก่อนอ่านผลด้านล่าง

In [2]:
df = pd.read_csv('nvc_tech_store.csv', dtype={'customer_phone': 'string'})
df

   order_id customer_phone  ... total_price payment_status
0   ORD-101     0812345601  ...       580.0       ชำระแล้ว
1   ORD-102     0891122302  ...      1290.0       ชำระแล้ว
2   ORD-103     0865544303  ...       450.0       ชำระแล้ว
3   ORD-104           <NA>  ...       380.0       ชำระแล้ว
4   ORD-105     0823344505  ...       250.0       ชำระแล้ว
5   ORD-105     0823344505  ...       250.0       ชำระแล้ว
6   ORD-106     0849988706  ...       890.0       ชำระแล้ว
7   ORD-107     0856677807  ...         NaN         รอชำระ
8   ORD-108     0874455608  ...       980.0       ชำระแล้ว
9   ORD-109     0832211409  ...       650.0       ชำระแล้ว
10  ORD-110     0887766510  ...       290.0       ชำระแล้ว
11  ORD-111     0819988711  ...       440.0       ชำระแล้ว
12  ORD-112     0893344512  ...      1150.0       ชำระแล้ว
13  ORD-113     0861122313  ...      1290.0         รอชำระ
14  ORD-114     0827788914  ...       500.0        คืนเงิน
15  ORD-115     0845566715  ...       590.0       ชำระแล้ว
16  ORD-116     0851122316  ...       870.0       ชำระแล้ว
17  ORD-117     0878899017  ...       360.0       ชำระแล้ว
18  ORD-118     0836655418  ...       580.0       ชำระแล้ว
19  ORD-118     0836655418  ...       580.0       ชำระแล้ว
20  ORD-119     0882233419  ...       760.0       ชำระแล้ว
21  ORD-120     0814455620  ...     99000.0       ชำระแล้ว
22  ORD-121     0897788921  ...       790.0       ชำระแล้ว
23  ORD-122           <NA>  ...       650.0         รอชำระ
24  ORD-123     0868899023  ...       490.0       ชำระแล้ว
25  ORD-124     0824455624  ...      2580.0       ชำระแล้ว
26  ORD-125     0841122325  ...         NaN       ชำระแล้ว
27  ORD-126     0859988726  ...       890.0       ชำระแล้ว
28  ORD-127     0872233427  ...      1180.0       ชำระแล้ว
29  ORD-128     0838899028  ...      1250.0       ชำระแล้ว
30  ORD-129     0884455629  ...      1150.0       ชำระแล้ว
31  ORD-130     0816677830  ...       870.0       ชำระแล้ว
32  ORD-131     0892233431  ...       190.0       ชำระแล้ว
33  ORD-132     0864455632  ...       300.0       ชำระแล้ว
34  ORD-133     0829988733  ...       180.0         รอชำระ
35  ORD-134     0847788934  ...       220.0       ชำระแล้ว

[36 rows x 7 columns]

### การตรวจผล

| ดัชนี | order_id | customer_phone | product_name | category | quantity | total_price | payment_status |
| --- | --- | --- | --- | --- | --- | --- | --- |
| 0 | ORD-101 | 0812345601 | เมาส์ไร้สาย NVC Pro | อุปกรณ์ต่อพ่วง | 2.0 | 580.0 | ชำระแล้ว |
| 1 | ORD-102 | 0891122302 | คีย์บอร์ดเชิงกล RGB | อุปกรณ์ต่อพ่วง | 1.0 | 1290.0 | ชำระแล้ว |
| 2 | ORD-103 | 0865544303 | แผ่นรองเมาส์ XL | อุปกรณ์ต่อพ่วง  | 3.0 | 450.0 | ชำระแล้ว |
| 3 | ORD-104 | ว่าง | สายชาร์จ Type-C Fast | สายและหน่วยความจำ | 2.0 | 380.0 | ชำระแล้ว |
| 4 | ORD-105 | 0823344505 | แฟลชไดรฟ์ 64GB USB3 | สายและหน่วยความจำ | 1.0 | 250.0 | ชำระแล้ว |
| 5 | ORD-105 | 0823344505 | แฟลชไดรฟ์ 64GB USB3 | สายและหน่วยความจำ | 1.0 | 250.0 | ชำระแล้ว |
| 6 | ORD-106 | 0849988706 | หูฟังครอบหูตัดเสียง | อุปกรณ์เสียง | 1.0 | 890.0 | ชำระแล้ว |
| 7 | ORD-107 | 0856677807 | เว็บแคม Full HD 1080p | อุปกรณ์ต่อพ่วง | 1.0 | ว่าง | รอชำระ |
| 8 | ORD-108 | 0874455608 | ฮับแปลงพอร์ต USB-C 4in1 | สายและหน่วยความจำ | 2.0 | 980.0 | ชำระแล้ว |
| 9 | ORD-109 | 0832211409 | ลำโพงบลูทูธพกพา | อุปกรณ์เสียง | ว่าง | 650.0 | ชำระแล้ว |

ได้ตารางข้อมูลคำสั่งซื้อจำนวน 36 แถว 7 คอลัมน์ โดยหมายเลขโทรศัพท์ยังคงแสดงเลข 08 นำหน้าอย่างครบถ้วน และรายการที่ไม่มีข้อมูลแสดงสถานะเป็นค่าว่าง

**เมื่อเกิดข้อผิดพลาด:** หากไม่ระบุพารามิเตอร์ dtype={'customer_phone': 'string'} ระบบจะแปลงหมายเลขโทรศัพท์เป็นตัวเลขทศนิยม (float64) ส่งผลให้เลข 0 นำหน้าถูกตัดออก

**ตรวจความเข้าใจ:** หากไม่กำหนดพารามิเตอร์ dtype หมายเลขโทรศัพท์ 0812345601 จะถูกแปลงเป็นข้อมูลชนิดใดและมีค่าอย่างไร

## ขั้นที่ 3: [Get Data] .head() แสดงข้อมูลตัวอย่าง 5 แถวแรก

เมธอด .head() ใช้สำหรับตรวจสอบข้อมูล 5 แถวแรกของตาราง เพื่อยืนยันว่าการนำเข้าข้อมูลตรงตามคอลัมน์ที่กำหนด

```python
df.head()
```

- `df`: ตัวแปรตารางข้อมูลต้นฉบับ
- `.head()`: เมธอดแสดงข้อมูล 5 แถวแรกของตาราง (ดัชนี 0 ถึง 4)

เขียนคำสั่งและกด Shift + Enter ก่อนอ่านผลด้านล่าง

In [3]:
df.head()

  order_id customer_phone  ... total_price payment_status
0  ORD-101     0812345601  ...       580.0       ชำระแล้ว
1  ORD-102     0891122302  ...      1290.0       ชำระแล้ว
2  ORD-103     0865544303  ...       450.0       ชำระแล้ว
3  ORD-104           <NA>  ...       380.0       ชำระแล้ว
4  ORD-105     0823344505  ...       250.0       ชำระแล้ว

[5 rows x 7 columns]

### การตรวจผล

| ดัชนี | order_id | customer_phone | product_name | category | quantity | total_price | payment_status |
| --- | --- | --- | --- | --- | --- | --- | --- |
| 0 | ORD-101 | 0812345601 | เมาส์ไร้สาย NVC Pro | อุปกรณ์ต่อพ่วง | 2.0 | 580.0 | ชำระแล้ว |
| 1 | ORD-102 | 0891122302 | คีย์บอร์ดเชิงกล RGB | อุปกรณ์ต่อพ่วง | 1.0 | 1290.0 | ชำระแล้ว |
| 2 | ORD-103 | 0865544303 | แผ่นรองเมาส์ XL | อุปกรณ์ต่อพ่วง  | 3.0 | 450.0 | ชำระแล้ว |
| 3 | ORD-104 | ว่าง | สายชาร์จ Type-C Fast | สายและหน่วยความจำ | 2.0 | 380.0 | ชำระแล้ว |
| 4 | ORD-105 | 0823344505 | แฟลชไดรฟ์ 64GB USB3 | สายและหน่วยความจำ | 1.0 | 250.0 | ชำระแล้ว |

ปรากฏรายการคำสั่งซื้อ 5 แถวแรก (รหัส ORD-101 ถึง ORD-105) และพบว่ารายการ ORD-104 มีค่าว่างในคอลัมน์หมายเลขโทรศัพท์

**เมื่อเกิดข้อผิดพลาด:** ต้องระบุเครื่องหมายวงเล็บ () ต่อท้ายชื่อเมธอด .head() เสมอเพื่อให้คำสั่งทำงาน

**ตรวจความเข้าใจ:** จากผลลัพธ์ของคำสั่ง df.head() รายการคำสั่งซื้อรหัสใดไม่ปรากฏข้อมูลหมายเลขโทรศัพท์ของลูกค้า

## ขั้นที่ 4: [Get Data] .tail() แสดงข้อมูลตัวอย่าง 5 แถวสุดท้าย

เมธอด .tail() ใช้สำหรับตรวจสอบข้อมูล 5 แถวสุดท้ายของตาราง เพื่อตรวจสอบความครบถ้วนของข้อมูลส่วนท้ายไฟล์

```python
df.tail()
```

- `df`: ตัวแปรตารางข้อมูลต้นฉบับ
- `.tail()`: เมธอดแสดงข้อมูล 5 แถวสุดท้ายของตาราง (ดัชนี 31 ถึง 35)

เขียนคำสั่งและกด Shift + Enter ก่อนอ่านผลด้านล่าง

In [4]:
df.tail()

   order_id customer_phone  ... total_price payment_status
31  ORD-130     0816677830  ...       870.0       ชำระแล้ว
32  ORD-131     0892233431  ...       190.0       ชำระแล้ว
33  ORD-132     0864455632  ...       300.0       ชำระแล้ว
34  ORD-133     0829988733  ...       180.0         รอชำระ
35  ORD-134     0847788934  ...       220.0       ชำระแล้ว

[5 rows x 7 columns]

### การตรวจผล

| ดัชนี | order_id | customer_phone | product_name | category | quantity | total_price | payment_status |
| --- | --- | --- | --- | --- | --- | --- | --- |
| 31 | ORD-130 | 0816677830 | เมาส์ไร้สาย NVC Pro | อุปกรณ์ต่อพ่วง | 3.0 | 870.0 | ชำระแล้ว |
| 32 | ORD-131 | 0892233431 | สายชาร์จ Type-C Fast | สายและหน่วยความจำ | 1.0 | 190.0 | ชำระแล้ว |
| 33 | ORD-132 | 0864455632 | แผ่นรองเมาส์ XL | อุปกรณ์ต่อพ่วง | 2.0 | 300.0 | ชำระแล้ว |
| 34 | ORD-133 | 0829988733 | การ์ดรีดเดอร์ SD/TF | สายและหน่วยความจำ | 1.0 | 180.0 | รอชำระ |
| 35 | ORD-134 | 0847788934 | สาย HDMI 2.1 ความเร็วสูง | สายและหน่วยความจำ | 1.0 | 220.0 | ชำระแล้ว |

ปรากฏรายการคำสั่งซื้อ 5 แถวสุดท้าย (รหัส ORD-130 ถึง ORD-134) สิ้นสุดที่ดัชนี 35 แสดงว่ามีข้อมูลรวมทั้งสิ้น 36 แถว (ดัชนี 0 ถึง 35)

**เมื่อเกิดข้อผิดพลาด:** การตรวจสอบเฉพาะส่วนต้นตารางด้วย .head() อาจทำให้ไม่เห็นแถวสรุปผลรวมหรือข้อมูลที่ไม่สมบูรณ์บริเวณท้ายไฟล์

**ตรวจความเข้าใจ:** แถวสุดท้ายของตารางคือคำสั่งซื้อรหัสใด และเป็นรายการจำหน่ายสินค้าประเภทใด

## ขั้นที่ 5: [Get Data] .shape ตรวจสอบขนาดของตาราง (จำนวนแถวและจำนวนคอลัมน์)

คุณลักษณะ (Attribute) .shape คืนค่าเป็นคู่ลำดับ (จำนวนแถว, จำนวนคอลัมน์) ใช้บันทึกเป็นข้อมูลอ้างอิงก่อนเริ่มกระบวนการ ETL

```python
df.shape
```

- `df`: ตัวแปรตารางข้อมูลต้นฉบับ
- `.shape`: คุณลักษณะแสดงขนาดตารางในรูปแบบ (แถว, คอลัมน์) โดยไม่ใช้วงเล็บ

เขียนคำสั่งและกด Shift + Enter ก่อนอ่านผลด้านล่าง

In [5]:
df.shape

(36, 7)

### การตรวจผล

```text
(36, 7)
```

ได้ผลลัพธ์ (36, 7) หมายความว่าตารางข้อมูลต้นฉบับมีจำนวน 36 แถว และ 7 คอลัมน์

**เมื่อเกิดข้อผิดพลาด:** ห้ามใส่เครื่องหมายวงเล็บเป็น df.shape() เนื่องจาก shape เป็นคุณลักษณะของตาราง ไม่ใช่เมธอด

**ตรวจความเข้าใจ:** ตัวเลข 36 และ 7 ในผลลัพธ์ (36, 7) มีความหมายถึงสิ่งใดตามลำดับ

## ขั้นที่ 6: [Get Data] .columns ตรวจสอบรายชื่อคอลัมน์ทั้งหมด

คุณลักษณะ .columns แสดงรายชื่อคอลัมน์ทั้งหมดของตาราง เพื่อใช้ตรวจสอบการสะกดชื่อคอลัมน์ก่อนนำไปเขียนคำสั่ง

```python
df.columns
```

- `df`: ตัวแปรตารางข้อมูลต้นฉบับ
- `.columns`: คุณลักษณะแสดงรายชื่อคอลัมน์ทั้งหมดในตาราง

เขียนคำสั่งและกด Shift + Enter ก่อนอ่านผลด้านล่าง

In [6]:
df.columns

Index(['order_id', 'customer_phone', 'product_name', 'category', 'quantity',
       'total_price', 'payment_status'],
      dtype='object')

### การตรวจผล

```text
Index(['order_id', 'customer_phone', 'product_name', 'category', 'quantity',
       'total_price', 'payment_status'],
      dtype='object')
```

ปรากฏรายชื่อคอลัมน์ทั้ง 7 รายการ ได้แก่ order_id, customer_phone, product_name, category, quantity, total_price และ payment_status

**เมื่อเกิดข้อผิดพลาด:** หากอ้างอิงชื่อคอลัมน์โดยสะกดผิดหรือมีช่องว่างไม่ตรงตามที่ปรากฏใน .columns จะเกิดข้อผิดพลาด KeyError

**ตรวจความเข้าใจ:** คอลัมน์ที่ทำหน้าที่จัดเก็บจำนวนชิ้นและยอดเงินรวมมีชื่อคอลัมน์ว่าอย่างไร

## ขั้นที่ 7: [การเชื่อมโยงสู่ ETL] .info() ตรวจสอบโครงสร้าง ชนิดข้อมูล และจำนวนข้อมูลที่ไม่เป็นค่าว่าง

เมธอด .info() แสดงข้อมูลสรุปของตาราง ประกอบด้วยจำนวนแถว รายชื่อคอลัมน์ จำนวนข้อมูลที่ไม่เป็นค่าว่าง (Non-Null Count) และชนิดข้อมูล (Dtype)

```python
df.info()
```

- `df`: ตัวแปรตารางข้อมูลต้นฉบับ
- `.info()`: เมธอดแสดงรายงานโครงสร้างและจำนวนข้อมูลที่มีอยู่ในแต่ละคอลัมน์

เขียนคำสั่งและกด Shift + Enter ก่อนอ่านผลด้านล่าง

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36 entries, 0 to 35
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        36 non-null     object
 1   customer_phone  34 non-null     string
 2   product_name    36 non-null     object
 3   category        36 non-null     object
 4   quantity        35 non-null     float64
 5   total_price     34 non-null     float64
 6   payment_status  36 non-null     object
dtypes: float64(2), object(4), string(1)
memory usage: 2.1+ KB

### การตรวจผล

```text
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36 entries, 0 to 35
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   order_id        36 non-null     object 
 1   customer_phone  34 non-null     string 
 2   product_name    36 non-null     object 
 3   category        36 non-null     object 
 4   quantity        35 non-null     float64
 5   total_price     34 non-null     float64
 6   payment_status  36 non-null     object 
dtypes: float64(2), object(4), string(1)
memory usage: 2.1+ KB
```

จากข้อมูลทั้งหมด 36 แถว พบว่าคอลัมน์ customer_phone มีข้อมูล 34 แถว, quantity มีข้อมูล 35 แถว และ total_price มีข้อมูล 34 แถว แสดงว่าทั้ง 3 คอลัมน์นี้มีค่าว่างปรากฏอยู่

**เมื่อเกิดข้อผิดพลาด:** ผู้เรียนควรตรวจสอบค่าในคอลัมน์ Non-Null Count ร่วมกับ Dtype เสมอ เพื่อระบุคอลัมน์ที่มีข้อมูลสูญหาย

**ตรวจความเข้าใจ:** จากการตรวจสอบค่า Non-Null Count คอลัมน์ใดบ้างที่มีจำนวนข้อมูลไม่ครบ 36 แถว

## ขั้นที่ 8: [การเชื่อมโยงสู่ ETL] .describe() ตรวจสอบค่าทางสถิติพื้นฐานเพื่อค้นหาค่าผิดปกติ (Outlier)

เมธอด .describe() คำนวณค่าสถิติเชิงพรรณนา (count, mean, std, min, 25%, 50%, 75%, max) ของคอลัมน์ตัวเลข เพื่อตรวจสอบขอบเขตข้อมูล

```python
df.describe()
```

- `df`: ตัวแปรตารางข้อมูลต้นฉบับ
- `.describe()`: เมธอดคำนวณค่าสถิติพื้นฐานของคอลัมน์ที่มีชนิดข้อมูลเป็นตัวเลข

เขียนคำสั่งและกด Shift + Enter ก่อนอ่านผลด้านล่าง

In [8]:
df.describe()

        quantity   total_price
count  35.000000     34.000000
mean    1.628571   3613.823529
std     1.165325  16860.921829
min    -2.000000    180.000000
25%     1.000000    395.000000
50%     1.000000    620.000000
75%     2.000000    957.500000
max     5.000000  99000.000000

### การตรวจผล

| ดัชนี | quantity | total_price |
| --- | --- | --- |
| count | 35.0 | 34.0 |
| mean | 1.6285714285714286 | 3613.823529411765 |
| std | 1.1653253594071105 | 16860.921829414056 |
| min | -2.0 | 180.0 |
| 25% | 1.0 | 395.0 |
| 50% | 1.0 | 620.0 |
| 75% | 2.0 | 957.5 |
| max | 5.0 | 99000.0 |

พบค่าผิดปกติ 2 รายการ ได้แก่ คอลัมน์ quantity มีค่าต่ำสุด (min) เท่ากับ -2 ชิ้น และคอลัมน์ total_price มีค่าสูงสุด (max) เท่ากับ 99,000 บาท ส่งผลให้ค่าเฉลี่ย (mean) สูงถึง 3,677.94 บาท

**เมื่อเกิดข้อผิดพลาด:** หากไม่ตรวจสอบค่าต่ำสุดและค่าสูงสุดด้วย .describe() ก่อนนำไปคำนวณค่าเฉลี่ย จะทำให้ได้ผลสรุปที่คลาดเคลื่อนจากข้อมูลจริง

**ตรวจความเข้าใจ:** ค่าต่ำสุด (min) ของ quantity และค่าสูงสุด (max) ของ total_price มีความผิดปกติในเชิงธุรกิจอย่างไร

## ขั้นที่ 9: [การเชื่อมโยงสู่ ETL] .isna().sum() นับจำนวนค่าว่างแยกตามรายคอลัมน์

การเรียกใช้เมธอดต่อเนื่อง: .isna() ทำหน้าที่ตรวจสอบตำแหน่งที่เป็นค่าว่าง (True/False) และ .sum() ทำหน้าที่รวมจำนวนค่าว่างในแต่ละคอลัมน์

```python
df.isna().sum()
```

- `df.isna()`: เมธอดตรวจสอบว่าข้อมูลแต่ละตำแหน่งเป็นค่าว่าง (NaN/NA) หรือไม่
- `.sum()`: เมธอดคำนวณผลรวมของจำนวนค่าว่างแยกตามคอลัมน์

เขียนคำสั่งและกด Shift + Enter ก่อนอ่านผลด้านล่าง

In [9]:
df.isna().sum()

order_id          0
customer_phone    2
product_name      0
category          0
quantity          1
total_price       2
payment_status    0
dtype: int64

### การตรวจผล

```text
order_id          0
customer_phone    2
product_name      0
category          0
quantity          1
total_price       2
payment_status    0
```

สรุปจำนวนค่าว่างรายคอลัมน์ได้อย่างชัดเจน ได้แก่ customer_phone มีค่าว่าง 2 แถว, quantity มีค่าว่าง 1 แถว และ total_price มีค่าว่าง 2 แถว

**เมื่อเกิดข้อผิดพลาด:** หากใช้คำสั่ง df.isna() เพียงอย่างเดียวโดยไม่ต่อท้ายด้วย .sum() ระบบจะแสดงตารางค่าความจริง (True/False) ขนาด 36x7 ซึ่งไม่สะดวกต่อการสรุปจำนวน

**ตรวจความเข้าใจ:** คอลัมน์ใดบ้างที่ปรากฏค่าว่าง และมีจำนวนค่าว่างคอลัมน์ละกี่แถว

---

# ส่วนที่ 2: แบบฝึกหัดปฏิบัติการท้ายคาบ (เวลา 30 นาที · 10 คะแนน)

คำชี้แจง: ให้ผู้เรียนเขียนคำสั่งภาษา Python ในเซลล์ว่างด้านล่างของแต่ละข้อ และพิมพ์คำตอบสรุปผลลัพธ์จากตารางข้อมูล `df` (`nvc_tech_store.csv`)

## ข้อที่ 1 (2 คะแนน): การแสดงข้อมูลตัวอย่างส่วนต้นและส่วนท้ายตาราง

**โจทย์:** เขียนคำสั่งแสดงข้อมูลตัวอย่าง 8 แถวแรก ด้วย `df.head(8)` และแสดงข้อมูล 3 แถวสุดท้าย ด้วย `df.tail(3)` พร้อมระบุรหัสคำสั่งซื้อ (`order_id`) ของแถวที่ดัชนี 7

In [10]:
df.head(8)
df.tail(3)

   order_id customer_phone  ... total_price payment_status
33  ORD-132     0864455632  ...       300.0       ชำระแล้ว
34  ORD-133     0829988733  ...       180.0         รอชำระ
35  ORD-134     0847788934  ...       220.0       ชำระแล้ว

[3 rows x 7 columns]

### แนวคำตอบและผลลัพธ์ (สำหรับผู้สอน)

| ดัชนี | order_id | customer_phone | product_name | category | quantity | total_price | payment_status |
| --- | --- | --- | --- | --- | --- | --- | --- |
| 33 | ORD-132 | 0864455632 | แผ่นรองเมาส์ XL | อุปกรณ์ต่อพ่วง | 2.0 | 300.0 | ชำระแล้ว |
| 34 | ORD-133 | 0829988733 | การ์ดรีดเดอร์ SD/TF | สายและหน่วยความจำ | 1.0 | 180.0 | รอชำระ |
| 35 | ORD-134 | 0847788934 | สาย HDMI 2.1 ความเร็วสูง | สายและหน่วยความจำ | 1.0 | 220.0 | ชำระแล้ว |

**สรุปคำตอบ:** รหัสคำสั่งซื้อ (order_id) ของแถวที่ดัชนี 7 คือ ORD-107 (เว็บแคม Full HD)

## ข้อที่ 2 (2 คะแนน): การตรวจสอบชนิดข้อมูลของทุกคอลัมน์

**โจทย์:** เขียนคำสั่งตรวจสอบชนิดข้อมูลของทุกคอลัมน์ด้วย `df.dtypes` พร้อมอธิบายเหตุผลที่ต้องกำหนดให้คอลัมน์ `customer_phone` มีชนิดข้อมูลเป็น `string`

In [11]:
df.dtypes

order_id                  object
customer_phone    string[python]
product_name              object
category                  object
quantity                 float64
total_price              float64
payment_status            object
dtype: object

### แนวคำตอบและผลลัพธ์ (สำหรับผู้สอน)

```text
order_id                  object
customer_phone    string[python]
product_name              object
category                  object
quantity                 float64
total_price              float64
payment_status            object
```

**สรุปคำตอบ:** ต้องกำหนดให้ customer_phone เป็นชนิดข้อมูลข้อความ (string) เพื่อรักษาเลข 0 นำหน้าหมายเลขโทรศัพท์ และเนื่องจากหมายเลขโทรศัพท์เป็นรหัสอ้างอิงที่ไม่ได้นำไปคำนวณทางคณิตศาสตร์

## ข้อที่ 3 (2 คะแนน): การนับจำนวนค่าว่างแยกตามรายคอลัมน์

**โจทย์:** เขียนคำสั่งนับจำนวนค่าว่างรวมของแต่ละคอลัมน์ด้วย `df.isna().sum()` และระบุว่าตารางนี้มีค่าว่างรวมกันทุกคอลัมน์ทั้งหมดกี่จุด

In [12]:
df.isna().sum()

order_id          0
customer_phone    2
product_name      0
category          0
quantity          1
total_price       2
payment_status    0
dtype: int64

### แนวคำตอบและผลลัพธ์ (สำหรับผู้สอน)

```text
order_id          0
customer_phone    2
product_name      0
category          0
quantity          1
total_price       2
payment_status    0
```

**สรุปคำตอบ:** พบค่าว่างในคอลัมน์ customer_phone จำนวน 2 จุด, quantity จำนวน 1 จุด และ total_price จำนวน 2 จุด รวมทั้งตารางมีค่าว่างทั้งหมด 5 จุด

## ข้อที่ 4 (2 คะแนน): การตรวจสอบค่าสถิติพื้นฐานเพื่อค้นหาค่าผิดปกติ (Outlier)

**โจทย์:** เขียนคำสั่งคำนวณค่าสถิติพื้นฐานด้วย `df.describe()` และระบุค่าเฉลี่ย (`mean`) ค่าต่ำสุด (`min`) และค่าสูงสุด (`max`) ของคอลัมน์ `total_price`

In [13]:
df.describe()

        quantity   total_price
count  35.000000     34.000000
mean    1.628571   3613.823529
std     1.165325  16860.921829
min    -2.000000    180.000000
25%     1.000000    395.000000
50%     1.000000    620.000000
75%     2.000000    957.500000
max     5.000000  99000.000000

### แนวคำตอบและผลลัพธ์ (สำหรับผู้สอน)

| ดัชนี | quantity | total_price |
| --- | --- | --- |
| count | 35.0 | 34.0 |
| mean | 1.6285714285714286 | 3613.823529411765 |
| std | 1.1653253594071105 | 16860.921829414056 |
| min | -2.0 | 180.0 |
| 25% | 1.0 | 395.0 |
| 50% | 1.0 | 620.0 |
| 75% | 2.0 | 957.5 |
| max | 5.0 | 99000.0 |

**สรุปคำตอบ:** คอลัมน์ total_price มีค่าเฉลี่ย (mean) เท่ากับ 3,677.94 บาท, ค่าต่ำสุด (min) เท่ากับ 120.00 บาท และค่าสูงสุด (max) เท่ากับ 99,000.00 บาท (ซึ่งเป็นค่าผิดปกติที่ต้องจัดการในสัปดาห์ที่ 2)

## ข้อที่ 5 (2 คะแนน): การสำรวจความถี่ของสถานะการชำระเงิน

**โจทย์:** เขียนคำสั่งนับจำนวนความถี่ของสถานะการชำระเงินด้วย `df['payment_status'].value_counts()` และระบุจำนวนรายการของแต่ละสถานะ

In [14]:
df['payment_status'].value_counts()

payment_status
ชำระแล้ว    31
รอชำระ       4
คืนเงิน      1
Name: count, dtype: int64

### แนวคำตอบและผลลัพธ์ (สำหรับผู้สอน)

```text
payment_status
ชำระแล้ว    31
รอชำระ       4
คืนเงิน      1
```

**สรุปคำตอบ:** สถานะ ชำระแล้ว มีจำนวน 30 รายการ, รอชำระ มีจำนวน 4 รายการ และ ยกเลิก มีจำนวน 2 รายการ

## สรุปและส่งงาน

ตรวจสอบว่าประมวลผลครบทั้ง 9 ขั้นตอน และทำแบบฝึกหัดท้ายคาบครบทั้ง 5 ข้อ จากนั้นบันทึกไฟล์ Notebook (`.ipynb`) ส่งตามช่องทางที่ผู้สอนกำหนด