# W02 — Get Data การรวบรวมและนำเข้าข้อมูล

## จุดประสงค์การเรียนรู้
- อธิบายหลักการของกระบวนการจัดเตรียมข้อมูล (ETL: Extract, Transform, Load) และผลกระทบของข้อมูลที่ไม่มีคุณภาพต่อการวิเคราะห์ได้
- เขียนคำสั่งภาษา Python ด้วยไลบรารี pandas เพื่อคัดกรองและแก้ไขปัญหาคุณภาพข้อมูลพื้นฐาน (อักขระช่องว่าง ข้อมูลซ้ำ ค่าว่าง และค่าผิดปกติ) ได้อย่างเป็นระบบ
- จัดเตรียมข้อมูลจากแผ่นงาน Excel โดยจัดมาตรฐานข้อความ เติมค่าว่างตามเงื่อนไข ตรวจข้อมูลซ้ำ และแปลงชนิดข้อมูลวันที่ได้
- ตรวจสอบคุณภาพตารางข้อมูลหลังทำความสะอาดและส่งออกเป็นไฟล์ CSV โดยไม่บันทึกลำดับแถวได้

## การเตรียมไฟล์ข้อมูล
- nvc_tech_store.csv

อัปโหลดไฟล์ข้อมูลผ่านเมนู Files ในโปรแกรม Google Colab แล้วพิมพ์คำสั่งและรันผลลัพธ์ตามลำดับทีละขั้นตอน

## โครงสร้างชุดข้อมูล
- ไฟล์ nvc_tech_store.csv: จำนวน 36 แถว 7 คอลัมน์ ได้แก่ order_id, customer_phone, product_name, category, quantity, total_price, payment_status

---

# ส่วนที่ 1: แบบฝึกหัดทบทวนก่อนเรียน (ทบทวนคำสั่งพื้นฐานจากสัปดาห์ที่ 1 · เวลา 30 นาที)

คำชี้แจง: ให้ผู้เรียนเขียนคำสั่งทบทวนการนำเข้าและสำรวจข้อมูล `nvc_tech_store.csv` ลงในเซลล์โค้ดทั้ง 3 ข้อด้านล่างก่อนเริ่มเรียนเนื้อหาใหม่

## ข้อที่ 1: ทบทวนการนำเข้าข้อมูลและกำหนดชนิดข้อมูลหมายเลขโทรศัพท์

**โจทย์:** เขียนคำสั่งนำเข้าไลบรารี `pandas` และอ่านไฟล์ `nvc_tech_store.csv` ลงในตัวแปร `df` โดยกำหนดชนิดข้อมูลของคอลัมน์ `customer_phone` เป็น `string` จากนั้นแสดงข้อมูลตัวอย่าง 3 แถวแรก

In [1]:
import pandas as pd
df = pd.read_csv('nvc_tech_store.csv', dtype={'customer_phone': 'string'})
df.head(3)

  order_id customer_phone  ... total_price payment_status
0  ORD-101     0812345601  ...       580.0       ชำระแล้ว
1  ORD-102     0891122302  ...      1290.0       ชำระแล้ว
2  ORD-103     0865544303  ...       450.0       ชำระแล้ว

[3 rows x 7 columns]

### แนวคำตอบทบทวน

| ลำดับแถว | order_id | customer_phone | product_name | category | quantity | total_price | payment_status |
| --- | --- | --- | --- | --- | --- | --- | --- |
| 0 | ORD-101 | 0812345601 | เมาส์ไร้สาย NVC Pro | อุปกรณ์ต่อพ่วง | 2.0 | 580.0 | ชำระแล้ว |
| 1 | ORD-102 | 0891122302 | คีย์บอร์ดเชิงกล RGB | อุปกรณ์ต่อพ่วง | 1.0 | 1290.0 | ชำระแล้ว |
| 2 | ORD-103 | 0865544303 | แผ่นรองเมาส์ XL | อุปกรณ์ต่อพ่วง  | 3.0 | 450.0 | ชำระแล้ว |

**สรุปผล:** นำเข้าตารางข้อมูลขนาด 36 แถว 7 คอลัมน์ โดยหมายเลขโทรศัพท์ยังคงแสดงเลข 08 นำหน้าครบถ้วน

## ข้อที่ 2: ทบทวนการสำรวจขนาดตารางและรายชื่อคอลัมน์

**โจทย์:** เขียนคำสั่งตรวจสอบขนาดของตารางด้วยคำสั่ง `df.shape` และแสดงรายชื่อคอลัมน์ทั้งหมดด้วยคำสั่ง `df.columns`

In [2]:
df.shape, df.columns.tolist()

((36, 7), ['order_id', 'customer_phone', 'product_name', 'category', 'quantity', 'total_price', 'payment_status'])

### แนวคำตอบทบทวน

```text
((36, 7), ['order_id', 'customer_phone', 'product_name', 'category', 'quantity', 'total_price', 'payment_status'])
```

**สรุปผล:** ตารางข้อมูลต้นฉบับมีขนาด (36, 7) คือ 36 แถว 7 คอลัมน์

## ข้อที่ 3: ทบทวนการตรวจสอบจำนวนค่าว่างและค่าสถิติพื้นฐาน

**โจทย์:** เขียนคำสั่งนับจำนวนค่าว่างแยกตามรายคอลัมน์ด้วยคำสั่ง `df.isna().sum()` และคำนวณค่าสถิติพื้นฐานด้วยคำสั่ง `df.describe()`

In [3]:
df.isna().sum()
df.describe()

        quantity   total_price
count  35.000000     34.000000
mean    1.628571   3613.823529
std     1.165325  16860.921829
min    -2.000000    180.000000
25%     1.000000    395.000000
50%     1.000000    620.000000
75%     2.000000    957.500000
max     5.000000  99000.000000

### แนวคำตอบทบทวน

| ลำดับแถว | quantity | total_price |
| --- | --- | --- |
| count | 35.0 | 34.0 |
| mean | 1.6285714285714286 | 3613.823529411765 |
| std | 1.1653253594071105 | 16860.921829414056 |
| min | -2.0 | 180.0 |
| 25% | 1.0 | 395.0 |
| 50% | 1.0 | 620.0 |
| 75% | 2.0 | 957.5 |
| max | 5.0 | 99000.0 |

**สรุปผล:** พบค่าว่างรวม 5 จุด และพบค่าผิดปกติในคอลัมน์ quantity (-2 ชิ้น) และ total_price (99,000 บาท)

---

# ส่วนที่ 2: ทฤษฎีและหลักการจัดเตรียมข้อมูล (ETL)

## ความหมายและองค์ประกอบของกระบวนการ ETL (Extract – Transform – Load)
- Extract (การดึงและนำเข้าข้อมูล): ขั้นตอนการรวบรวมและอ่านข้อมูลจากแหล่งข้อมูลต้นทาง เช่น ไฟล์ CSV หรือไฟล์ Excel เข้าสู่โปรแกรมประมวลผล พร้อมกำหนดชนิดข้อมูลเบื้องต้นให้ถูกต้องตามลักษณะการใช้งาน
- Transform (การปรับรูปแบบและทำความสะอาดข้อมูล): ขั้นตอนการตรวจสอบ คัดกรอง และแก้ไขความผิดพลาดของข้อมูล เช่น การตัดอักขระช่องว่างส่วนเกิน การลบข้อมูลที่บันทึกซ้ำซ้อน การจัดการค่าว่าง และการคัดกรองค่าที่อยู่นอกเกณฑ์ที่กำหนด
- Load (การจัดเก็บและส่งออกข้อมูล): ขั้นตอนการบันทึกตารางข้อมูลที่ผ่านการจัดเตรียมแล้วออกเป็นไฟล์ข้อมูลชุดใหม่ที่มีความถูกต้องสมบูรณ์ เพื่อนำไปใช้วิเคราะห์คำนวณหรือสร้างแผนภูมินำเสนอในลำดับถัดไป

## ความสำคัญของการจัดเตรียมข้อมูลต่อความถูกต้องของผลการวิเคราะห์
- หลักการคุณภาพของข้อมูล (Garbage In, Garbage Out): หากนำตารางข้อมูลต้นฉบับที่มีข้อผิดพลาดมาคำนวณทันที ผลลัพธ์ที่ได้ย่อมคลาดเคลื่อนจากความเป็นจริง แม้ว่าจะเขียนคำสั่งคำนวณได้ถูกต้องตามหลักไวยากรณ์ก็ตาม
- ผลกระทบต่อการคำนวณยอดรวมและค่าเฉลี่ย: การบันทึกข้อมูลซ้ำซ้อนทำให้นับจำนวนคำสั่งซื้อและยอดขายรวมเกินจริง ส่วนค่าผิดปกติเพียงรายการเดียว (เช่น 99,000 บาท) ส่งผลให้ค่าเฉลี่ยคลาดเคลื่อนจาก 754.83 บาท ไปเป็น 3,613.82 บาท
- ผลกระทบต่อการจัดกลุ่มและสรุปรายงาน: อักขระช่องว่างส่วนเกินต่อท้ายข้อความทำให้โปรแกรมแยกนับหมวดหมู่สินค้าเดียวกันออกเป็นคนละกลุ่ม ส่งผลให้ตารางสรุปจำนวนสินค้าแยกตามหมวดหมู่ขาดความถูกต้อง

## ปัญหาคุณภาพข้อมูล 4 รูปแบบหลักที่ต้องตรวจสอบในขั้นตอน Transform
- ข้อมูลสูญหายหรือค่าว่าง (Missing Values): ข้อมูลที่ไม่ได้ถูกบันทึกในบางคอลัมน์ (แสดงเป็น NaN หรือ <NA>) ผู้วิเคราะห์ต้องพิจารณาแยกแยะระหว่างคอลัมน์สำคัญที่ใช้คำนวณยอดขาย กับคอลัมน์ข้อมูลทั่วไปที่สามารถคงแถวข้อมูลไว้ได้
- การบันทึกข้อมูลซ้ำซ้อน (Duplicate Data): รายการคำสั่งซื้อเดียวกันถูกบันทึกซ้ำมากกว่า 1 แถวในทุกคอลัมน์ ซึ่งต้องตรวจสอบแถวที่ซ้ำและตัดออกให้เหลือเพียงรายการจริงเพียงรายการเดียว
- รูปแบบข้อความไม่เป็นมาตรฐานเดียวกัน (Inconsistent Text): ข้อมูลข้อความที่มีอักขระช่องว่างส่วนเกินด้านหน้าหรือด้านหลัง เช่น 'อุปกรณ์ต่อพ่วง ' ซึ่งต้องปรับรูปแบบข้อความให้เป็นมาตรฐานเดียวกันก่อนจัดกลุ่มข้อมูล
- ค่าผิดปกติหรือค่าที่อยู่นอกเกณฑ์ที่กำหนด (Outliers / Invalid Values): ข้อมูลตัวเลขที่ไม่สอดคล้องกับความเป็นจริง เช่น จำนวนชิ้นที่ติดลบ (-2 ชิ้น) หรือยอดเงินที่สูงผิดปกติจากการบันทึกข้อมูลผิดพลาด (99,000 บาท)

## หลักปฏิบัติมาตรฐานในการจัดเตรียมข้อมูลด้วยไลบรารี pandas
- การตรวจสอบข้อมูลก่อนดำเนินการแก้ไข (Inspect Before Transform): ใช้การคัดกรองตามเงื่อนไข (Boolean Indexing) เพื่อแสดงเฉพาะแถวที่มีปัญหาขึ้นมาตรวจสอบรายละเอียดก่อนสั่งลบหรือแก้ไขข้อมูล
- การแยกตัวแปรเพื่อรักษาตารางข้อมูลต้นฉบับ (Preserve Original Data): ควรจัดเก็บตารางข้อมูลที่ผ่านการลบแถวซ้ำซ้อนและคัดกรองค่าว่างไว้ในตัวแปรใหม่ชื่อ df_clean เพื่อเก็บรักษาตารางข้อมูลต้นฉบับ (df) ไว้ใช้ตรวจสอบเปรียบเทียบ
- การเลือกลบค่าว่างเฉพาะคอลัมน์สำคัญ (Selective Cleaning): ระบุพารามิเตอร์ subset ในคำสั่ง .dropna() เพื่อลบเฉพาะแถวที่ขาดข้อมูลจำนวนชิ้นหรือยอดเงินรวม โดยไม่ลบรายการที่ขาดเพียงหมายเลขโทรศัพท์
- การส่งออกไฟล์ข้อมูลโดยไม่บันทึกลำดับแถว (Clean Export): เมื่อบันทึกไฟล์ใหม่ด้วยคำสั่ง .to_csv() ต้องกำหนดพารามิเตอร์ index=False เสมอ เพื่อป้องกันไม่ให้ลำดับแถวถูกบันทึกเป็นคอลัมน์เกินมาในไฟล์ CSV

---

# ส่วนที่ 3: การฝึกปฏิบัติการจัดเตรียมข้อมูลด้วยกระบวนการ ETL (ขั้นตอนที่ 1–10)

## ขั้นตอนที่ 1: การนำเข้าไลบรารี pandas และอ่านไฟล์ชุดข้อมูลต้นฉบับ nvc_tech_store.csv

นำเข้าไลบรารี pandas และอ่านตารางข้อมูลต้นฉบับ nvc_tech_store.csv พร้อมกำหนดชนิดข้อมูลของคอลัมน์หมายเลขโทรศัพท์ให้เป็นข้อความ

```python
import pandas as pd
df = pd.read_csv('nvc_tech_store.csv', dtype={'customer_phone': 'string'})
df.shape
```

- `import pandas as pd`: นำเข้าไลบรารี pandas โดยกำหนดชื่อย่อเป็น pd
- `pd.read_csv('nvc_tech_store.csv', dtype={'customer_phone': 'string'})`: อ่านไฟล์ข้อมูล CSV และกำหนดชนิดข้อมูลคอลัมน์หมายเลขโทรศัพท์เป็นข้อความ
- `df.shape`: ตรวจสอบขนาดของตารางข้อมูลต้นฉบับ ซึ่งมีขนาด (36, 7)

พิมพ์คำสั่งและกดปุ่ม Shift + Enter เพื่อรันคำสั่งและตรวจสอบผลลัพธ์

In [1]:
import pandas as pd
df = pd.read_csv('nvc_tech_store.csv', dtype={'customer_phone': 'string'})
df.shape

(36, 7)

### ผลลัพธ์และคำอธิบาย

```text
(36, 7)
```

ได้ตารางข้อมูลต้นฉบับขนาด 36 แถว 7 คอลัมน์ พร้อมสำหรับการตรวจสอบและจัดเตรียมข้อมูลในขั้นตอนถัดไป

**ข้อควรระวังในการเขียนคำสั่ง:** ต้องตรวจสอบว่าได้อัปโหลดไฟล์ nvc_tech_store.csv เข้าสู่โปรแกรม Google Colab เรียบร้อยแล้วก่อนรันคำสั่ง

**คำถามตรวจสอบความเข้าใจ:** ตารางข้อมูลต้นฉบับก่อนเริ่มกระบวนการจัดเตรียมข้อมูลมีจำนวนแถวและคอลัมน์เท่าใด

## ขั้นตอนที่ 2: การคัดกรองแถวที่มีค่าว่างด้วยเงื่อนไข (Boolean Indexing)

ระบุเงื่อนไข df['total_price'].isna() ภายในเครื่องหมายวงเล็บเหลี่ยม df[...] เพื่อแสดงเฉพาะแถวที่ไม่มีข้อมูลยอดเงินรวม

```python
df[df['total_price'].isna()]
```

- `df[...]`: การคัดกรองตารางเพื่อแสดงเฉพาะแถวที่ตรงตามเงื่อนไขที่กำหนด
- `df['total_price'].isna()`: เงื่อนไขสำหรับตรวจสอบว่าแถวใดในคอลัมน์ total_price มีค่าว่าง

พิมพ์คำสั่งและกดปุ่ม Shift + Enter เพื่อรันคำสั่งและตรวจสอบผลลัพธ์

In [2]:
df[df['total_price'].isna()]

   order_id customer_phone  ... total_price payment_status
7   ORD-107     0856677807  ...         NaN         รอชำระ
26  ORD-125     0841122325  ...         NaN       ชำระแล้ว

[2 rows x 7 columns]

### ผลลัพธ์และคำอธิบาย

| ลำดับแถว | order_id | customer_phone | product_name | category | quantity | total_price | payment_status |
| --- | --- | --- | --- | --- | --- | --- | --- |
| 7 | ORD-107 | 0856677807 | เว็บแคม Full HD 1080p | อุปกรณ์ต่อพ่วง | 1.0 | ว่าง | รอชำระ |
| 26 | ORD-125 | 0841122325 | สายแลน Cat6 5 เมตร | สายและหน่วยความจำ | 3.0 | ว่าง | ชำระแล้ว |

พบรายการคำสั่งซื้อที่ไม่มีข้อมูลยอดเงินรวมจำนวน 2 รายการ ได้แก่ รหัส ORD-107 (เว็บแคม Full HD 1080p) และรหัส ORD-125 (สายแลน Cat6 5 เมตร)

**ข้อควรระวังในการเขียนคำสั่ง:** ต้องใส่วงเล็บเหลี่ยมให้ครบทั้งส่วนของการคัดกรองตาราง df[...] และส่วนของการอ้างอิงชื่อคอลัมน์ df['total_price']

**คำถามตรวจสอบความเข้าใจ:** รายการคำสั่งซื้อรหัสใดบ้างที่ไม่มีข้อมูลในคอลัมน์ยอดเงินรวม (total_price)

## ขั้นตอนที่ 3: การนับจำนวนแถวข้อมูลที่ซ้ำซ้อนด้วยคำสั่ง df.duplicated().sum()

ใช้คำสั่ง .duplicated() เพื่อตรวจสอบแถวที่มีข้อมูลซ้ำกับแถวก่อนหน้าในทุกคอลัมน์ และใช้ .sum() เพื่อรวมจำนวนแถวที่ซ้ำซ้อนทั้งหมด

```python
df.duplicated().sum()
```

- `df.duplicated()`: คำสั่งตรวจสอบแถวที่มีข้อมูลซ้ำกับแถวก่อนหน้าทุกคอลัมน์
- `.sum()`: คำสั่งรวมจำนวนแถวที่ตรวจพบว่าเป็นข้อมูลซ้ำซ้อน

พิมพ์คำสั่งและกดปุ่ม Shift + Enter เพื่อรันคำสั่งและตรวจสอบผลลัพธ์

In [3]:
df.duplicated().sum()

2

### ผลลัพธ์และคำอธิบาย

```text
2
```

ได้ผลลัพธ์เท่ากับ 2 แสดงว่ามีรายการคำสั่งซื้อที่ถูกบันทึกข้อมูลซ้ำซ้อนเกินจำนวนจริง 2 แถว

**ข้อควรระวังในการเขียนคำสั่ง:** หากไม่ตรวจสอบและลบแถวที่บันทึกข้อมูลซ้ำซ้อน จะทำให้การคำนวณยอดจำหน่ายรวมและจำนวนคำสั่งซื้อนับซ้ำซ้อนเกินจำนวนจริง

**คำถามตรวจสอบความเข้าใจ:** ในชุดข้อมูลนี้มีแถวข้อมูลที่ถูกบันทึกซ้ำซ้อนจำนวนกี่แถว

## ขั้นตอนที่ 4: การแสดงแถวข้อมูลที่ซ้ำซ้อนทั้งหมดด้วยคำสั่ง df[df.duplicated(keep=False)]

กำหนดพารามิเตอร์ keep=False ในคำสั่ง .duplicated() เพื่อแสดงทั้งแถวข้อมูลต้นฉบับและแถวที่บันทึกซ้ำซ้อนขึ้นมาเปรียบเทียบกัน

```python
df[df.duplicated(keep=False)]
```

- `df[...]`: การคัดกรองตารางเพื่อแสดงเฉพาะแถวที่ตรงตามเงื่อนไข
- `df.duplicated(keep=False)`: เงื่อนไขที่กำหนดให้แสดงทุกแถวที่มีข้อมูลซ้ำกันทั้งหมด (ทั้งแถวแรกและแถวที่ซ้ำ)

พิมพ์คำสั่งและกดปุ่ม Shift + Enter เพื่อรันคำสั่งและตรวจสอบผลลัพธ์

In [4]:
df[df.duplicated(keep=False)]

   order_id customer_phone  ... total_price payment_status
4   ORD-105     0823344505  ...       250.0       ชำระแล้ว
5   ORD-105     0823344505  ...       250.0       ชำระแล้ว
18  ORD-118     0836655418  ...       580.0       ชำระแล้ว
19  ORD-118     0836655418  ...       580.0       ชำระแล้ว

[4 rows x 7 columns]

### ผลลัพธ์และคำอธิบาย

| ลำดับแถว | order_id | customer_phone | product_name | category | quantity | total_price | payment_status |
| --- | --- | --- | --- | --- | --- | --- | --- |
| 4 | ORD-105 | 0823344505 | แฟลชไดรฟ์ 64GB USB3 | สายและหน่วยความจำ | 1.0 | 250.0 | ชำระแล้ว |
| 5 | ORD-105 | 0823344505 | แฟลชไดรฟ์ 64GB USB3 | สายและหน่วยความจำ | 1.0 | 250.0 | ชำระแล้ว |
| 18 | ORD-118 | 0836655418 | เมาส์ไร้สาย NVC Pro | อุปกรณ์ต่อพ่วง | 2.0 | 580.0 | ชำระแล้ว |
| 19 | ORD-118 | 0836655418 | เมาส์ไร้สาย NVC Pro | อุปกรณ์ต่อพ่วง | 2.0 | 580.0 | ชำระแล้ว |

แสดงรายการที่ซ้ำซ้อนกันจำนวน 4 แถว (2 คู่รายการ) ได้แก่ รหัส ORD-105 (ลำดับแถว 4 และ 5) และรหัส ORD-118 (ลำดับแถว 18 และ 19) ซึ่งมีข้อมูลตรงกันทุกคอลัมน์

**ข้อควรระวังในการเขียนคำสั่ง:** หากไม่ระบุพารามิเตอร์ keep=False โปรแกรมจะแสดงเฉพาะแถวที่ซ้ำในลำดับถัดมา (ลำดับแถว 5 และ 19) โดยไม่แสดงแถวแรกให้เปรียบเทียบ

**คำถามตรวจสอบความเข้าใจ:** รหัสคำสั่งซื้อใดบ้างที่มีการบันทึกข้อมูลซ้ำซ้อนกัน

## ขั้นตอนที่ 5: การตรวจสอบความถี่ของหมวดหมู่สินค้าด้วยคำสั่ง .value_counts()

ใช้คำสั่ง .value_counts() เพื่อนับจำนวนรายการในแต่ละหมวดหมู่สินค้า ช่วยในการตรวจสอบความถูกต้องของข้อความและอักขระช่องว่างส่วนเกิน

```python
df['category'].value_counts()
```

- `df['category']`: การอ้างอิงคอลัมน์หมวดหมู่สินค้า (category)
- `.value_counts()`: คำสั่งนับจำนวนความถี่ของข้อมูลแต่ละกลุ่มโดยเรียงจากมากไปน้อย

พิมพ์คำสั่งและกดปุ่ม Shift + Enter เพื่อรันคำสั่งและตรวจสอบผลลัพธ์

In [5]:
df['category'].value_counts()

category
สายและหน่วยความจำ    14
อุปกรณ์ต่อพ่วง       13
อุปกรณ์เสียง          7
อุปกรณ์ต่อพ่วง        2
Name: count, dtype: int64

### ผลลัพธ์และคำอธิบาย

```text
category
สายและหน่วยความจำ    14
อุปกรณ์ต่อพ่วง       13
อุปกรณ์เสียง          7
อุปกรณ์ต่อพ่วง        2
```

พบว่าหมวดหมู่ 'อุปกรณ์ต่อพ่วง' ถูกแยกนับเป็น 2 กลุ่ม คือ 13 รายการ และ 2 รายการ เนื่องจากมีอักขระช่องว่างต่อท้ายข้อความ ('อุปกรณ์ต่อพ่วง ')

**ข้อควรระวังในการเขียนคำสั่ง:** โปรแกรมประมวลผลจะถือว่าข้อความ 'อุปกรณ์ต่อพ่วง' และ 'อุปกรณ์ต่อพ่วง ' ที่มีอักขระช่องว่างต่อท้ายข้อความ เป็นข้อมูลคนละหมวดหมู่กัน

**คำถามตรวจสอบความเข้าใจ:** เหตุใดหมวดหมู่ 'อุปกรณ์ต่อพ่วง' จึงถูกแยกแสดงผลออกเป็น 2 กลุ่ม (13 รายการ และ 2 รายการ)

## ขั้นตอนที่ 6: การตัดอักขระช่องว่างส่วนเกินด้วยคำสั่ง .str.strip()

ใช้คำสั่งจัดการข้อความ .str.strip() เพื่อลบอักขระช่องว่างส่วนเกินบริเวณด้านหน้าและด้านหลังของข้อความ แล้วบันทึกค่ากลับเข้าสู่คอลัมน์เดิม

```python
df['category'] = df['category'].str.strip()
df['category'].value_counts()
```

- `df['category'] =`: บันทึกข้อมูลที่ตัดช่องว่างส่วนเกินแล้วกลับเข้าสู่คอลัมน์ category
- `df['category'].str.strip()`: คำสั่งจัดการข้อความ (.str) เพื่อตัดอักขระช่องว่างส่วนเกินด้านหน้าและด้านหลัง (.strip())
- `df['category'].value_counts()`: นับจำนวนความถี่ซ้ำอีกครั้งเพื่อยืนยันว่าหมวดหมู่ถูกรวมเข้าด้วยกันเรียบร้อยแล้ว

พิมพ์คำสั่งและกดปุ่ม Shift + Enter เพื่อรันคำสั่งและตรวจสอบผลลัพธ์

In [6]:
df['category'] = df['category'].str.strip()
df['category'].value_counts()

category
อุปกรณ์ต่อพ่วง       15
สายและหน่วยความจำ    14
อุปกรณ์เสียง          7
Name: count, dtype: int64

### ผลลัพธ์และคำอธิบาย

```text
category
อุปกรณ์ต่อพ่วง       15
สายและหน่วยความจำ    14
อุปกรณ์เสียง          7
```

หมวดหมู่ 'อุปกรณ์ต่อพ่วง' ถูกรวมเป็นกลุ่มเดียวกันจำนวน 15 รายการ ส่งผลให้ตารางมีหมวดหมู่สินค้าครบ 3 หมวดหมู่ตามมาตรฐาน

**ข้อควรระวังในการเขียนคำสั่ง:** ต้องเขียนคำสั่งกำหนดค่า df['category'] = ไว้ด้านหน้าเสมอ หากไม่กำหนดค่ากลับ ผลลัพธ์จากการตัดช่องว่างจะไม่ถูกบันทึกทับลงในตาราง

**คำถามตรวจสอบความเข้าใจ:** หลังจากใช้คำสั่ง .str.strip() หมวดหมู่ 'อุปกรณ์ต่อพ่วง' มีจำนวนรายการรวมทั้งหมดกี่รายการ

## ขั้นตอนที่ 7: การลบแถวข้อมูลที่ซ้ำซ้อนและสร้างตารางใหม่ด้วยคำสั่ง .drop_duplicates()

ใช้คำสั่ง .drop_duplicates() เพื่อลบแถวข้อมูลที่ซ้ำซ้อนออกโดยคงแถวแรกไว้ และจัดเก็บผลลัพธ์ลงในตัวแปรตารางใหม่ชื่อ df_clean

```python
df_clean = df.drop_duplicates().copy()
df_clean.shape
```

- `df_clean =`: สร้างตัวแปรตารางใหม่สำหรับจัดเก็บตารางข้อมูลที่ผ่านการจัดเตรียมแล้ว
- `df.drop_duplicates().copy()`: คำสั่งลบแถวข้อมูลที่ซ้ำซ้อนและคัดลอกเป็นตารางใหม่
- `df_clean.shape`: ตรวจสอบขนาดของตารางหลังจากลบแถวข้อมูลที่ซ้ำซ้อน

พิมพ์คำสั่งและกดปุ่ม Shift + Enter เพื่อรันคำสั่งและตรวจสอบผลลัพธ์

In [7]:
df_clean = df.drop_duplicates().copy()
df_clean.shape

(34, 7)

### ผลลัพธ์และคำอธิบาย

```text
(34, 7)
```

ขนาดของตารางลดลงจาก (36, 7) เหลือ (34, 7) เนื่องจากแถวที่ซ้ำซ้อนของรหัส ORD-105 และ ORD-118 ถูกลบออกจำนวน 2 แถว

**ข้อควรระวังในการเขียนคำสั่ง:** ในการจัดเตรียมข้อมูลควรแยกเก็บผลลัพธ์ไว้ในตัวแปรใหม่ (df_clean) เพื่อรักษาตารางข้อมูลต้นฉบับ (df) ไว้ใช้เปรียบเทียบผลลัพธ์

**คำถามตรวจสอบความเข้าใจ:** เหตุใดจำนวนแถวของตาราง df_clean จึงลดลงจาก 36 แถว เหลือ 34 แถว

## ขั้นตอนที่ 8: การลบแถวที่มีค่าว่างในคอลัมน์สำคัญด้วยคำสั่ง .dropna(subset=...)

ใช้คำสั่ง .dropna() ร่วมกับพารามิเตอร์ subset เพื่อลบเฉพาะแถวที่มีค่าว่างในคอลัมน์จำนวนชิ้น (quantity) หรือยอดเงินรวม (total_price) โดยคงรายการที่ขาดเฉพาะหมายเลขโทรศัพท์ไว้

```python
df_clean = df_clean.dropna(subset=['quantity', 'total_price'])
df_clean.shape
```

- `df_clean.dropna(...)`: คำสั่งสำหรับลบแถวที่มีข้อมูลสูญหายหรือค่าว่าง (Missing Values)
- `subset=['quantity', 'total_price']`: พารามิเตอร์กำหนดให้ตรวจสอบค่าว่างเฉพาะในคอลัมน์ quantity และ total_price เท่านั้น
- `df_clean.shape`: ตรวจสอบขนาดของตารางหลังจากลบแถวที่มีค่าว่างในคอลัมน์สำคัญ

พิมพ์คำสั่งและกดปุ่ม Shift + Enter เพื่อรันคำสั่งและตรวจสอบผลลัพธ์

In [8]:
df_clean = df_clean.dropna(subset=['quantity', 'total_price'])
df_clean.shape

(31, 7)

### ผลลัพธ์และคำอธิบาย

```text
(31, 7)
```

ขนาดของตารางลดลงจาก (34, 7) เหลือ (31, 7) โดยตัดเฉพาะ 3 แถวที่ไม่สามารถคำนวณยอดขายได้ ส่วนรายการที่ขาดเฉพาะหมายเลขโทรศัพท์ยังคงอยู่ในตาราง

**ข้อควรระวังในการเขียนคำสั่ง:** หากใช้คำสั่ง df_clean.dropna() โดยไม่ระบุพารามิเตอร์ subset โปรแกรมจะลบแถวที่ขาดเฉพาะหมายเลขโทรศัพท์แต่มีข้อมูลยอดขายสมบูรณ์ออกไปด้วย

**คำถามตรวจสอบความเข้าใจ:** การระบุพารามิเตอร์ subset=['quantity', 'total_price'] มีข้อดีอย่างไรเมื่อเทียบกับการใช้ dropna() ทั้งตาราง

## ขั้นตอนที่ 9: การคัดกรองขอบเขตข้อมูลด้วยคำสั่ง .between() และการเปรียบเทียบค่าเฉลี่ย

ใช้คำสั่ง .between(1, 20) เพื่อคัดกรองรายการที่มีจำนวนชิ้นตั้งแต่ 1 ถึง 20 ชิ้น และมียอดเงินรวมไม่เกิน 10,000 บาท จากนั้นเปรียบเทียบค่าเฉลี่ยก่อนและหลังการจัดเตรียมข้อมูล

```python
df_clean = df_clean[df_clean['quantity'].between(1, 20) & (df_clean['total_price'] <= 10000)]
round(df['total_price'].mean(), 2), round(df_clean['total_price'].mean(), 2)
```

- `df_clean['quantity'].between(1, 20)`: เงื่อนไขตรวจสอบว่าค่าในคอลัมน์ quantity อยู่ในช่วง 1 ถึง 20 ชิ้นหรือไม่
- `& (df_clean['total_price'] <= 10000)`: ตัวดำเนินการเชื่อมเงื่อนไขว่ายอดเงินรวมต่อรายการต้องไม่เกิน 10,000 บาท
- `round(..., 2)`: ฟังก์ชันปัดเศษทศนิยม 2 ตำแหน่งเพื่อเปรียบเทียบค่าเฉลี่ยของตาราง df และ df_clean

พิมพ์คำสั่งและกดปุ่ม Shift + Enter เพื่อรันคำสั่งและตรวจสอบผลลัพธ์

In [9]:
df_clean = df_clean[df_clean['quantity'].between(1, 20) & (df_clean['total_price'] <= 10000)]
round(df['total_price'].mean(), 2), round(df_clean['total_price'].mean(), 2)

(3613.82, 754.83)

### ผลลัพธ์และคำอธิบาย

```text
(3613.82, 754.83)
```

ได้ตารางข้อมูลที่ผ่านการจัดเตรียมแล้วจำนวน 29 แถว โดยค่าเฉลี่ยยอดสั่งซื้อก่อนทำ ETL เท่ากับ 3,613.82 บาท (เนื่องจากมีค่าผิดปกติ 99,000 บาท) และภายหลังทำ ETL ค่าเฉลี่ยปรับเป็น 754.83 บาท ตามมูลค่าการซื้อขายจริง

**ข้อควรระวังในการเขียนคำสั่ง:** การเชื่อมหลายเงื่อนไขในไลบรารี pandas ต้องใช้เครื่องหมาย & และต้องใส่วงเล็บครอบเงื่อนไขย่อยให้ครบถ้วน

**คำถามตรวจสอบความเข้าใจ:** ค่าเฉลี่ยยอดสั่งซื้อต่อรายการก่อนและหลังการจัดเตรียมข้อมูลแตกต่างกันอย่างไร และมีสาเหตุมาจากปัจจัยใด

## ขั้นตอนที่ 10: การบันทึกตารางข้อมูลที่ผ่านการจัดเตรียมแล้วเป็นไฟล์ CSV ด้วยคำสั่ง .to_csv()

ขั้นตอนสุดท้ายของกระบวนการ ETL (Load): ใช้คำสั่ง .to_csv() เพื่อบันทึกตารางข้อมูล df_clean (จำนวน 29 แถว) ออกเป็นไฟล์ CSV ใหม่โดยไม่บันทึกหมายเลขลำดับแถว

```python
df_clean.to_csv('nvc_tech_store_clean.csv', index=False)
df_clean.head()
```

- `df_clean.to_csv('nvc_tech_store_clean.csv', ...)`: คำสั่งบันทึกตารางข้อมูลออกเป็นไฟล์ CSV ตามชื่อไฟล์ที่กำหนด
- `index=False`: พารามิเตอร์กำหนดไม่ให้บันทึกหมายเลขลำดับแถว (Index) เป็นคอลัมน์เพิ่มเติมในไฟล์ CSV
- `df_clean.head()`: แสดงข้อมูลตัวอย่าง 5 แถวแรกของตารางข้อมูลที่ผ่านการจัดเตรียมแล้ว

พิมพ์คำสั่งและกดปุ่ม Shift + Enter เพื่อรันคำสั่งและตรวจสอบผลลัพธ์

In [10]:
df_clean.to_csv('nvc_tech_store_clean.csv', index=False)
df_clean.head()

  order_id customer_phone  ... total_price payment_status
0  ORD-101     0812345601  ...       580.0       ชำระแล้ว
1  ORD-102     0891122302  ...      1290.0       ชำระแล้ว
2  ORD-103     0865544303  ...       450.0       ชำระแล้ว
3  ORD-104           <NA>  ...       380.0       ชำระแล้ว
4  ORD-105     0823344505  ...       250.0       ชำระแล้ว

[5 rows x 7 columns]

### ผลลัพธ์และคำอธิบาย

| ลำดับแถว | order_id | customer_phone | product_name | category | quantity | total_price | payment_status |
| --- | --- | --- | --- | --- | --- | --- | --- |
| 0 | ORD-101 | 0812345601 | เมาส์ไร้สาย NVC Pro | อุปกรณ์ต่อพ่วง | 2.0 | 580.0 | ชำระแล้ว |
| 1 | ORD-102 | 0891122302 | คีย์บอร์ดเชิงกล RGB | อุปกรณ์ต่อพ่วง | 1.0 | 1290.0 | ชำระแล้ว |
| 2 | ORD-103 | 0865544303 | แผ่นรองเมาส์ XL | อุปกรณ์ต่อพ่วง | 3.0 | 450.0 | ชำระแล้ว |
| 3 | ORD-104 | ว่าง | สายชาร์จ Type-C Fast | สายและหน่วยความจำ | 2.0 | 380.0 | ชำระแล้ว |
| 4 | ORD-105 | 0823344505 | แฟลชไดรฟ์ 64GB USB3 | สายและหน่วยความจำ | 1.0 | 250.0 | ชำระแล้ว |

โปรแกรมสร้างไฟล์ nvc_tech_store_clean.csv (ขนาด 29 แถว 7 คอลัมน์) เรียบร้อยแล้ว พร้อมสำหรับการนำไปใช้วิเคราะห์และนำเสนอข้อมูลในขั้นตอนต่อไป

**ข้อควรระวังในการเขียนคำสั่ง:** หากไม่ระบุพารามิเตอร์ index=False เมื่อนำไฟล์ CSV ที่บันทึกไว้กลับมาเปิดใช้งานใหม่ จะปรากฏคอลัมน์ Unnamed: 0 เพิ่มขึ้นมาด้านซ้ายสุด

**คำถามตรวจสอบความเข้าใจ:** พารามิเตอร์ index=False ในคำสั่ง .to_csv() มีหน้าที่และผลลัพธ์อย่างไร

---

# ส่วนที่ 3: แบบฝึกหัดปฏิบัติการท้ายคาบเรียนวันจันทร์ (เวลา 40 นาที · 10 คะแนน)

คำชี้แจง: ให้ผู้เรียนเขียนคำสั่งภาษา Python ลงในเซลล์ว่างด้านล่างของแต่ละข้อ และพิมพ์สรุปคำตอบที่ได้จากตารางข้อมูล `df_clean`

## ข้อที่ 1 (2 คะแนน): เปรียบเทียบขนาดของตารางข้อมูลก่อนและหลังทำ ETL

**โจทย์:** เขียนคำสั่งแสดงขนาดของตาราง `df.shape` เปรียบเทียบกับ `df_clean.shape` และระบุว่ามีแถวข้อมูลที่มีปัญหาถูกคัดกรองออกไปทั้งหมดกี่แถว

In [101]:
df.shape, df_clean.shape

((36, 7), (29, 7))

### แนวคำตอบและผลลัพธ์ (สำหรับผู้สอน)

```text
((36, 7), (29, 7))
```

**สรุปคำตอบ:** ตารางข้อมูลต้นฉบับมี 36 แถว และตารางข้อมูลที่ผ่านการจัดเตรียมแล้วเหลือ 29 แถว แสดงว่ามีแถวข้อมูลที่มีปัญหาถูกคัดกรองออกไปทั้งหมด 7 แถว

## ข้อที่ 2 (2 คะแนน): ตรวจสอบจำนวนค่าว่างคงเหลือในตาราง df_clean

**โจทย์:** เขียนคำสั่งตรวจสอบจำนวนค่าว่างคงเหลือด้วยคำสั่ง `df_clean.isna().sum()` และระบุว่าคอลัมน์ใดที่ยังคงมีค่าว่างเหลืออยู่ และเหลืออยู่กี่แถว พร้อมอธิบายเหตุผล

In [102]:
df_clean.isna().sum()

order_id          0
customer_phone    2
product_name      0
category          0
quantity          0
total_price       0
payment_status    0
dtype: int64

### แนวคำตอบและผลลัพธ์ (สำหรับผู้สอน)

```text
order_id          0
customer_phone    2
product_name      0
category          0
quantity          0
total_price       0
payment_status    0
```

**สรุปคำตอบ:** คอลัมน์ customer_phone ยังคงมีค่าว่างเหลืออยู่ 2 แถว เนื่องจากเป็นรายการที่มีมูลค่าการซื้อขายครบถ้วนแต่ไม่ได้ระบุหมายเลขโทรศัพท์

## ข้อที่ 3 (2 คะแนน): สรุปจำนวนรายการสินค้าแยกตามหมวดหมู่ภายหลังการจัดเตรียมข้อมูล

**โจทย์:** เขียนคำสั่งนับจำนวนรายการสินค้าแต่ละหมวดหมู่ด้วยคำสั่ง `df_clean['category'].value_counts()` และระบุจำนวนรายการของทั้ง 3 หมวดหมู่

In [103]:
df_clean['category'].value_counts()

category
อุปกรณ์ต่อพ่วง       12
สายและหน่วยความจำ    11
อุปกรณ์เสียง          6
Name: count, dtype: int64

### แนวคำตอบและผลลัพธ์ (สำหรับผู้สอน)

```text
category
อุปกรณ์ต่อพ่วง       12
สายและหน่วยความจำ    11
อุปกรณ์เสียง          6
```

**สรุปคำตอบ:** หมวดหมู่ อุปกรณ์ต่อพ่วง มี 12 รายการ, สายและหน่วยความจำ มี 11 รายการ และ อุปกรณ์เสียง มี 6 รายการ (รวม 29 รายการ)

## ข้อที่ 4 (2 คะแนน): ตรวจสอบค่าสถิติพื้นฐานของตาราง df_clean

**โจทย์:** เขียนคำสั่งคำนวณค่าสถิติพื้นฐานด้วยคำสั่ง `df_clean.describe()` และระบุค่าเฉลี่ย (`mean`) ค่าต่ำสุด (`min`) และค่าสูงสุด (`max`) ของคอลัมน์ `total_price`

In [104]:
df_clean.describe()

        quantity  total_price
count  29.000000    29.000000
mean    1.758621   754.827586
std     1.023131   501.017684
min     1.000000   180.000000
25%     1.000000   380.000000
50%     1.000000   650.000000
75%     2.000000   980.000000
max     5.000000  2580.000000

### แนวคำตอบและผลลัพธ์ (สำหรับผู้สอน)

| ลำดับแถว | quantity | total_price |
| --- | --- | --- |
| count | 29.0 | 29.0 |
| mean | 1.7586206896551724 | 754.8275862068965 |
| std | 1.0231314820474688 | 501.01768353205125 |
| min | 1.0 | 180.0 |
| 25% | 1.0 | 380.0 |
| 50% | 1.0 | 650.0 |
| 75% | 2.0 | 980.0 |
| max | 5.0 | 2580.0 |

**สรุปคำตอบ:** ภายหลังการทำ ETL คอลัมน์ total_price มีค่าเฉลี่ย (mean) เท่ากับ 754.83 บาท, ค่าต่ำสุด (min) เท่ากับ 180.00 บาท และค่าสูงสุด (max) เท่ากับ 2,580.00 บาท

## ข้อที่ 5 (2 คะแนน): ตรวจสอบความถูกต้องของไฟล์ CSV ที่บันทึกออก

**โจทย์:** เขียนคำสั่งอ่านไฟล์ `nvc_tech_store_clean.csv` ขึ้นมาแสดงข้อมูลตัวอย่าง 5 แถวแรกด้วยคำสั่ง `pd.read_csv('nvc_tech_store_clean.csv').head()` เพื่อยืนยันความถูกต้องของไฟล์

In [105]:
pd.read_csv('nvc_tech_store_clean.csv').head()

  order_id  customer_phone  ... total_price payment_status
0  ORD-101     812345601.0  ...       580.0       ชำระแล้ว
1  ORD-102     891122302.0  ...      1290.0       ชำระแล้ว
2  ORD-103     865544303.0  ...       450.0       ชำระแล้ว
3  ORD-104             NaN  ...       380.0       ชำระแล้ว
4  ORD-105     823344505.0  ...       250.0       ชำระแล้ว

[5 rows x 7 columns]

### แนวคำตอบและผลลัพธ์ (สำหรับผู้สอน)

| ลำดับแถว | order_id | customer_phone | product_name | category | quantity | total_price | payment_status |
| --- | --- | --- | --- | --- | --- | --- | --- |
| 0 | ORD-101 | 812345601.0 | เมาส์ไร้สาย NVC Pro | อุปกรณ์ต่อพ่วง | 2.0 | 580.0 | ชำระแล้ว |
| 1 | ORD-102 | 891122302.0 | คีย์บอร์ดเชิงกล RGB | อุปกรณ์ต่อพ่วง | 1.0 | 1290.0 | ชำระแล้ว |
| 2 | ORD-103 | 865544303.0 | แผ่นรองเมาส์ XL | อุปกรณ์ต่อพ่วง | 3.0 | 450.0 | ชำระแล้ว |
| 3 | ORD-104 | ว่าง | สายชาร์จ Type-C Fast | สายและหน่วยความจำ | 2.0 | 380.0 | ชำระแล้ว |
| 4 | ORD-105 | 823344505.0 | แฟลชไดรฟ์ 64GB USB3 | สายและหน่วยความจำ | 1.0 | 250.0 | ชำระแล้ว |

**สรุปคำตอบ:** ไฟล์ nvc_tech_store_clean.csv สามารถอ่านกลับมาใช้งานได้ถูกต้อง มี 7 คอลัมน์มาตรฐานโดยไม่มีคอลัมน์ Unnamed: 0 เพิ่มขึ้นมา

---

# คาบเรียนที่ 2 (ขั้นตอนที่ 1–12)

## ขั้นตอนที่ 1: การนำเข้าไลบรารี pandas และการสำรวจรายชื่อแผ่นงานในไฟล์ Excel

เริ่มต้นสมุดงานใหม่ด้วยการนำเข้าไลบรารี pandas ในชื่อย่อ pd จากนั้นเปิดอ่านโครงสร้างไฟล์สมุดงาน Excel (nvc_store_sales.xlsx) ด้วยฟังก์ชัน pd.ExcelFile() และตรวจสอบรายชื่อแผ่นงานย่อยทั้งหมดภายในไฟล์ด้วยแอตทริบิวต์ .sheet_names

```python
import pandas as pd
excel_book = pd.ExcelFile('nvc_store_sales.xlsx')
excel_book.sheet_names
```

- `import pandas as pd`: นำเข้าไลบรารี pandas สำหรับจัดการข้อมูลตารางและกำหนดชื่อย่อเป็น pd (ต้องรันทุกครั้งเมื่อสร้างสมุดงานใหม่)
- `excel_book = pd.ExcelFile('nvc_store_sales.xlsx')`: เปิดอ่านโครงสร้างไฟล์สมุดงาน Excel เพื่อตรวจสอบแผ่นงานภายในโดยยังไม่ดึงข้อมูลทั้งตาราง
- `excel_book.sheet_names`: แอตทริบิวต์สำหรับแสดงรายชื่อแผ่นงาน (Sheets) ทั้งหมดที่มีอยู่ในไฟล์ Excel ในรูปแบบรายการ (List)

พิมพ์คำสั่งและกดปุ่ม Shift + Enter เพื่อรันคำสั่งและตรวจสอบผลลัพธ์

In [11]:
import pandas as pd
excel_book = pd.ExcelFile('nvc_store_sales.xlsx')
excel_book.sheet_names

['Products', 'Daily_Sales', 'Branch_Orders_Dirty']

### ผลลัพธ์และคำอธิบาย

```text
['Products', 'Daily_Sales', 'Branch_Orders_Dirty']
```

ไฟล์ nvc_store_sales.xlsx บรรจุข้อมูลแยกออกเป็น 3 แผ่นงาน ได้แก่ 'Products' (ตารางสินค้าหลัก), 'Daily_Sales' (ยอดขายสาขาหลัก) และ 'Branch_Orders_Dirty' (รายการขายสาขาย่อยที่ต้องทำความสะอาดข้อมูล)

**ข้อควรระวังในการเขียนคำสั่ง:** เมื่อเริ่มต้นสร้างไฟล์ Notebook ใหม่ทุกครั้ง ต้องพิมพ์ import pandas as pd ในเซลล์แรกเสมอ มิฉะนั้นจะเกิดข้อผิดพลาด NameError: name 'pd' is not defined

**คำถามตรวจสอบความเข้าใจ:** เหตุใดผู้วิเคราะห์จึงควรสำรวจรายชื่อแผ่นงานด้วย .sheet_names ก่อนใช้คำสั่ง pd.read_excel()

## ขั้นตอนที่ 2: การนำเข้าชีต Branch_Orders_Dirty และตรวจสอบข้อมูลตัวอย่าง

อ่านเฉพาะแผ่นงาน Branch_Orders_Dirty ซึ่งเป็นข้อมูลที่ใช้ทำความสะอาดในบทเรียนนี้ แล้วตรวจขนาดตารางและข้อมูลตัวอย่าง

```python
branch_df = pd.read_excel('nvc_store_sales.xlsx', sheet_name='Branch_Orders_Dirty')
print('ขนาดตาราง:', branch_df.shape)
branch_df.head(8)
```

- `sheet_name='Branch_Orders_Dirty'`: เลือกแผ่นงานข้อมูลรายการขายสาขาย่อยเท่านั้น
- `branch_df.shape`: ตรวจจำนวนแถวและคอลัมน์ของตาราง
- `branch_df.head(8)`: แสดงข้อมูลตัวอย่าง 8 แถวแรก

พิมพ์คำสั่งและกดปุ่ม Shift + Enter เพื่อรันคำสั่งและตรวจสอบผลลัพธ์

In [12]:
branch_df = pd.read_excel('nvc_store_sales.xlsx', sheet_name='Branch_Orders_Dirty')
print('ขนาดตาราง:', branch_df.shape)
branch_df.head(8)

ขนาดตาราง: (22, 6)

  order_id   sale_date product_id  quantity discount_text payment_method
0   BR-101  2026-11-03      p001        2.0        10 บาท        โอนเงิน
1   BR-102  2026-11-03       P002      -1.0           NaN             สด
2   BR-103  2026-11-03      p003        3.0         5 บาท   QR PromptPay
3   BR-104  2026-11-03       P004       2.0         0 บาท      พร้อมเพย์
4   BR-104  2026-11-03       P004       2.0         0 บาท            โอน
5   BR-105  2026-11-03       p005       NaN         5 บาท         เงินสด
6   BR-106  2026-11-03      P006       -2.0        10 บาท            โอน
7   BR-107  2026-11-03       p001       4.0           NaN             สด

### ผลลัพธ์และคำอธิบาย

| ลำดับแถว | order_id | sale_date | product_id | quantity | discount_text | payment_method |
| --- | --- | --- | --- | --- | --- | --- |
| 0 | BR-101 | 2026-11-03 |  p001  | 2.0 | 10 บาท | โอนเงิน |
| 1 | BR-102 | 2026-11-03 | P002 | -1.0 | ว่าง | สด |
| 2 | BR-103 | 2026-11-03 | p003  | 3.0 | 5 บาท | QR PromptPay |
| 3 | BR-104 | 2026-11-03 | P004 | 2.0 | 0 บาท | พร้อมเพย์ |
| 4 | BR-104 | 2026-11-03 | P004 | 2.0 | 0 บาท | โอน |
| 5 | BR-105 | 2026-11-03 |  p005 | ว่าง | 5 บาท | เงินสด |
| 6 | BR-106 | 2026-11-03 | P006  | -2.0 | 10 บาท | โอน |
| 7 | BR-107 | 2026-11-03 | p001 | 4.0 | ว่าง | สด |

ได้ตาราง branch_df จำนวน 22 แถว 6 คอลัมน์ก่อนทำความสะอาด

**ข้อควรระวังในการเขียนคำสั่ง:** ชื่อแผ่นงานต้องตรงกับรายชื่อที่แสดงจาก .sheet_names

**คำถามตรวจสอบความเข้าใจ:** ตารางที่นำเข้ามีจำนวนแถวและคอลัมน์เท่าใด

## ขั้นตอนที่ 3: การสำรวจชนิดข้อมูล (.dtypes) จำนวนค่าว่าง (.isna().sum) และค่าสถิติพื้นฐาน (.describe)

ทบทวนขั้นตอนการสำรวจโครงสร้างตารางพื้นฐานตั้งแต่ต้น โดยตรวจสอบชนิดข้อมูลด้วย .dtypes ตรวจนับจำนวนข้อมูลสูญหายแยกตามรายคอลัมน์ด้วย .isna().sum() และคำนวณค่าสถิติเชิงพรรณนาด้วย .describe()

```python
print(branch_df.dtypes)
print('--- จำนวนค่าว่างในแต่ละคอลัมน์ ---')
print(branch_df.isna().sum())
branch_df.describe()
```

- `print(branch_df.dtypes)`: แสดงชนิดข้อมูลของทั้ง 6 คอลัมน์ในตาราง branch_df
- `branch_df.isna().sum()`: นับจำนวนแถวที่มีค่าว่าง (NaN) ในแต่ละคอลัมน์ของตาราง branch_df
- `branch_df.describe()`: คำนวณค่าสถิติพื้นฐานของคอลัมน์ตัวเลข (quantity) เพื่อตรวจหาค่าต่ำสุดที่ติดลบและค่าสูงสุดที่สูงผิดปกติ

พิมพ์คำสั่งและกดปุ่ม Shift + Enter เพื่อรันคำสั่งและตรวจสอบผลลัพธ์

In [13]:
print(branch_df.dtypes)
print('--- จำนวนค่าว่างในแต่ละคอลัมน์ ---')
print(branch_df.isna().sum())
branch_df.describe()

order_id           object
sale_date          object
product_id         object
quantity          float64
discount_text      object
payment_method     object
dtype: object
--- จำนวนค่าว่างในแต่ละคอลัมน์ ---
order_id          0
sale_date         0
product_id        0
quantity          2
discount_text     6
payment_method    0
dtype: int64

        quantity
count  20.000000
mean    3.850000
std    11.037138
min    -3.000000
25%     1.000000
50%     2.000000
75%     3.000000
max    50.000000

### ผลลัพธ์และคำอธิบาย

| ลำดับแถว | quantity |
| --- | --- |
| count | 20.0 |
| mean | 3.85 |
| std | 11.037138263727224 |
| min | -3.0 |
| 25% | 1.0 |
| 50% | 2.0 |
| 75% | 3.0 |
| max | 50.0 |

พบว่าคอลัมน์ discount_text มีชนิดเป็น object และมีค่าว่าง 6 แถว ส่วนคอลัมน์ quantity มีค่าว่าง 2 แถว และจากผลลัพธ์ .describe() พบว่า quantity มีค่าต่ำสุด (min) ติดลบที่ -3 แก้ว และค่าสูงสุด (max) สูงถึง 50 แก้ว

**ข้อควรระวังในการเขียนคำสั่ง:** คอลัมน์ discount_text ไม่ปรากฏในผลลัพธ์ของ .describe() เพราะยังมีคำว่า ' บาท' ปนอยู่ทำให้โปรแกรมมองว่าเป็นข้อความ (object)

**คำถามตรวจสอบความเข้าใจ:** จากตารางสถิติ .describe() ค่าต่ำสุด (min) และค่าสูงสุด (max) ของคอลัมน์ quantity มีค่าเท่าใด

## ขั้นตอนที่ 4: เทคนิคที่ 1: การจัดมาตรฐานรหัสสินค้าด้วย .str.strip() และ .str.upper()

ตัดอักขระช่องว่างด้านหน้าและด้านหลังรหัสสินค้า แล้วแปลงเป็นตัวพิมพ์ใหญ่เพื่อให้รหัสเดียวกันมีรูปแบบตรงกัน ก่อนตรวจจำนวนด้วย .value_counts()

```python
branch_df['product_id'] = branch_df['product_id'].str.strip().str.upper()
branch_df['product_id'].value_counts()
```

- `branch_df['product_id'].str.strip()`: ตัดอักขระช่องว่างส่วนเกินด้านหน้าและด้านหลังรหัสสินค้า เช่น ' p001 ' ให้เหลือ 'p001'
- `.str.upper()`: แปลงตัวอักษรภาษาอังกฤษทั้งหมดให้เป็นตัวพิมพ์ใหญ่มาตรฐานเดียวกัน เช่น 'p001' เป็น 'P001'
- `branch_df['product_id'].value_counts()`: ตรวจสอบผลการนับความถี่ของรหัสสินค้าภายหลังการจัดรูปแบบมาตรฐาน

พิมพ์คำสั่งและกดปุ่ม Shift + Enter เพื่อรันคำสั่งและตรวจสอบผลลัพธ์

In [14]:
branch_df['product_id'] = branch_df['product_id'].str.strip().str.upper()
branch_df['product_id'].value_counts()

product_id
P001    4
P002    4
P004    4
P006    4
P003    3
P005    3
Name: count, dtype: int64

### ผลลัพธ์และคำอธิบาย

```text
product_id
P001    4
P002    4
P004    4
P006    4
P003    3
P005    3
```

รหัสสินค้าหลังจัดรูปแบบเป็นมาตรฐาน P001 ถึง P006 ครบ 6 รหัส โดยรหัสเดียวกันไม่ถูกนับแยกเพราะช่องว่างหรือตัวพิมพ์เล็ก–ใหญ่

**ข้อควรระวังในการเขียนคำสั่ง:** สามารถเขียนคำสั่งต่อเนื่องกัน (Method Chaining) เป็น .str.strip().str.upper() ในบรรทัดเดียวได้ แต่ต้องอย่าลืมกำหนดค่ากลับเข้าสู่คอลัมน์เดิมด้วยเครื่องหมาย =

**คำถามตรวจสอบความเข้าใจ:** หากรหัส p001 และ P001 เป็นสินค้าเดียวกัน แต่ไม่จัดรูปแบบก่อนนับจำนวน จะเกิดผลอย่างไร

## ขั้นตอนที่ 5: เทคนิคที่ 2: การจัดกลุ่มคำศัพท์ที่เขียนต่างกันให้เป็นมาตรฐานเดียวด้วย .replace()

สร้างพจนานุกรม (Dictionary) จับคู่คำศัพท์ที่เขียนแตกต่างกันให้เป็นคำมาตรฐานเดียวกัน แล้วใช้ฟังก์ชัน .replace() แทนที่ค่าในคอลัมน์ payment_method พร้อมตรวจสอบจำนวนรายการแต่ละช่องทาง

```python
payment_map = {'โอน': 'พร้อมเพย์', 'โอนเงิน': 'พร้อมเพย์', 'QR PromptPay': 'พร้อมเพย์', 'สด': 'เงินสด'}
branch_df['payment_method'] = branch_df['payment_method'].str.strip().replace(payment_map)
branch_df['payment_method'].value_counts()
```

- `payment_map = {'โอน': 'พร้อมเพย์', ...}`: กำหนดพจนานุกรมระบุคำเดิมที่ต้องการเปลี่ยน (Key) และคำมาตรฐานที่ต้องการใช้แทน (Value)
- `.str.strip().replace(payment_map)`: ตัดช่องว่างส่วนเกินและแทนที่คำศัพท์ในคอลัมน์ payment_method ตามพจนานุกรมที่กำหนด
- `branch_df['payment_method'].value_counts()`: ตรวจนับจำนวนรายการแยกตามช่องทางการชำระเงินภายหลังการจัดมาตรฐานคำศัพท์

พิมพ์คำสั่งและกดปุ่ม Shift + Enter เพื่อรันคำสั่งและตรวจสอบผลลัพธ์

In [15]:
payment_map = {'โอน': 'พร้อมเพย์', 'โอนเงิน': 'พร้อมเพย์', 'QR PromptPay': 'พร้อมเพย์', 'สด': 'เงินสด'}
branch_df['payment_method'] = branch_df['payment_method'].str.strip().replace(payment_map)
branch_df['payment_method'].value_counts()

payment_method
พร้อมเพย์    14
เงินสด        8
Name: count, dtype: int64

### ผลลัพธ์และคำอธิบาย

```text
payment_method
พร้อมเพย์    14
เงินสด        8
```

ช่องทางการชำระเงินที่เคยแยกเป็น 6 รูปแบบ ถูกรวมกลุ่มเป็นมาตรฐานเดียวกันเหลือเพียง 2 ช่องทางหลัก ได้แก่ 'พร้อมเพย์' (14 รายการ) และ 'เงินสด' (8 รายการ)

**ข้อควรระวังในการเขียนคำสั่ง:** การสะกดคำต้นทางในพจนานุกรม (Key) ต้องตรงกับข้อความในตารางทุกตัวอักษร จึงควรใช้ .str.strip() ตัดช่องว่างก่อนเรียกใช้ .replace()

**คำถามตรวจสอบความเข้าใจ:** เทคนิคการใช้ .replace() ด้วยพจนานุกรมมีข้อดีกว่าการเขียนคำสั่งแก้ไขทีละคำอย่างไร

## ขั้นตอนที่ 6: เทคนิคที่ 3: การจัดการค่าว่างด้วยการเติมค่ามาตรฐาน (.fillna) แทนการลบแถว

เติมส่วนลดที่ว่างด้วยข้อความ 0 บาท และจำนวนที่ว่างด้วยค่าทดแทน 1 แก้วตามสมมติฐานที่กำหนดเฉพาะชุดฝึกนี้ เพื่อฝึกใช้ .fillna() และคงจำนวนแถวไว้ ต้องแยกค่าทดแทนออกจากค่าที่ตรวจสอบยืนยันแล้วในการใช้งานจริง

```python
branch_df['discount_text'] = branch_df['discount_text'].fillna('0 บาท')
branch_df['quantity'] = branch_df['quantity'].fillna(1)
branch_df.isna().sum()
```

- `branch_df['discount_text'].fillna('0 บาท')`: เติมข้อความ '0 บาท' ลงในแถวที่มีค่าว่างของคอลัมน์ส่วนลด แทนการลบแถวข้อมูลทิ้ง
- `branch_df['quantity'].fillna(1)`: เติมค่าเริ่มต้นเท่ากับ 1 แก้ว ลงในแถวที่ไม่ได้ระบุจำนวนชิ้น
- `branch_df.isna().sum()`: ตรวจสอบยืนยันว่าไม่มีค่าว่าง (NaN) หลงเหลืออยู่ในตารางข้อมูล

พิมพ์คำสั่งและกดปุ่ม Shift + Enter เพื่อรันคำสั่งและตรวจสอบผลลัพธ์

**เงื่อนไขก่อนใช้คำสั่ง:** กติกาสมมติสำหรับชุดฝึกนี้เท่านั้น: กำหนดให้ค่าว่างส่วนลดหมายถึง 0 บาท และจำนวนที่ไม่ระบุใช้ค่าทดแทน 1 แก้วเพื่อฝึก .fillna() ค่าทดแทนไม่ใช่ยอดขายที่ยืนยันแล้ว ข้อมูลจริงต้องตรวจหลักฐานและบันทึกการเติมค่า

In [16]:
branch_df['discount_text'] = branch_df['discount_text'].fillna('0 บาท')
branch_df['quantity'] = branch_df['quantity'].fillna(1)
branch_df.isna().sum()

order_id          0
sale_date         0
product_id        0
quantity          0
discount_text     0
payment_method    0
dtype: int64

### ผลลัพธ์และคำอธิบาย

```text
order_id          0
sale_date         0
product_id        0
quantity          0
discount_text     0
payment_method    0
```

จำนวนค่าว่างในทุกคอลัมน์กลายเป็น 0 รายการ โดยที่ตารางยังคงมีข้อมูลครบทั้ง 22 แถว ไม่สูญเสียรายการขายไปจากการลบแถว

**ข้อควรระวังในการเขียนคำสั่ง:** ค่าว่างไม่ได้หมายถึงศูนย์หรือหนึ่งเสมอไป ต้องตรวจสอบความหมายกับแหล่งข้อมูลก่อนเติมค่า และบันทึกว่ารายการใดได้รับการเติมค่า

**คำถามตรวจสอบความเข้าใจ:** เมื่อใดที่เราควรใช้ .fillna() แทนการใช้ .dropna() ในการจัดเตรียมข้อมูล

## ขั้นตอนที่ 7: เทคนิคที่ 4: การตัดหน่วยข้อความออกจากตัวเลขและแปลงชนิดข้อมูล (.str.replace & .astype)

สกัดเฉพาะตัวเลขออกจากคอลัมน์ discount_text โดยใช้ .str.replace() ลบคำว่า ' บาท' ออก แล้วแปลงชนิดข้อมูลจากข้อความให้เป็นตัวเลขทศนิยม (float) ด้วย .astype(float) เก็บในคอลัมน์ใหม่ชื่อ discount

```python
branch_df['discount'] = branch_df['discount_text'].str.replace(' บาท', '', regex=False).astype(float)
branch_df[['order_id', 'discount_text', 'discount']].head(6)
```

- `.str.replace(' บาท', '', regex=False)`: ค้นหาคำว่า ' บาท' ในข้อความแล้วแทนที่ด้วยค่าว่าง (ตัดคำว่า ' บาท' ออก)
- `.astype(float)`: แปลงชนิดข้อมูลจากข้อความตัวเลข (เช่น '10') ให้เป็นข้อมูลตัวเลขทศนิยม (10.0) ที่คำนวณได้
- `branch_df[['order_id', 'discount_text', 'discount']].head(6)`: แสดงเปรียบเทียบคอลัมน์ข้อความเดิมกับคอลัมน์ตัวเลขใหม่ 6 แถวแรก

พิมพ์คำสั่งและกดปุ่ม Shift + Enter เพื่อรันคำสั่งและตรวจสอบผลลัพธ์

In [17]:
branch_df['discount'] = branch_df['discount_text'].str.replace(' บาท', '', regex=False).astype(float)
branch_df[['order_id', 'discount_text', 'discount']].head(6)

  order_id discount_text  discount
0   BR-101        10 บาท      10.0
1   BR-102         0 บาท       0.0
2   BR-103         5 บาท       5.0
3   BR-104         0 บาท       0.0
4   BR-104         0 บาท       0.0
5   BR-105         5 บาท       5.0

### ผลลัพธ์และคำอธิบาย

| ลำดับแถว | order_id | discount_text | discount |
| --- | --- | --- | --- |
| 0 | BR-101 | 10 บาท | 10.0 |
| 1 | BR-102 | 0 บาท | 0.0 |
| 2 | BR-103 | 5 บาท | 5.0 |
| 3 | BR-104 | 0 บาท | 0.0 |
| 4 | BR-104 | 0 บาท | 0.0 |
| 5 | BR-105 | 5 บาท | 5.0 |

ได้คอลัมน์ใหม่ discount ที่มีชนิดข้อมูลเป็น float64 (เช่น 10.0, 0.0, 5.0) พร้อมสำหรับนำไปหักลบออกจากยอดขายรวมได้อย่างถูกต้อง

**ข้อควรระวังในการเขียนคำสั่ง:** ต้องตัดอักขระที่ไม่ใช่ตัวเลข (เช่น ' บาท' หรือเครื่องหมายจุลภาค ',') ออกให้หมดก่อนเรียกใช้ .astype(float) มิฉะนั้นจะเกิดข้อผิดพลาด ValueError

**คำถามตรวจสอบความเข้าใจ:** เหตุใดเราจึงต้องแปลงคอลัมน์ส่วนลดให้เป็นชนิด float ก่อนนำไปคำนวณยอดขายสุทธิ

## ขั้นตอนที่ 8: เทคนิคที่ 5: การแก้ไขค่าติดลบด้วยค่าสัมบูรณ์ (.abs) และการจำกัดเพดานค่า (.clip)

สาธิต .abs() เพื่อแปลงค่าติดลบเป็นค่าบวก และ .clip(upper=10) เพื่อจำกัดจำนวนไม่เกิน 10 แก้วตามกติกาสมมติของแบบฝึก จากนั้นแปลงเป็นจำนวนเต็มด้วย .astype(int) การจำกัดเพดานไม่ใช่การกู้คืนค่าจริงจากต้นทาง

```python
branch_df['quantity'] = branch_df['quantity'].abs().clip(upper=10).astype(int)
branch_df['quantity'].describe()
```

- `.abs()`: ฟังก์ชันค่าสัมบูรณ์ (Absolute Value) เปลี่ยนตัวเลขติดลบ (เช่น -2, -3) ให้เป็นตัวเลขบวก (2, 3)
- `.clip(upper=10)`: ฟังก์ชันจำกัดขอบเขตข้อมูล โดยปรับค่าที่สูงเกินเพดาน 10 ให้ลงมาอยู่ที่ค่าสูงสุดที่ยอมรับได้คือ 10
- `.astype(int)`: แปลงชนิดข้อมูลจำนวนชิ้นจากทศนิยม (float64) ให้เป็นจำนวนเต็ม (int64)
- `branch_df['quantity'].describe()`: ตรวจสอบค่าสถิติพื้นฐานของคอลัมน์จำนวนชิ้นภายหลังการปรับแก้

พิมพ์คำสั่งและกดปุ่ม Shift + Enter เพื่อรันคำสั่งและตรวจสอบผลลัพธ์

**เงื่อนไขก่อนใช้คำสั่ง:** กติกาสมมติสำหรับฝึกคำสั่ง: ถือว่าค่าติดลบเกิดจากเครื่องหมายผิด และจำกัดจำนวนสูงสุดไว้ที่ 10 แก้วเพื่อสาธิต .clip() การเปลี่ยน 50 เป็น 10 เป็นการจำกัดเพดาน ไม่ใช่การยืนยันยอดขายจริง หากยังตรวจต้นทางไม่ได้ ให้แยกรายการไว้ตรวจสอบ

In [18]:
branch_df['quantity'] = branch_df['quantity'].abs().clip(upper=10).astype(int)
branch_df['quantity'].describe()

count    22.000000
mean      2.500000
std       1.896111
min       1.000000
25%       2.000000
50%       2.000000
75%       3.000000
max      10.000000
Name: quantity, dtype: float64

### ผลลัพธ์และคำอธิบาย

```text
count    22.000000
mean      2.500000
std       1.896111
min       1.000000
25%       2.000000
50%       2.000000
75%       3.000000
max      10.000000
```

คอลัมน์ quantity มีค่าต่ำสุด (min) เท่ากับ 1 แก้ว และค่าสูงสุด (max) เท่ากับ 10 แก้ว ค่าเฉลี่ยอยู่ที่ประมาณ 2.55 แก้วต่อรายการ โดยไม่มีค่าติดลบหรือค่าที่สูงเกินเกณฑ์หลงเหลืออยู่

**ข้อควรระวังในการเขียนคำสั่ง:** ห้ามเปลี่ยนค่าติดลบหรือค่าที่สูงผิดสังเกตโดยอัตโนมัติในข้อมูลจริง เพราะอาจเป็นรายการคืนสินค้าหรือยอดขายจริง ต้องตรวจสอบหลักฐานและบันทึกเหตุผลก่อนแก้ไข

**คำถามตรวจสอบความเข้าใจ:** หากจำนวน 50 แก้วยังไม่มีหลักฐานยืนยันว่าเป็นข้อมูลผิด ควรเปลี่ยนเป็น 10 ทันทีหรือไม่ เพราะเหตุใด และ .clip() ต่างจากการลบแถวอย่างไร

## ขั้นตอนที่ 9: เทคนิคที่ 6: การลบข้อมูลซ้ำโดยระบุคอลัมน์คีย์หลัก (.drop_duplicates(subset=...))

ลบแถวที่มีรหัสคำสั่งซื้อ (order_id) ซ้ำซ้อนกัน โดยระบุพารามิเตอร์ subset=['order_id'] เพื่อตรวจสอบการซ้ำเฉพาะคอลัมน์คีย์หลัก และเก็บแถวแรกไว้ด้วย keep='first' ลงในตารางใหม่ชื่อ branch_clean

```python
branch_clean = branch_df.drop_duplicates(subset=['order_id'], keep='first').copy()
print('ขนาดตารางก่อนลบซ้ำ:', branch_df.shape)
print('ขนาดตารางหลังลบซ้ำ:', branch_clean.shape)
```

- `branch_df.drop_duplicates(...)`: ฟังก์ชันสำหรับลบแถวข้อมูลที่มีการบันทึกซ้ำซ้อน
- `subset=['order_id']`: ระบุให้ตรวจสอบความซ้ำซ้อนเฉพาะคอลัมน์รหัสคำสั่งซื้อ (order_id) แม้คอลัมน์อื่นอาจบันทึกต่างกันเล็กน้อย
- `keep='first'`: เก็บรักษาแถวแรกของรหัสคำสั่งซื้อนั้นไว้ และลบแถวที่ซ้ำตามมาออก
- `.copy()`: สร้างสำเนาตารางแยกออกมาเป็นตัวแปร branch_clean อย่างอิสระ

พิมพ์คำสั่งและกดปุ่ม Shift + Enter เพื่อรันคำสั่งและตรวจสอบผลลัพธ์

**เงื่อนไขก่อนใช้คำสั่ง:** กำหนดให้ 1 order_id แทน 1 รายการขายในชุดฝึกนี้ จึงเก็บแถวแรกเมื่อพบรหัสซ้ำ ข้อมูลจริงที่หนึ่งคำสั่งซื้อมีหลายสินค้า หรือแถวซ้ำมีค่าขัดแย้งกัน ต้องตรวจสอบก่อนลบ

In [19]:
branch_clean = branch_df.drop_duplicates(subset=['order_id'], keep='first').copy()
print('ขนาดตารางก่อนลบซ้ำ:', branch_df.shape)
print('ขนาดตารางหลังลบซ้ำ:', branch_clean.shape)

ขนาดตารางก่อนลบซ้ำ: (22, 7)
ขนาดตารางหลังลบซ้ำ: (20, 7)

### ผลลัพธ์และคำอธิบาย

```text
ขนาดตารางก่อนลบซ้ำ: (22, 7)
ขนาดตารางหลังลบซ้ำ: (20, 7)
```

ขนาดตารางลดลงจาก (22, 7) เหลือ (20, 7) เนื่องจากรหัสคำสั่งซื้อที่ซ้ำกัน 2 คู่ (BR-104 และ BR-112) ถูกลบแถวที่ซ้ำออกเหลือรหัสละ 1 แถว

**ข้อควรระวังในการเขียนคำสั่ง:** หากไม่ระบุ subset=['order_id'] คำสั่ง .drop_duplicates() จะลบเฉพาะแถวที่ซ้ำกันทุกคอลัมน์เท่านั้น ซึ่งอาจไม่ลบรหัสคำสั่งซื้อเดียวกันที่พนักงานบันทึกช่องทางชำระเงินต่างกัน

**คำถามตรวจสอบความเข้าใจ:** ตารางควรลดจาก 22 เหลือ 20 แถว หากหนึ่งคำสั่งซื้อมีหลายรายการสินค้า ยังใช้ order_id เพียงคอลัมน์เดียวเพื่อลบซ้ำได้หรือไม่

## ขั้นตอนที่ 10: เทคนิคที่ 7: การแปลงชนิดข้อมูลวันที่ด้วย pd.to_datetime()

แปลง sale_date จากข้อความให้เป็นชนิดข้อมูลวันที่ เพื่อให้รูปแบบข้อมูลสม่ำเสมอก่อนส่งออก

```python
branch_clean['sale_date'] = pd.to_datetime(branch_clean['sale_date'])
print(branch_clean['sale_date'].dtype)
branch_clean[['order_id', 'sale_date']].head(6)
```

- `pd.to_datetime(branch_clean['sale_date'])`: แปลงค่าคอลัมน์วันที่เป็นชนิดข้อมูล datetime
- `branch_clean['sale_date'].dtype`: ตรวจสอบชนิดข้อมูลวันที่หลังแปลง

พิมพ์คำสั่งและกดปุ่ม Shift + Enter เพื่อรันคำสั่งและตรวจสอบผลลัพธ์

In [20]:
branch_clean['sale_date'] = pd.to_datetime(branch_clean['sale_date'])
print(branch_clean['sale_date'].dtype)
branch_clean[['order_id', 'sale_date']].head(6)

datetime64[ns]

  order_id  sale_date
0   BR-101 2026-11-03
1   BR-102 2026-11-03
2   BR-103 2026-11-03
3   BR-104 2026-11-03
5   BR-105 2026-11-03
6   BR-106 2026-11-03

### ผลลัพธ์และคำอธิบาย

| ลำดับแถว | order_id | sale_date |
| --- | --- | --- |
| 0 | BR-101 | 2026-11-03 00:00:00 |
| 1 | BR-102 | 2026-11-03 00:00:00 |
| 2 | BR-103 | 2026-11-03 00:00:00 |
| 3 | BR-104 | 2026-11-03 00:00:00 |
| 5 | BR-105 | 2026-11-03 00:00:00 |
| 6 | BR-106 | 2026-11-03 00:00:00 |

คอลัมน์ sale_date เป็นชนิดข้อมูล datetime และมีข้อมูลรายการขาย 20 แถวเท่าเดิม

**ข้อควรระวังในการเขียนคำสั่ง:** หากแปลงวันที่ไม่สำเร็จ ต้องตรวจรูปแบบและค่าจากต้นทางก่อนแก้ไข

**คำถามตรวจสอบความเข้าใจ:** หลังแปลงวันที่ จำนวนแถวควรเปลี่ยนหรือไม่ และตรวจชนิดข้อมูลด้วยคำสั่งใด

## ขั้นตอนที่ 11: การตรวจสอบคุณภาพข้อมูลหลังทำความสะอาด

ตรวจจำนวนแถว ค่าว่าง รหัสคำสั่งซื้อซ้ำ และช่วงค่าจำนวนสินค้า เพื่อยืนยันผลตามเงื่อนไขของชุดฝึกก่อนส่งออก

```python
print('ขนาดตาราง:', branch_clean.shape)
print('ค่าว่างในแต่ละคอลัมน์:')
print(branch_clean.isna().sum())
print('รหัสคำสั่งซื้อซ้ำ:', branch_clean.duplicated(subset=['order_id']).sum())
branch_clean['quantity'].describe()
```

- `branch_clean.shape`: ตรวจว่าตารางเหลือ 20 แถว 7 คอลัมน์
- `branch_clean.isna().sum()`: นับค่าว่างแยกแต่ละคอลัมน์
- `branch_clean.duplicated(subset=['order_id']).sum()`: นับรายการรหัสคำสั่งซื้อที่ซ้ำ
- `branch_clean['quantity'].describe()`: ตรวจช่วงค่าจำนวนสินค้าหลังทำความสะอาด

พิมพ์คำสั่งและกดปุ่ม Shift + Enter เพื่อรันคำสั่งและตรวจสอบผลลัพธ์

In [21]:
print('ขนาดตาราง:', branch_clean.shape)
print('ค่าว่างในแต่ละคอลัมน์:')
print(branch_clean.isna().sum())
print('รหัสคำสั่งซื้อซ้ำ:', branch_clean.duplicated(subset=['order_id']).sum())
branch_clean['quantity'].describe()

ขนาดตาราง: (20, 7)
ค่าว่างในแต่ละคอลัมน์:
order_id          0
sale_date         0
product_id        0
quantity          0
discount_text     0
payment_method    0
discount          0
dtype: int64
รหัสคำสั่งซื้อซ้ำ: 0

count    20.000000
mean      2.550000
std       1.986136
min       1.000000
25%       1.750000
50%       2.000000
75%       3.000000
max      10.000000
Name: quantity, dtype: float64

### ผลลัพธ์และคำอธิบาย

```text
count    20.000000
mean      2.550000
std       1.986136
min       1.000000
25%       1.750000
50%       2.000000
75%       3.000000
max      10.000000
```

ตารางมี 20 แถว 7 คอลัมน์ ไม่มีค่าว่างหรือรหัสคำสั่งซื้อซ้ำ และ quantity อยู่ในช่วง 1–10 ตามกติกาสมมติของชุดฝึก

**ข้อควรระวังในการเขียนคำสั่ง:** จำนวนแถวตรงเพียงอย่างเดียวไม่ได้ยืนยันคุณภาพ ต้องตรวจค่าว่าง ข้อมูลซ้ำ ชนิดข้อมูล และช่วงค่าควบคู่กัน

**คำถามตรวจสอบความเข้าใจ:** ก่อนส่งออกไฟล์ ควรตรวจสอบอะไรบ้างนอกเหนือจากจำนวนแถว

## ขั้นตอนที่ 12: การส่งออกตารางข้อมูลที่ผ่านการทำความสะอาดเป็นไฟล์ CSV

บันทึก branch_clean เป็นไฟล์ nvc_branch_orders_clean.csv โดยไม่เพิ่มลำดับแถว แล้วอ่านกลับเพื่อตรวจว่าข้อมูลส่งออกครบถ้วน

```python
output_file = 'nvc_branch_orders_clean.csv'
branch_clean.to_csv(output_file, index=False, encoding='utf-8-sig')
exported_df = pd.read_csv(output_file)
print('ขนาดตารางที่อ่านกลับ:', exported_df.shape)
exported_df.head()
```

- `branch_clean.to_csv('nvc_branch_orders_clean.csv', ...)`: ส่งออกตารางที่ผ่านการทำความสะอาดเป็นไฟล์ CSV
- `index=False`: ไม่บันทึกลำดับแถวเป็นคอลัมน์เพิ่มเติม
- `encoding='utf-8-sig'`: ใช้การเข้ารหัสที่ช่วยให้ Excel อ่านภาษาไทยได้
- `pd.read_csv(...)`: อ่านไฟล์ที่ส่งออกกลับมาตรวจสอบ

พิมพ์คำสั่งและกดปุ่ม Shift + Enter เพื่อรันคำสั่งและตรวจสอบผลลัพธ์

In [22]:
output_file = 'nvc_branch_orders_clean.csv'
branch_clean.to_csv(output_file, index=False, encoding='utf-8-sig')
exported_df = pd.read_csv(output_file)
print('ขนาดตารางที่อ่านกลับ:', exported_df.shape)
exported_df.head()

ขนาดตารางที่อ่านกลับ: (20, 7)

  order_id   sale_date product_id  ...  discount_text payment_method discount
0   BR-101  2026-11-03       P001  ...         10 บาท      พร้อมเพย์     10.0
1   BR-102  2026-11-03       P002  ...          0 บาท         เงินสด      0.0
2   BR-103  2026-11-03       P003  ...          5 บาท      พร้อมเพย์      5.0
3   BR-104  2026-11-03       P004  ...          0 บาท      พร้อมเพย์      0.0
4   BR-105  2026-11-03       P005  ...          5 บาท         เงินสด      5.0

[5 rows x 7 columns]

### ผลลัพธ์และคำอธิบาย

| ลำดับแถว | order_id | sale_date | product_id | quantity | discount_text | payment_method | discount |
| --- | --- | --- | --- | --- | --- | --- | --- |
| 0 | BR-101 | 2026-11-03 | P001 | 2 | 10 บาท | พร้อมเพย์ | 10.0 |
| 1 | BR-102 | 2026-11-03 | P002 | 1 | 0 บาท | เงินสด | 0.0 |
| 2 | BR-103 | 2026-11-03 | P003 | 3 | 5 บาท | พร้อมเพย์ | 5.0 |
| 3 | BR-104 | 2026-11-03 | P004 | 2 | 0 บาท | พร้อมเพย์ | 0.0 |
| 4 | BR-105 | 2026-11-03 | P005 | 1 | 5 บาท | เงินสด | 5.0 |

ได้ไฟล์ nvc_branch_orders_clean.csv จำนวน 20 แถว 7 คอลัมน์ ไม่มีคอลัมน์ลำดับแถวเพิ่มเติม

**ข้อควรระวังในการเขียนคำสั่ง:** ไฟล์ CSV ไม่เก็บชนิดข้อมูลวันที่ไว้ เมื่ออ่านกลับอาจต้องใช้ pd.to_datetime() อีกครั้ง และควรตรวจชื่อไฟล์ก่อนดาวน์โหลด

**คำถามตรวจสอบความเข้าใจ:** เหตุใดต้องกำหนด index=False และตรวจอย่างไรว่าไฟล์ที่ส่งออกมีจำนวนแถวครบ

## สรุป

อธิบายคำสั่ง ผลลัพธ์ หน่วย และข้อจำกัด บันทึก Notebook สำหรับทบทวน