# W02 — Get Data การรวบรวมและนำเข้าข้อมูล

## จุดประสงค์การเรียนรู้
- คัดกรองและจัดเตรียมข้อมูล (ETL) บนชุดข้อมูล nvc_tech_store.csv ต่อเนื่องจากสัปดาห์ที่ 1 ได้อย่างเป็นระบบ
- ใช้คำสั่งตรวจสอบข้อมูลซ้ำซ้อน (duplicated) ตัดอักขระช่องว่างส่วนเกิน (str.strip) จัดการค่าว่าง (dropna) คัดกรองขอบเขตข้อมูล (between) และบันทึกไฟล์ข้อมูลใหม่ (to_csv) ได้
- นำเข้าข้อมูลจากไฟล์ Excel ที่มีหลายชีต (pd.read_excel) และจัดทำตารางพจนานุกรมข้อมูล (Data Dictionary) ได้อย่างถูกต้อง

## การเตรียมไฟล์ข้อมูล
- nvc_tech_store.csv
- students.csv
- nvc_store_sales.xlsx

อัปโหลดไฟล์ข้อมูลผ่านเมนู Files ในโปรแกรม Google Colab แล้วพิมพ์คำสั่งและรันผลลัพธ์ตามลำดับทีละขั้นตอน

## โครงสร้างชุดข้อมูล
- ไฟล์ nvc_tech_store.csv: จำนวน 36 แถว 7 คอลัมน์ ได้แก่ order_id, customer_phone, product_name, category, quantity, total_price, payment_status
- ไฟล์ students.csv: จำนวน 30 แถว 5 คอลัมน์ ได้แก่ id, name, gender, major, score
- ไฟล์ nvc_store_sales.xlsx (ชีต Products): จำนวน 6 แถว 5 คอลัมน์ ได้แก่ product_id, product_name, category, cost_price, selling_price
- ไฟล์ nvc_store_sales.xlsx (ชีต Daily_Sales): จำนวน 15 แถว 5 คอลัมน์ ได้แก่ order_id, product_id, quantity, payment_method, sale_date

---

# ส่วนที่ 1: แบบฝึกหัดทบทวนก่อนเรียน (ทบทวนคำสั่งพื้นฐานจากสัปดาห์ที่ 1 · เวลา 30 นาที)

คำชี้แจง: ให้ผู้เรียนเขียนคำสั่งทบทวนการนำเข้าและสำรวจข้อมูล `nvc_tech_store.csv` ลงในเซลล์โค้ดทั้ง 3 ข้อด้านล่างก่อนเริ่มเรียนเนื้อหาใหม่

## ข้อที่ 1: ทบทวนการนำเข้าข้อมูลและกำหนดชนิดข้อมูลหมายเลขโทรศัพท์

**โจทย์:** เขียนคำสั่งนำเข้าไลบรารี `pandas` และอ่านไฟล์ `nvc_tech_store.csv` ลงในตัวแปร `df` โดยกำหนดชนิดข้อมูลของคอลัมน์ `customer_phone` เป็น `string` จากนั้นแสดงข้อมูลตัวอย่าง 3 แถวแรก

In [1]:
import pandas as pd
df = pd.read_csv('nvc_tech_store.csv', dtype={'customer_phone': 'string'})
df.head(3)

  order_id customer_phone  ... total_price payment_status
0  ORD-101     0812345601  ...       580.0       ชำระแล้ว
1  ORD-102     0891122302  ...      1290.0       ชำระแล้ว
2  ORD-103     0865544303  ...       450.0       ชำระแล้ว

[3 rows x 7 columns]

### แนวคำตอบทบทวน

| ลำดับแถว | order_id | customer_phone | product_name | category | quantity | total_price | payment_status |
| --- | --- | --- | --- | --- | --- | --- | --- |
| 0 | ORD-101 | 0812345601 | เมาส์ไร้สาย NVC Pro | อุปกรณ์ต่อพ่วง | 2.0 | 580.0 | ชำระแล้ว |
| 1 | ORD-102 | 0891122302 | คีย์บอร์ดเชิงกล RGB | อุปกรณ์ต่อพ่วง | 1.0 | 1290.0 | ชำระแล้ว |
| 2 | ORD-103 | 0865544303 | แผ่นรองเมาส์ XL | อุปกรณ์ต่อพ่วง  | 3.0 | 450.0 | ชำระแล้ว |

**สรุปผล:** นำเข้าตารางข้อมูลขนาด 36 แถว 7 คอลัมน์ โดยหมายเลขโทรศัพท์ยังคงแสดงเลข 08 นำหน้าครบถ้วน

## ข้อที่ 2: ทบทวนการสำรวจขนาดตารางและรายชื่อคอลัมน์

**โจทย์:** เขียนคำสั่งตรวจสอบขนาดของตารางด้วยคำสั่ง `df.shape` และแสดงรายชื่อคอลัมน์ทั้งหมดด้วยคำสั่ง `df.columns`

In [2]:
df.shape, df.columns.tolist()

((36, 7), ['order_id', 'customer_phone', 'product_name', 'category', 'quantity', 'total_price', 'payment_status'])

### แนวคำตอบทบทวน

```text
((36, 7), ['order_id', 'customer_phone', 'product_name', 'category', 'quantity', 'total_price', 'payment_status'])
```

**สรุปผล:** ตารางข้อมูลต้นฉบับมีขนาด (36, 7) คือ 36 แถว 7 คอลัมน์

## ข้อที่ 3: ทบทวนการตรวจสอบจำนวนค่าว่างและค่าสถิติพื้นฐาน

**โจทย์:** เขียนคำสั่งนับจำนวนค่าว่างแยกตามรายคอลัมน์ด้วยคำสั่ง `df.isna().sum()` และคำนวณค่าสถิติพื้นฐานด้วยคำสั่ง `df.describe()`

In [3]:
df.isna().sum()
df.describe()

        quantity   total_price
count  35.000000     34.000000
mean    1.628571   3613.823529
std     1.165325  16860.921829
min    -2.000000    180.000000
25%     1.000000    395.000000
50%     1.000000    620.000000
75%     2.000000    957.500000
max     5.000000  99000.000000

### แนวคำตอบทบทวน

| ลำดับแถว | quantity | total_price |
| --- | --- | --- |
| count | 35.0 | 34.0 |
| mean | 1.6285714285714286 | 3613.823529411765 |
| std | 1.1653253594071105 | 16860.921829414056 |
| min | -2.0 | 180.0 |
| 25% | 1.0 | 395.0 |
| 50% | 1.0 | 620.0 |
| 75% | 2.0 | 957.5 |
| max | 5.0 | 99000.0 |

**สรุปผล:** พบค่าว่างรวม 5 จุด และพบค่าผิดปกติในคอลัมน์ quantity (-2 ชิ้น) และ total_price (99,000 บาท)

---

# ส่วนที่ 2: ทฤษฎีและหลักการจัดเตรียมข้อมูล (ETL)

## ความหมายและองค์ประกอบของกระบวนการ ETL (Extract – Transform – Load)
- Extract (การดึงและนำเข้าข้อมูล): ขั้นตอนการรวบรวมและอ่านข้อมูลจากแหล่งข้อมูลต้นทาง เช่น ไฟล์ CSV หรือไฟล์ Excel เข้าสู่โปรแกรมประมวลผล พร้อมกำหนดชนิดข้อมูลเบื้องต้นให้ถูกต้องตามลักษณะการใช้งาน
- Transform (การปรับรูปแบบและทำความสะอาดข้อมูล): ขั้นตอนการตรวจสอบ คัดกรอง และแก้ไขความผิดพลาดของข้อมูล เช่น การตัดอักขระช่องว่างส่วนเกิน การลบข้อมูลที่บันทึกซ้ำซ้อน การจัดการค่าว่าง และการคัดกรองค่าที่อยู่นอกเกณฑ์ที่กำหนด
- Load (การจัดเก็บและส่งออกข้อมูล): ขั้นตอนการบันทึกตารางข้อมูลที่ผ่านการจัดเตรียมแล้วออกเป็นไฟล์ข้อมูลชุดใหม่ที่มีความถูกต้องสมบูรณ์ เพื่อนำไปใช้วิเคราะห์คำนวณหรือสร้างแผนภูมินำเสนอในลำดับถัดไป

## ความสำคัญของการจัดเตรียมข้อมูลต่อความถูกต้องของผลการวิเคราะห์
- หลักการคุณภาพของข้อมูล (Garbage In, Garbage Out): หากนำตารางข้อมูลต้นฉบับที่มีข้อผิดพลาดมาคำนวณทันที ผลลัพธ์ที่ได้ย่อมคลาดเคลื่อนจากความเป็นจริง แม้ว่าจะเขียนคำสั่งคำนวณได้ถูกต้องตามหลักไวยากรณ์ก็ตาม
- ผลกระทบต่อการคำนวณยอดรวมและค่าเฉลี่ย: การบันทึกข้อมูลซ้ำซ้อนทำให้นับจำนวนคำสั่งซื้อและยอดขายรวมเกินจริง ส่วนค่าผิดปกติเพียงรายการเดียว (เช่น 99,000 บาท) ส่งผลให้ค่าเฉลี่ยคลาดเคลื่อนจาก 754.83 บาท ไปเป็น 3,613.82 บาท
- ผลกระทบต่อการจัดกลุ่มและสรุปรายงาน: อักขระช่องว่างส่วนเกินต่อท้ายข้อความทำให้โปรแกรมแยกนับหมวดหมู่สินค้าเดียวกันออกเป็นคนละกลุ่ม ส่งผลให้ตารางสรุปจำนวนสินค้าแยกตามหมวดหมู่ขาดความถูกต้อง

## ปัญหาคุณภาพข้อมูล 4 รูปแบบหลักที่ต้องตรวจสอบในขั้นตอน Transform
- ข้อมูลสูญหายหรือค่าว่าง (Missing Values): ข้อมูลที่ไม่ได้ถูกบันทึกในบางคอลัมน์ (แสดงเป็น NaN หรือ <NA>) ผู้วิเคราะห์ต้องพิจารณาแยกแยะระหว่างคอลัมน์สำคัญที่ใช้คำนวณยอดขาย กับคอลัมน์ข้อมูลทั่วไปที่สามารถคงแถวข้อมูลไว้ได้
- การบันทึกข้อมูลซ้ำซ้อน (Duplicate Data): รายการคำสั่งซื้อเดียวกันถูกบันทึกซ้ำมากกว่า 1 แถวในทุกคอลัมน์ ซึ่งต้องตรวจสอบแถวที่ซ้ำและตัดออกให้เหลือเพียงรายการจริงเพียงรายการเดียว
- รูปแบบข้อความไม่เป็นมาตรฐานเดียวกัน (Inconsistent Text): ข้อมูลข้อความที่มีอักขระช่องว่างส่วนเกินด้านหน้าหรือด้านหลัง เช่น 'อุปกรณ์ต่อพ่วง ' ซึ่งต้องปรับรูปแบบข้อความให้เป็นมาตรฐานเดียวกันก่อนจัดกลุ่มข้อมูล
- ค่าผิดปกติหรือค่าที่อยู่นอกเกณฑ์ที่กำหนด (Outliers / Invalid Values): ข้อมูลตัวเลขที่ไม่สอดคล้องกับความเป็นจริง เช่น จำนวนชิ้นที่ติดลบ (-2 ชิ้น) หรือยอดเงินที่สูงผิดปกติจากการบันทึกข้อมูลผิดพลาด (99,000 บาท)

## หลักปฏิบัติมาตรฐานในการจัดเตรียมข้อมูลด้วยไลบรารี pandas
- การตรวจสอบข้อมูลก่อนดำเนินการแก้ไข (Inspect Before Transform): ใช้การคัดกรองตามเงื่อนไข (Boolean Indexing) เพื่อแสดงเฉพาะแถวที่มีปัญหาขึ้นมาตรวจสอบรายละเอียดก่อนสั่งลบหรือแก้ไขข้อมูล
- การแยกตัวแปรเพื่อรักษาตารางข้อมูลต้นฉบับ (Preserve Original Data): ควรจัดเก็บตารางข้อมูลที่ผ่านการลบแถวซ้ำซ้อนและคัดกรองค่าว่างไว้ในตัวแปรใหม่ชื่อ df_clean เพื่อเก็บรักษาตารางข้อมูลต้นฉบับ (df) ไว้ใช้ตรวจสอบเปรียบเทียบ
- การเลือกลบค่าว่างเฉพาะคอลัมน์สำคัญ (Selective Cleaning): ระบุพารามิเตอร์ subset ในคำสั่ง .dropna() เพื่อลบเฉพาะแถวที่ขาดข้อมูลจำนวนชิ้นหรือยอดเงินรวม โดยไม่ลบรายการที่ขาดเพียงหมายเลขโทรศัพท์
- การส่งออกไฟล์ข้อมูลโดยไม่บันทึกลำดับแถว (Clean Export): เมื่อบันทึกไฟล์ใหม่ด้วยคำสั่ง .to_csv() ต้องกำหนดพารามิเตอร์ index=False เสมอ เพื่อป้องกันไม่ให้ลำดับแถวถูกบันทึกเป็นคอลัมน์เกินมาในไฟล์ CSV

---

# ส่วนที่ 3: การฝึกปฏิบัติการจัดเตรียมข้อมูลด้วยกระบวนการ ETL (ขั้นตอนที่ 1–10)

## ขั้นตอนที่ 1: การนำเข้าไลบรารี pandas และอ่านไฟล์ชุดข้อมูลต้นฉบับ nvc_tech_store.csv

นำเข้าไลบรารี pandas และอ่านตารางข้อมูลต้นฉบับ nvc_tech_store.csv พร้อมกำหนดชนิดข้อมูลของคอลัมน์หมายเลขโทรศัพท์ให้เป็นข้อความ

```python
import pandas as pd
df = pd.read_csv('nvc_tech_store.csv', dtype={'customer_phone': 'string'})
df.shape
```

- `import pandas as pd`: นำเข้าไลบรารี pandas โดยกำหนดชื่อย่อเป็น pd
- `pd.read_csv('nvc_tech_store.csv', dtype={'customer_phone': 'string'})`: อ่านไฟล์ข้อมูล CSV และกำหนดชนิดข้อมูลคอลัมน์หมายเลขโทรศัพท์เป็นข้อความ
- `df.shape`: ตรวจสอบขนาดของตารางข้อมูลต้นฉบับ ซึ่งมีขนาด (36, 7)

พิมพ์คำสั่งและกดปุ่ม Shift + Enter เพื่อรันคำสั่งและตรวจสอบผลลัพธ์

In [1]:
import pandas as pd
df = pd.read_csv('nvc_tech_store.csv', dtype={'customer_phone': 'string'})
df.shape

(36, 7)

### ผลลัพธ์และคำอธิบาย

```text
(36, 7)
```

ได้ตารางข้อมูลต้นฉบับขนาด 36 แถว 7 คอลัมน์ พร้อมสำหรับการตรวจสอบและจัดเตรียมข้อมูลในขั้นตอนถัดไป

**ข้อควรระวังในการเขียนคำสั่ง:** ต้องตรวจสอบว่าได้อัปโหลดไฟล์ nvc_tech_store.csv เข้าสู่โปรแกรม Google Colab เรียบร้อยแล้วก่อนรันคำสั่ง

**คำถามตรวจสอบความเข้าใจ:** ตารางข้อมูลต้นฉบับก่อนเริ่มกระบวนการจัดเตรียมข้อมูลมีจำนวนแถวและคอลัมน์เท่าใด

## ขั้นตอนที่ 2: การคัดกรองแถวที่มีค่าว่างด้วยเงื่อนไข (Boolean Indexing)

ระบุเงื่อนไข df['total_price'].isna() ภายในเครื่องหมายวงเล็บเหลี่ยม df[...] เพื่อแสดงเฉพาะแถวที่ไม่มีข้อมูลยอดเงินรวม

```python
df[df['total_price'].isna()]
```

- `df[...]`: การคัดกรองตารางเพื่อแสดงเฉพาะแถวที่ตรงตามเงื่อนไขที่กำหนด
- `df['total_price'].isna()`: เงื่อนไขสำหรับตรวจสอบว่าแถวใดในคอลัมน์ total_price มีค่าว่าง

พิมพ์คำสั่งและกดปุ่ม Shift + Enter เพื่อรันคำสั่งและตรวจสอบผลลัพธ์

In [2]:
df[df['total_price'].isna()]

   order_id customer_phone  ... total_price payment_status
7   ORD-107     0856677807  ...         NaN         รอชำระ
26  ORD-125     0841122325  ...         NaN       ชำระแล้ว

[2 rows x 7 columns]

### ผลลัพธ์และคำอธิบาย

| ลำดับแถว | order_id | customer_phone | product_name | category | quantity | total_price | payment_status |
| --- | --- | --- | --- | --- | --- | --- | --- |
| 7 | ORD-107 | 0856677807 | เว็บแคม Full HD 1080p | อุปกรณ์ต่อพ่วง | 1.0 | ว่าง | รอชำระ |
| 26 | ORD-125 | 0841122325 | สายแลน Cat6 5 เมตร | สายและหน่วยความจำ | 3.0 | ว่าง | ชำระแล้ว |

พบรายการคำสั่งซื้อที่ไม่มีข้อมูลยอดเงินรวมจำนวน 2 รายการ ได้แก่ รหัส ORD-107 (เว็บแคม Full HD 1080p) และรหัส ORD-125 (สายแลน Cat6 5 เมตร)

**ข้อควรระวังในการเขียนคำสั่ง:** ต้องใส่วงเล็บเหลี่ยมให้ครบทั้งส่วนของการคัดกรองตาราง df[...] และส่วนของการอ้างอิงชื่อคอลัมน์ df['total_price']

**คำถามตรวจสอบความเข้าใจ:** รายการคำสั่งซื้อรหัสใดบ้างที่ไม่มีข้อมูลในคอลัมน์ยอดเงินรวม (total_price)

## ขั้นตอนที่ 3: การนับจำนวนแถวข้อมูลที่ซ้ำซ้อนด้วยคำสั่ง df.duplicated().sum()

ใช้คำสั่ง .duplicated() เพื่อตรวจสอบแถวที่มีข้อมูลซ้ำกับแถวก่อนหน้าในทุกคอลัมน์ และใช้ .sum() เพื่อรวมจำนวนแถวที่ซ้ำซ้อนทั้งหมด

```python
df.duplicated().sum()
```

- `df.duplicated()`: คำสั่งตรวจสอบแถวที่มีข้อมูลซ้ำกับแถวก่อนหน้าทุกคอลัมน์
- `.sum()`: คำสั่งรวมจำนวนแถวที่ตรวจพบว่าเป็นข้อมูลซ้ำซ้อน

พิมพ์คำสั่งและกดปุ่ม Shift + Enter เพื่อรันคำสั่งและตรวจสอบผลลัพธ์

In [3]:
df.duplicated().sum()

2

### ผลลัพธ์และคำอธิบาย

```text
2
```

ได้ผลลัพธ์เท่ากับ 2 แสดงว่ามีรายการคำสั่งซื้อที่ถูกบันทึกข้อมูลซ้ำซ้อนเกินจำนวนจริง 2 แถว

**ข้อควรระวังในการเขียนคำสั่ง:** หากไม่ตรวจสอบและลบแถวที่บันทึกข้อมูลซ้ำซ้อน จะทำให้การคำนวณยอดจำหน่ายรวมและจำนวนคำสั่งซื้อนับซ้ำซ้อนเกินจำนวนจริง

**คำถามตรวจสอบความเข้าใจ:** ในชุดข้อมูลนี้มีแถวข้อมูลที่ถูกบันทึกซ้ำซ้อนจำนวนกี่แถว

## ขั้นตอนที่ 4: การแสดงแถวข้อมูลที่ซ้ำซ้อนทั้งหมดด้วยคำสั่ง df[df.duplicated(keep=False)]

กำหนดพารามิเตอร์ keep=False ในคำสั่ง .duplicated() เพื่อแสดงทั้งแถวข้อมูลต้นฉบับและแถวที่บันทึกซ้ำซ้อนขึ้นมาเปรียบเทียบกัน

```python
df[df.duplicated(keep=False)]
```

- `df[...]`: การคัดกรองตารางเพื่อแสดงเฉพาะแถวที่ตรงตามเงื่อนไข
- `df.duplicated(keep=False)`: เงื่อนไขที่กำหนดให้แสดงทุกแถวที่มีข้อมูลซ้ำกันทั้งหมด (ทั้งแถวแรกและแถวที่ซ้ำ)

พิมพ์คำสั่งและกดปุ่ม Shift + Enter เพื่อรันคำสั่งและตรวจสอบผลลัพธ์

In [4]:
df[df.duplicated(keep=False)]

   order_id customer_phone  ... total_price payment_status
4   ORD-105     0823344505  ...       250.0       ชำระแล้ว
5   ORD-105     0823344505  ...       250.0       ชำระแล้ว
18  ORD-118     0836655418  ...       580.0       ชำระแล้ว
19  ORD-118     0836655418  ...       580.0       ชำระแล้ว

[4 rows x 7 columns]

### ผลลัพธ์และคำอธิบาย

| ลำดับแถว | order_id | customer_phone | product_name | category | quantity | total_price | payment_status |
| --- | --- | --- | --- | --- | --- | --- | --- |
| 4 | ORD-105 | 0823344505 | แฟลชไดรฟ์ 64GB USB3 | สายและหน่วยความจำ | 1.0 | 250.0 | ชำระแล้ว |
| 5 | ORD-105 | 0823344505 | แฟลชไดรฟ์ 64GB USB3 | สายและหน่วยความจำ | 1.0 | 250.0 | ชำระแล้ว |
| 18 | ORD-118 | 0836655418 | เมาส์ไร้สาย NVC Pro | อุปกรณ์ต่อพ่วง | 2.0 | 580.0 | ชำระแล้ว |
| 19 | ORD-118 | 0836655418 | เมาส์ไร้สาย NVC Pro | อุปกรณ์ต่อพ่วง | 2.0 | 580.0 | ชำระแล้ว |

แสดงรายการที่ซ้ำซ้อนกันจำนวน 4 แถว (2 คู่รายการ) ได้แก่ รหัส ORD-105 (ลำดับแถว 4 และ 5) และรหัส ORD-118 (ลำดับแถว 18 และ 19) ซึ่งมีข้อมูลตรงกันทุกคอลัมน์

**ข้อควรระวังในการเขียนคำสั่ง:** หากไม่ระบุพารามิเตอร์ keep=False โปรแกรมจะแสดงเฉพาะแถวที่ซ้ำในลำดับถัดมา (ลำดับแถว 5 และ 19) โดยไม่แสดงแถวแรกให้เปรียบเทียบ

**คำถามตรวจสอบความเข้าใจ:** รหัสคำสั่งซื้อใดบ้างที่มีการบันทึกข้อมูลซ้ำซ้อนกัน

## ขั้นตอนที่ 5: การตรวจสอบความถี่ของหมวดหมู่สินค้าด้วยคำสั่ง .value_counts()

ใช้คำสั่ง .value_counts() เพื่อนับจำนวนรายการในแต่ละหมวดหมู่สินค้า ช่วยในการตรวจสอบความถูกต้องของข้อความและอักขระช่องว่างส่วนเกิน

```python
df['category'].value_counts()
```

- `df['category']`: การอ้างอิงคอลัมน์หมวดหมู่สินค้า (category)
- `.value_counts()`: คำสั่งนับจำนวนความถี่ของข้อมูลแต่ละกลุ่มโดยเรียงจากมากไปน้อย

พิมพ์คำสั่งและกดปุ่ม Shift + Enter เพื่อรันคำสั่งและตรวจสอบผลลัพธ์

In [5]:
df['category'].value_counts()

category
สายและหน่วยความจำ    14
อุปกรณ์ต่อพ่วง       13
อุปกรณ์เสียง          7
อุปกรณ์ต่อพ่วง        2
Name: count, dtype: int64

### ผลลัพธ์และคำอธิบาย

```text
category
สายและหน่วยความจำ    14
อุปกรณ์ต่อพ่วง       13
อุปกรณ์เสียง          7
อุปกรณ์ต่อพ่วง        2
```

พบว่าหมวดหมู่ 'อุปกรณ์ต่อพ่วง' ถูกแยกนับเป็น 2 กลุ่ม คือ 13 รายการ และ 2 รายการ เนื่องจากมีอักขระช่องว่างต่อท้ายข้อความ ('อุปกรณ์ต่อพ่วง ')

**ข้อควรระวังในการเขียนคำสั่ง:** โปรแกรมประมวลผลจะถือว่าข้อความ 'อุปกรณ์ต่อพ่วง' และ 'อุปกรณ์ต่อพ่วง ' ที่มีอักขระช่องว่างต่อท้ายข้อความ เป็นข้อมูลคนละหมวดหมู่กัน

**คำถามตรวจสอบความเข้าใจ:** เหตุใดหมวดหมู่ 'อุปกรณ์ต่อพ่วง' จึงถูกแยกแสดงผลออกเป็น 2 กลุ่ม (13 รายการ และ 2 รายการ)

## ขั้นตอนที่ 6: การตัดอักขระช่องว่างส่วนเกินด้วยคำสั่ง .str.strip()

ใช้คำสั่งจัดการข้อความ .str.strip() เพื่อลบอักขระช่องว่างส่วนเกินบริเวณด้านหน้าและด้านหลังของข้อความ แล้วบันทึกค่ากลับเข้าสู่คอลัมน์เดิม

```python
df['category'] = df['category'].str.strip()
df['category'].value_counts()
```

- `df['category'] =`: บันทึกข้อมูลที่ตัดช่องว่างส่วนเกินแล้วกลับเข้าสู่คอลัมน์ category
- `df['category'].str.strip()`: คำสั่งจัดการข้อความ (.str) เพื่อตัดอักขระช่องว่างส่วนเกินด้านหน้าและด้านหลัง (.strip())
- `df['category'].value_counts()`: นับจำนวนความถี่ซ้ำอีกครั้งเพื่อยืนยันว่าหมวดหมู่ถูกรวมเข้าด้วยกันเรียบร้อยแล้ว

พิมพ์คำสั่งและกดปุ่ม Shift + Enter เพื่อรันคำสั่งและตรวจสอบผลลัพธ์

In [6]:
df['category'] = df['category'].str.strip()
df['category'].value_counts()

category
อุปกรณ์ต่อพ่วง       15
สายและหน่วยความจำ    14
อุปกรณ์เสียง          7
Name: count, dtype: int64

### ผลลัพธ์และคำอธิบาย

```text
category
อุปกรณ์ต่อพ่วง       15
สายและหน่วยความจำ    14
อุปกรณ์เสียง          7
```

หมวดหมู่ 'อุปกรณ์ต่อพ่วง' ถูกรวมเป็นกลุ่มเดียวกันจำนวน 15 รายการ ส่งผลให้ตารางมีหมวดหมู่สินค้าครบ 3 หมวดหมู่ตามมาตรฐาน

**ข้อควรระวังในการเขียนคำสั่ง:** ต้องเขียนคำสั่งกำหนดค่า df['category'] = ไว้ด้านหน้าเสมอ หากไม่กำหนดค่ากลับ ผลลัพธ์จากการตัดช่องว่างจะไม่ถูกบันทึกทับลงในตาราง

**คำถามตรวจสอบความเข้าใจ:** หลังจากใช้คำสั่ง .str.strip() หมวดหมู่ 'อุปกรณ์ต่อพ่วง' มีจำนวนรายการรวมทั้งหมดกี่รายการ

## ขั้นตอนที่ 7: การลบแถวข้อมูลที่ซ้ำซ้อนและสร้างตารางใหม่ด้วยคำสั่ง .drop_duplicates()

ใช้คำสั่ง .drop_duplicates() เพื่อลบแถวข้อมูลที่ซ้ำซ้อนออกโดยคงแถวแรกไว้ และจัดเก็บผลลัพธ์ลงในตัวแปรตารางใหม่ชื่อ df_clean

```python
df_clean = df.drop_duplicates().copy()
df_clean.shape
```

- `df_clean =`: สร้างตัวแปรตารางใหม่สำหรับจัดเก็บตารางข้อมูลที่ผ่านการจัดเตรียมแล้ว
- `df.drop_duplicates().copy()`: คำสั่งลบแถวข้อมูลที่ซ้ำซ้อนและคัดลอกเป็นตารางใหม่
- `df_clean.shape`: ตรวจสอบขนาดของตารางหลังจากลบแถวข้อมูลที่ซ้ำซ้อน

พิมพ์คำสั่งและกดปุ่ม Shift + Enter เพื่อรันคำสั่งและตรวจสอบผลลัพธ์

In [7]:
df_clean = df.drop_duplicates().copy()
df_clean.shape

(34, 7)

### ผลลัพธ์และคำอธิบาย

```text
(34, 7)
```

ขนาดของตารางลดลงจาก (36, 7) เหลือ (34, 7) เนื่องจากแถวที่ซ้ำซ้อนของรหัส ORD-105 และ ORD-118 ถูกลบออกจำนวน 2 แถว

**ข้อควรระวังในการเขียนคำสั่ง:** ในการจัดเตรียมข้อมูลควรแยกเก็บผลลัพธ์ไว้ในตัวแปรใหม่ (df_clean) เพื่อรักษาตารางข้อมูลต้นฉบับ (df) ไว้ใช้เปรียบเทียบผลลัพธ์

**คำถามตรวจสอบความเข้าใจ:** เหตุใดจำนวนแถวของตาราง df_clean จึงลดลงจาก 36 แถว เหลือ 34 แถว

## ขั้นตอนที่ 8: การลบแถวที่มีค่าว่างในคอลัมน์สำคัญด้วยคำสั่ง .dropna(subset=...)

ใช้คำสั่ง .dropna() ร่วมกับพารามิเตอร์ subset เพื่อลบเฉพาะแถวที่มีค่าว่างในคอลัมน์จำนวนชิ้น (quantity) หรือยอดเงินรวม (total_price) โดยคงรายการที่ขาดเฉพาะหมายเลขโทรศัพท์ไว้

```python
df_clean = df_clean.dropna(subset=['quantity', 'total_price'])
df_clean.shape
```

- `df_clean.dropna(...)`: คำสั่งสำหรับลบแถวที่มีข้อมูลสูญหายหรือค่าว่าง (Missing Values)
- `subset=['quantity', 'total_price']`: พารามิเตอร์กำหนดให้ตรวจสอบค่าว่างเฉพาะในคอลัมน์ quantity และ total_price เท่านั้น
- `df_clean.shape`: ตรวจสอบขนาดของตารางหลังจากลบแถวที่มีค่าว่างในคอลัมน์สำคัญ

พิมพ์คำสั่งและกดปุ่ม Shift + Enter เพื่อรันคำสั่งและตรวจสอบผลลัพธ์

In [8]:
df_clean = df_clean.dropna(subset=['quantity', 'total_price'])
df_clean.shape

(31, 7)

### ผลลัพธ์และคำอธิบาย

```text
(31, 7)
```

ขนาดของตารางลดลงจาก (34, 7) เหลือ (31, 7) โดยตัดเฉพาะ 3 แถวที่ไม่สามารถคำนวณยอดขายได้ ส่วนรายการที่ขาดเฉพาะหมายเลขโทรศัพท์ยังคงอยู่ในตาราง

**ข้อควรระวังในการเขียนคำสั่ง:** หากใช้คำสั่ง df_clean.dropna() โดยไม่ระบุพารามิเตอร์ subset โปรแกรมจะลบแถวที่ขาดเฉพาะหมายเลขโทรศัพท์แต่มีข้อมูลยอดขายสมบูรณ์ออกไปด้วย

**คำถามตรวจสอบความเข้าใจ:** การระบุพารามิเตอร์ subset=['quantity', 'total_price'] มีข้อดีอย่างไรเมื่อเทียบกับการใช้ dropna() ทั้งตาราง

## ขั้นตอนที่ 9: การคัดกรองขอบเขตข้อมูลด้วยคำสั่ง .between() และการเปรียบเทียบค่าเฉลี่ย

ใช้คำสั่ง .between(1, 20) เพื่อคัดกรองรายการที่มีจำนวนชิ้นตั้งแต่ 1 ถึง 20 ชิ้น และมียอดเงินรวมไม่เกิน 10,000 บาท จากนั้นเปรียบเทียบค่าเฉลี่ยก่อนและหลังการจัดเตรียมข้อมูล

```python
df_clean = df_clean[df_clean['quantity'].between(1, 20) & (df_clean['total_price'] <= 10000)]
round(df['total_price'].mean(), 2), round(df_clean['total_price'].mean(), 2)
```

- `df_clean['quantity'].between(1, 20)`: เงื่อนไขตรวจสอบว่าค่าในคอลัมน์ quantity อยู่ในช่วง 1 ถึง 20 ชิ้นหรือไม่
- `& (df_clean['total_price'] <= 10000)`: ตัวดำเนินการเชื่อมเงื่อนไขว่ายอดเงินรวมต่อรายการต้องไม่เกิน 10,000 บาท
- `round(..., 2)`: ฟังก์ชันปัดเศษทศนิยม 2 ตำแหน่งเพื่อเปรียบเทียบค่าเฉลี่ยของตาราง df และ df_clean

พิมพ์คำสั่งและกดปุ่ม Shift + Enter เพื่อรันคำสั่งและตรวจสอบผลลัพธ์

In [9]:
df_clean = df_clean[df_clean['quantity'].between(1, 20) & (df_clean['total_price'] <= 10000)]
round(df['total_price'].mean(), 2), round(df_clean['total_price'].mean(), 2)

(3613.82, 754.83)

### ผลลัพธ์และคำอธิบาย

```text
(3613.82, 754.83)
```

ได้ตารางข้อมูลที่ผ่านการจัดเตรียมแล้วจำนวน 29 แถว โดยค่าเฉลี่ยยอดสั่งซื้อก่อนทำ ETL เท่ากับ 3,613.82 บาท (เนื่องจากมีค่าผิดปกติ 99,000 บาท) และภายหลังทำ ETL ค่าเฉลี่ยปรับเป็น 754.83 บาท ตามมูลค่าการซื้อขายจริง

**ข้อควรระวังในการเขียนคำสั่ง:** การเชื่อมหลายเงื่อนไขในไลบรารี pandas ต้องใช้เครื่องหมาย & และต้องใส่วงเล็บครอบเงื่อนไขย่อยให้ครบถ้วน

**คำถามตรวจสอบความเข้าใจ:** ค่าเฉลี่ยยอดสั่งซื้อต่อรายการก่อนและหลังการจัดเตรียมข้อมูลแตกต่างกันอย่างไร และมีสาเหตุมาจากปัจจัยใด

## ขั้นตอนที่ 10: การบันทึกตารางข้อมูลที่ผ่านการจัดเตรียมแล้วเป็นไฟล์ CSV ด้วยคำสั่ง .to_csv()

ขั้นตอนสุดท้ายของกระบวนการ ETL (Load): ใช้คำสั่ง .to_csv() เพื่อบันทึกตารางข้อมูล df_clean (จำนวน 29 แถว) ออกเป็นไฟล์ CSV ใหม่โดยไม่บันทึกหมายเลขลำดับแถว

```python
df_clean.to_csv('nvc_tech_store_clean.csv', index=False)
df_clean.head()
```

- `df_clean.to_csv('nvc_tech_store_clean.csv', ...)`: คำสั่งบันทึกตารางข้อมูลออกเป็นไฟล์ CSV ตามชื่อไฟล์ที่กำหนด
- `index=False`: พารามิเตอร์กำหนดไม่ให้บันทึกหมายเลขลำดับแถว (Index) เป็นคอลัมน์เพิ่มเติมในไฟล์ CSV
- `df_clean.head()`: แสดงข้อมูลตัวอย่าง 5 แถวแรกของตารางข้อมูลที่ผ่านการจัดเตรียมแล้ว

พิมพ์คำสั่งและกดปุ่ม Shift + Enter เพื่อรันคำสั่งและตรวจสอบผลลัพธ์

In [10]:
df_clean.to_csv('nvc_tech_store_clean.csv', index=False)
df_clean.head()

  order_id customer_phone  ... total_price payment_status
0  ORD-101     0812345601  ...       580.0       ชำระแล้ว
1  ORD-102     0891122302  ...      1290.0       ชำระแล้ว
2  ORD-103     0865544303  ...       450.0       ชำระแล้ว
3  ORD-104           <NA>  ...       380.0       ชำระแล้ว
4  ORD-105     0823344505  ...       250.0       ชำระแล้ว

[5 rows x 7 columns]

### ผลลัพธ์และคำอธิบาย

| ลำดับแถว | order_id | customer_phone | product_name | category | quantity | total_price | payment_status |
| --- | --- | --- | --- | --- | --- | --- | --- |
| 0 | ORD-101 | 0812345601 | เมาส์ไร้สาย NVC Pro | อุปกรณ์ต่อพ่วง | 2.0 | 580.0 | ชำระแล้ว |
| 1 | ORD-102 | 0891122302 | คีย์บอร์ดเชิงกล RGB | อุปกรณ์ต่อพ่วง | 1.0 | 1290.0 | ชำระแล้ว |
| 2 | ORD-103 | 0865544303 | แผ่นรองเมาส์ XL | อุปกรณ์ต่อพ่วง | 3.0 | 450.0 | ชำระแล้ว |
| 3 | ORD-104 | ว่าง | สายชาร์จ Type-C Fast | สายและหน่วยความจำ | 2.0 | 380.0 | ชำระแล้ว |
| 4 | ORD-105 | 0823344505 | แฟลชไดรฟ์ 64GB USB3 | สายและหน่วยความจำ | 1.0 | 250.0 | ชำระแล้ว |

โปรแกรมสร้างไฟล์ nvc_tech_store_clean.csv (ขนาด 29 แถว 7 คอลัมน์) เรียบร้อยแล้ว พร้อมสำหรับการนำไปใช้วิเคราะห์และนำเสนอข้อมูลในขั้นตอนต่อไป

**ข้อควรระวังในการเขียนคำสั่ง:** หากไม่ระบุพารามิเตอร์ index=False เมื่อนำไฟล์ CSV ที่บันทึกไว้กลับมาเปิดใช้งานใหม่ จะปรากฏคอลัมน์ Unnamed: 0 เพิ่มขึ้นมาด้านซ้ายสุด

**คำถามตรวจสอบความเข้าใจ:** พารามิเตอร์ index=False ในคำสั่ง .to_csv() มีหน้าที่และผลลัพธ์อย่างไร

---

# ส่วนที่ 3: แบบฝึกหัดปฏิบัติการท้ายคาบเรียนวันจันทร์ (เวลา 40 นาที · 10 คะแนน)

คำชี้แจง: ให้ผู้เรียนเขียนคำสั่งภาษา Python ลงในเซลล์ว่างด้านล่างของแต่ละข้อ และพิมพ์สรุปคำตอบที่ได้จากตารางข้อมูล `df_clean`

## ข้อที่ 1 (2 คะแนน): เปรียบเทียบขนาดของตารางข้อมูลก่อนและหลังทำ ETL

**โจทย์:** เขียนคำสั่งแสดงขนาดของตาราง `df.shape` เปรียบเทียบกับ `df_clean.shape` และระบุว่ามีแถวข้อมูลที่มีปัญหาถูกคัดกรองออกไปทั้งหมดกี่แถว

In [101]:
df.shape, df_clean.shape

((36, 7), (29, 7))

### แนวคำตอบและผลลัพธ์ (สำหรับผู้สอน)

```text
((36, 7), (29, 7))
```

**สรุปคำตอบ:** ตารางข้อมูลต้นฉบับมี 36 แถว และตารางข้อมูลที่ผ่านการจัดเตรียมแล้วเหลือ 29 แถว แสดงว่ามีแถวข้อมูลที่มีปัญหาถูกคัดกรองออกไปทั้งหมด 7 แถว

## ข้อที่ 2 (2 คะแนน): ตรวจสอบจำนวนค่าว่างคงเหลือในตาราง df_clean

**โจทย์:** เขียนคำสั่งตรวจสอบจำนวนค่าว่างคงเหลือด้วยคำสั่ง `df_clean.isna().sum()` และระบุว่าคอลัมน์ใดที่ยังคงมีค่าว่างเหลืออยู่ และเหลืออยู่กี่แถว พร้อมอธิบายเหตุผล

In [102]:
df_clean.isna().sum()

order_id          0
customer_phone    2
product_name      0
category          0
quantity          0
total_price       0
payment_status    0
dtype: int64

### แนวคำตอบและผลลัพธ์ (สำหรับผู้สอน)

```text
order_id          0
customer_phone    2
product_name      0
category          0
quantity          0
total_price       0
payment_status    0
```

**สรุปคำตอบ:** คอลัมน์ customer_phone ยังคงมีค่าว่างเหลืออยู่ 2 แถว เนื่องจากเป็นรายการที่มีมูลค่าการซื้อขายครบถ้วนแต่ไม่ได้ระบุหมายเลขโทรศัพท์

## ข้อที่ 3 (2 คะแนน): สรุปจำนวนรายการสินค้าแยกตามหมวดหมู่ภายหลังการจัดเตรียมข้อมูล

**โจทย์:** เขียนคำสั่งนับจำนวนรายการสินค้าแต่ละหมวดหมู่ด้วยคำสั่ง `df_clean['category'].value_counts()` และระบุจำนวนรายการของทั้ง 3 หมวดหมู่

In [103]:
df_clean['category'].value_counts()

category
อุปกรณ์ต่อพ่วง       12
สายและหน่วยความจำ    11
อุปกรณ์เสียง          6
Name: count, dtype: int64

### แนวคำตอบและผลลัพธ์ (สำหรับผู้สอน)

```text
category
อุปกรณ์ต่อพ่วง       12
สายและหน่วยความจำ    11
อุปกรณ์เสียง          6
```

**สรุปคำตอบ:** หมวดหมู่ อุปกรณ์ต่อพ่วง มี 12 รายการ, สายและหน่วยความจำ มี 11 รายการ และ อุปกรณ์เสียง มี 6 รายการ (รวม 29 รายการ)

## ข้อที่ 4 (2 คะแนน): ตรวจสอบค่าสถิติพื้นฐานของตาราง df_clean

**โจทย์:** เขียนคำสั่งคำนวณค่าสถิติพื้นฐานด้วยคำสั่ง `df_clean.describe()` และระบุค่าเฉลี่ย (`mean`) ค่าต่ำสุด (`min`) และค่าสูงสุด (`max`) ของคอลัมน์ `total_price`

In [104]:
df_clean.describe()

        quantity  total_price
count  29.000000    29.000000
mean    1.758621   754.827586
std     1.023131   501.017684
min     1.000000   180.000000
25%     1.000000   380.000000
50%     1.000000   650.000000
75%     2.000000   980.000000
max     5.000000  2580.000000

### แนวคำตอบและผลลัพธ์ (สำหรับผู้สอน)

| ลำดับแถว | quantity | total_price |
| --- | --- | --- |
| count | 29.0 | 29.0 |
| mean | 1.7586206896551724 | 754.8275862068965 |
| std | 1.0231314820474688 | 501.01768353205125 |
| min | 1.0 | 180.0 |
| 25% | 1.0 | 380.0 |
| 50% | 1.0 | 650.0 |
| 75% | 2.0 | 980.0 |
| max | 5.0 | 2580.0 |

**สรุปคำตอบ:** ภายหลังการทำ ETL คอลัมน์ total_price มีค่าเฉลี่ย (mean) เท่ากับ 754.83 บาท, ค่าต่ำสุด (min) เท่ากับ 180.00 บาท และค่าสูงสุด (max) เท่ากับ 2,580.00 บาท

## ข้อที่ 5 (2 คะแนน): ตรวจสอบความถูกต้องของไฟล์ CSV ที่บันทึกออก

**โจทย์:** เขียนคำสั่งอ่านไฟล์ `nvc_tech_store_clean.csv` ขึ้นมาแสดงข้อมูลตัวอย่าง 5 แถวแรกด้วยคำสั่ง `pd.read_csv('nvc_tech_store_clean.csv').head()` เพื่อยืนยันความถูกต้องของไฟล์

In [105]:
pd.read_csv('nvc_tech_store_clean.csv').head()

  order_id  customer_phone  ... total_price payment_status
0  ORD-101     812345601.0  ...       580.0       ชำระแล้ว
1  ORD-102     891122302.0  ...      1290.0       ชำระแล้ว
2  ORD-103     865544303.0  ...       450.0       ชำระแล้ว
3  ORD-104             NaN  ...       380.0       ชำระแล้ว
4  ORD-105     823344505.0  ...       250.0       ชำระแล้ว

[5 rows x 7 columns]

### แนวคำตอบและผลลัพธ์ (สำหรับผู้สอน)

| ลำดับแถว | order_id | customer_phone | product_name | category | quantity | total_price | payment_status |
| --- | --- | --- | --- | --- | --- | --- | --- |
| 0 | ORD-101 | 812345601.0 | เมาส์ไร้สาย NVC Pro | อุปกรณ์ต่อพ่วง | 2.0 | 580.0 | ชำระแล้ว |
| 1 | ORD-102 | 891122302.0 | คีย์บอร์ดเชิงกล RGB | อุปกรณ์ต่อพ่วง | 1.0 | 1290.0 | ชำระแล้ว |
| 2 | ORD-103 | 865544303.0 | แผ่นรองเมาส์ XL | อุปกรณ์ต่อพ่วง | 3.0 | 450.0 | ชำระแล้ว |
| 3 | ORD-104 | ว่าง | สายชาร์จ Type-C Fast | สายและหน่วยความจำ | 2.0 | 380.0 | ชำระแล้ว |
| 4 | ORD-105 | 823344505.0 | แฟลชไดรฟ์ 64GB USB3 | สายและหน่วยความจำ | 1.0 | 250.0 | ชำระแล้ว |

**สรุปคำตอบ:** ไฟล์ nvc_tech_store_clean.csv สามารถอ่านกลับมาใช้งานได้ถูกต้อง มี 7 คอลัมน์มาตรฐานโดยไม่มีคอลัมน์ Unnamed: 0 เพิ่มขึ้นมา

---

# วันอังคาร

## ขั้นตอนที่ 11: การอ่านข้อมูลสินค้าจากชีต Products ในไฟล์ Excel

อ่านข้อมูลจากชีต Products ในไฟล์ Excel และแสดงตารางข้อมูลสินค้าทั้งหมด

```python
products = pd.read_excel('nvc_store_sales.xlsx', sheet_name='Products')
products
```

- `pd.read_excel(...)`: ฟังก์ชันสำหรับอ่านไฟล์ข้อมูล Excel
- `'nvc_store_sales.xlsx'`: ชื่อไฟล์ข้อมูล Excel ที่ต้องการอ่าน
- `sheet_name='Products'`: พารามิเตอร์ระบุชื่อชีตข้อมูลสินค้าที่ต้องการนำเข้า
- `products`: แสดงตารางข้อมูลสินค้าทั้งหมด 6 แถว

พิมพ์คำสั่งและกดปุ่ม Shift + Enter เพื่อรันคำสั่งและตรวจสอบผลลัพธ์

In [11]:
products = pd.read_excel('nvc_store_sales.xlsx', sheet_name='Products')
products

  product_id  product_name          category  cost_price  selling_price
0       P001     ชาไทยเย็น     เครื่องดื่มชง          15             30
1       P002     กาแฟโบราณ     เครื่องดื่มชง          18             35
2       P003       ชามะนาว  เครื่องดื่มผลไม้          12             25
3       P004  โกโก้เข้มข้น     เครื่องดื่มชง          18             35
4       P005   นมสดคาราเมล     เครื่องดื่มนม          20             35
5       P006     ชาเขียวนม     เครื่องดื่มชง          20             40

### ผลลัพธ์และคำอธิบาย

| ลำดับแถว | product_id | product_name | category | cost_price | selling_price |
| --- | --- | --- | --- | --- | --- |
| 0 | P001 | ชาไทยเย็น | เครื่องดื่มชง | 15 | 30 |
| 1 | P002 | กาแฟโบราณ | เครื่องดื่มชง | 18 | 35 |
| 2 | P003 | ชามะนาว | เครื่องดื่มผลไม้ | 12 | 25 |
| 3 | P004 | โกโก้เข้มข้น | เครื่องดื่มชง | 18 | 35 |
| 4 | P005 | นมสดคาราเมล | เครื่องดื่มนม | 20 | 35 |
| 5 | P006 | ชาเขียวนม | เครื่องดื่มชง | 20 | 40 |

ชีต Products มีขนาด 6 แถว 5 คอลัมน์ จัดเก็บรหัสสินค้า ชื่อสินค้า หมวดหมู่ ต้นทุน และราคาจำหน่ายต่อหน่วย

**ข้อควรระวังในการเขียนคำสั่ง:** การระบุชื่อชีตในพารามิเตอร์ sheet_name ต้องสะกดตัวอักษรพิมพ์ใหญ่และพิมพ์เล็กให้ตรงตามต้นฉบับ เช่น Products

**คำถามตรวจสอบความเข้าใจ:** คอลัมน์ selling_price ในตารางสินค้าหมายถึงข้อมูลใดและมีหน่วยวัดเป็นอะไร

## ขั้นตอนที่ 12: การอ่านข้อมูลรายการขายรายวันจากชีต Daily_Sales ในไฟล์ Excel

อ่านข้อมูลจากชีต Daily_Sales และแสดงข้อมูลตัวอย่าง 5 แถวแรกของรายการขาย

```python
sales = pd.read_excel('nvc_store_sales.xlsx', sheet_name='Daily_Sales')
sales.head()
```

- `sales =`: กำหนดตัวแปรสำหรับจัดเก็บตารางรายการขายรายวัน
- `sheet_name='Daily_Sales'`: พารามิเตอร์ระบุชื่อชีตรายการขายรายวัน
- `sales.head()`: แสดงข้อมูลตัวอย่าง 5 แถวแรกของตารางรายการขาย

พิมพ์คำสั่งและกดปุ่ม Shift + Enter เพื่อรันคำสั่งและตรวจสอบผลลัพธ์

In [12]:
sales = pd.read_excel('nvc_store_sales.xlsx', sheet_name='Daily_Sales')
sales.head()

  order_id product_id  quantity payment_method   sale_date
0   ORD001       P001         2         เงินสด  2026-11-01
1   ORD002       P002         1      พร้อมเพย์  2026-11-01
2   ORD003       P001         3      พร้อมเพย์  2026-11-01
3   ORD004       P004         1         เงินสด  2026-11-01
4   ORD005       P003         2      พร้อมเพย์  2026-11-01

### ผลลัพธ์และคำอธิบาย

| ลำดับแถว | order_id | product_id | quantity | payment_method | sale_date |
| --- | --- | --- | --- | --- | --- |
| 0 | ORD001 | P001 | 2 | เงินสด | 2026-11-01 |
| 1 | ORD002 | P002 | 1 | พร้อมเพย์ | 2026-11-01 |
| 2 | ORD003 | P001 | 3 | พร้อมเพย์ | 2026-11-01 |
| 3 | ORD004 | P004 | 1 | เงินสด | 2026-11-01 |
| 4 | ORD005 | P003 | 2 | พร้อมเพย์ | 2026-11-01 |

แสดงข้อมูลรหัสรายการขาย รหัสสินค้า จำนวนชิ้น วิธีการชำระเงิน และวันที่ขาย

**ข้อควรระวังในการเขียนคำสั่ง:** หากไม่ระบุพารามิเตอร์ sheet_name ไลบรารี pandas จะอ่านเฉพาะชีตแรกสุดของไฟล์ Excel เท่านั้น

**คำถามตรวจสอบความเข้าใจ:** คอลัมน์ใดทำหน้าที่เป็นคีย์หลักสำหรับเชื่อมโยงตาราง sales เข้ากับตาราง products

## ขั้นตอนที่ 13: การตรวจสอบโครงสร้างและชนิดข้อมูลของตารางรายการขาย

ตรวจสอบรายชื่อคอลัมน์ ชนิดข้อมูล และขนาดของตาราง sales

```python
sales.columns.tolist(), sales.dtypes, sales.shape
```

- `sales.columns.tolist()`: แสดงรายชื่อคอลัมน์ทั้งหมดในรูปแบบรายการ (List)
- `sales.dtypes`: ตรวจสอบชนิดข้อมูลของแต่ละคอลัมน์
- `sales.shape`: ตรวจสอบจำนวนแถวและจำนวนคอลัมน์ของตาราง

พิมพ์คำสั่งและกดปุ่ม Shift + Enter เพื่อรันคำสั่งและตรวจสอบผลลัพธ์

In [13]:
sales.columns.tolist(), sales.dtypes, sales.shape

(['order_id', 'product_id', 'quantity', 'payment_method', 'sale_date'], order_id          object
product_id        object
quantity           int64
payment_method    object
sale_date         object
dtype: object, (15, 5))

### ผลลัพธ์และคำอธิบาย

```text
(['order_id', 'product_id', 'quantity', 'payment_method', 'sale_date'], order_id          object
product_id        object
quantity           int64
payment_method    object
sale_date         object
dtype: object, (15, 5))
```

ตาราง Daily_Sales มีขนาด 15 แถว 5 คอลัมน์ โดยคอลัมน์ quantity เป็นตัวเลขจำนวนเต็มและคอลัมน์อื่นเป็นข้อความ

**ข้อควรระวังในการเขียนคำสั่ง:** คอลัมน์ sale_date ยังมีชนิดข้อมูลเป็นข้อความ จึงควรตรวจสอบรูปแบบวันที่ก่อนนำไปจัดเรียงตามลำดับเวลา

**คำถามตรวจสอบความเข้าใจ:** ตาราง Daily_Sales มีจำนวนแถวและจำนวนคอลัมน์ทั้งหมดเท่าใด

## ขั้นตอนที่ 14: การจัดทำตารางพจนานุกรมข้อมูล (Data Dictionary) ของชุดข้อมูล nvc_tech_store.csv

สร้างตารางสรุปรายชื่อคอลัมน์ ชนิดข้อมูล และความหมายของแต่ละคอลัมน์ในชุดข้อมูล nvc_tech_store

```python
dictionary = pd.DataFrame({
    'column': df.columns,
    'dtype': df.dtypes.astype(str).values,
    'meaning': ['รหัสคำสั่งซื้อ', 'หมายเลขโทรศัพท์ลูกค้า', 'ชื่อสินค้า', 'หมวดหมู่สินค้า', 'จำนวนชิ้น', 'ยอดเงินรวม (บาท)', 'สถานะการชำระเงิน']
})
dictionary
```

- `pd.DataFrame({...})`: คำสั่งสร้างตารางข้อมูลใหม่
- `df.columns`: ดึงรายชื่อคอลัมน์ทั้งหมดจากตาราง df
- `df.dtypes.astype(str).values`: ดึงชนิดข้อมูลของแต่ละคอลัมน์ในรูปแบบข้อความ

พิมพ์คำสั่งและกดปุ่ม Shift + Enter เพื่อรันคำสั่งและตรวจสอบผลลัพธ์

In [14]:
dictionary = pd.DataFrame({
    'column': df.columns,
    'dtype': df.dtypes.astype(str).values,
    'meaning': ['รหัสคำสั่งซื้อ', 'หมายเลขโทรศัพท์ลูกค้า', 'ชื่อสินค้า', 'หมวดหมู่สินค้า', 'จำนวนชิ้น', 'ยอดเงินรวม (บาท)', 'สถานะการชำระเงิน']
})
dictionary

           column    dtype                meaning
0        order_id   object         รหัสคำสั่งซื้อ
1  customer_phone   string  หมายเลขโทรศัพท์ลูกค้า
2    product_name   object             ชื่อสินค้า
3        category   object         หมวดหมู่สินค้า
4        quantity  float64              จำนวนชิ้น
5     total_price  float64       ยอดเงินรวม (บาท)
6  payment_status   object       สถานะการชำระเงิน

### ผลลัพธ์และคำอธิบาย

| ลำดับแถว | column | dtype | meaning |
| --- | --- | --- | --- |
| 0 | order_id | object | รหัสคำสั่งซื้อ |
| 1 | customer_phone | string | หมายเลขโทรศัพท์ลูกค้า |
| 2 | product_name | object | ชื่อสินค้า |
| 3 | category | object | หมวดหมู่สินค้า |
| 4 | quantity | float64 | จำนวนชิ้น |
| 5 | total_price | float64 | ยอดเงินรวม (บาท) |
| 6 | payment_status | object | สถานะการชำระเงิน |

ได้ตารางพจนานุกรมข้อมูลจำนวน 7 แถว 3 คอลัมน์ แสดงชื่อคอลัมน์ ชนิดข้อมูล และความหมายของแต่ละคอลัมน์อย่างชัดเจน

**ข้อควรระวังในการเขียนคำสั่ง:** จำนวนคำอธิบายในรายการ meaning ต้องมีจำนวนครบ 7 รายการให้ตรงกับจำนวนคอลัมน์ของตาราง

**คำถามตรวจสอบความเข้าใจ:** การจัดทำตารางพจนานุกรมข้อมูลมีประโยชน์ต่อการวิเคราะห์ข้อมูลอย่างไร

## สรุป

อธิบายคำสั่ง ผลลัพธ์ หน่วย และข้อจำกัด บันทึก Notebook สำหรับทบทวน