# W03 — ETL ตรวจคุณภาพข้อมูล

## จุดประสงค์การเรียนรู้
- ตรวจและนับค่าว่างกับแถวซ้ำได้
- ใช้หน้ากากเลือกอายุและ GPA ที่ผิดช่วงได้
- แยกปัญหาคุณภาพออกจากค่าว่างและบันทึกหลักฐานได้

## การเตรียมไฟล์ข้อมูล
- student_register_dirty.csv

อัปโหลดไฟล์ข้อมูลผ่านเมนู Files ในโปรแกรม Google Colab แล้วพิมพ์คำสั่งและรันผลลัพธ์ตามลำดับทีละขั้นตอน

## โครงสร้างชุดข้อมูล
- ไฟล์ student_register_dirty.csv: จำนวน 42 แถว 7 คอลัมน์ ได้แก่ student_id, name, major, age, gpa, phone, updated_date

## ขั้นตอนที่ 1: เรียกใช้ pandas

นำเข้าเครื่องมือจัดการตาราง และตั้งชื่อย่อว่า pd

```python
import pandas as pd
```

- `import`: นำเข้าไลบรารี
- `as pd`: กำหนดชื่อย่อสำหรับคำสั่งต่อไป

พิมพ์คำสั่งและกดปุ่ม Shift + Enter เพื่อรันคำสั่งและตรวจสอบผลลัพธ์

In [1]:
import pandas as pd

### ผลลัพธ์และคำอธิบาย

```text
รันคำสั่งสำเร็จ (ไม่มีข้อความแจ้งข้อผิดพลาด)
```

เมื่อสำเร็จจะไม่มีตารางปรากฏ และสามารถใช้ pd ได้

**ข้อควรระวังในการเขียนคำสั่ง:** เขียน pandas และ pd ด้วยตัวพิมพ์เล็ก

**คำถามตรวจสอบความเข้าใจ:** รันแล้วไม่มีข้อความผิดพลาด

## ขั้นตอนที่ 2: อ่านทะเบียนที่มีปัญหา

อ่านทะเบียนและกำหนด phone เป็นข้อความ

```python
df = pd.read_csv('student_register_dirty.csv', dtype={'phone': 'string'})
df
```

- `dtype`: กำหนดชนิดข้อมูลขณะอ่าน
- `{'phone': 'string'}`: dict ระบุให้ phone เก็บข้อความ

พิมพ์คำสั่งและกดปุ่ม Shift + Enter เพื่อรันคำสั่งและตรวจสอบผลลัพธ์

In [2]:
df = pd.read_csv('student_register_dirty.csv', dtype={'phone': 'string'})
df

   student_id            name  ...       phone  updated_date
0        S001     สมชาย สุขสม  ...  0882903368    2026-06-01
1        S002     อรุณ ศรีสุข  ...  0845046288    2026-06-09
2        S003     วรรณา สุขสม  ...  0877470852    2026-06-06
3        S004       ชัย สุขสม  ...  0863778945    2026-06-04
4        S005      กมล ศรีสุข  ...  0813749650    2026-06-05
5        S006      ศิริ ทองคำ  ...  0856208603    2026-06-08
6        S007      อรุณ บุญมา  ...  0823711300    2026-06-04
7        S008      ศิริ สุขสม  ...  0891907998    2026-06-01
8        S009      ศิริ บุญมา  ...  0898662305    2026-06-02
9        S010    ภูมิ แก้วมณี  ...  0833960779    2026-06-07
10       S011      อรุณ บุญมา  ...  0863128543    2026-06-08
11       S012       ธนา บุญมา  ...  0827050801    2026-06-01
12       S013   อนันต์ ศรีสุข  ...  0889976351    2026-06-08
13       S014       ชัย ทองคำ  ...  0812871813    2026-06-01
14       S015      อรุณ บุญมา  ...  0828689916    2026-06-07
15       S016      จิรา สุขสม  ...        <NA>    2026-06-09
16       S017      กมล ศรีสุข  ...  0827592411    2026-06-01
17       S018      ภูมิ บุญมา  ...  0879358465    2026-06-07
18       S019     จิรา ศรีสุข  ...  0878524460    2026-06-01
19       S020    จิรา แก้วมณี  ...  0830106149    2026-06-03
20       S021  อนันต์ แก้วมณี  ...  0818288654    2026-06-06
21       S022      ชัย ศรีสุข  ...  0824241764    2026-06-09
22       S023     สมชาย สุขสม  ...  0823119148    2026-06-09
23       S024     ศิริ ศรีสุข  ...  0892212100    2026-06-09
24       S025       พร ศรีสุข  ...  0878203564    2026-06-09
25       S026    อรุณ แก้วมณี  ...        0812    2026-06-09
26       S027      ภูมิ สุขสม  ...  0862662255    2026-06-08
27       S028      วรรณา ใจดี  ...  0838546741    2026-06-05
28       S029       อรุณ ใจดี  ...  0859148289    2026-06-03
29       S030      ปิยะ สุขสม  ...  0822633303    2026-06-07
30       S031    ภูมิ แก้วมณี  ...  0831671607    2020-06-05
31       S032     ณัฐ แก้วมณี  ...  0852751778    2026-06-02
32       S033      มาลี ทองคำ  ...  0869117285    2026-06-01
33       S034       ธนา ทองคำ  ...  0818628964    2020-06-02
34       S035      ภูมิ สุขสม  ...  0815313436    2026-06-03
35       S036      ปิยะ สุขสม  ...  0844709914    2026-06-07
36       S037   อนันต์ ศรีสุข  ...  0853895707    2026-06-02
37       S038       ปิยะ ใจดี  ...  0819719255    2026-06-05
38       S039     สมชาย บุญมา  ...  0839851095    2026-06-02
39       S040       ปิยะ ใจดี  ...  0884231009    2026-06-07
40       S006      ศิริ ทองคำ  ...  0856208603    2026-06-08
41       S021  อนันต์ แก้วมณี  ...  0818288654    2026-06-06

[42 rows x 7 columns]

### ผลลัพธ์และคำอธิบาย

| ลำดับแถว | student_id | name | major | age | gpa | phone | updated_date |
| --- | --- | --- | --- | --- | --- | --- | --- |
| 0 | S001 | สมชาย สุขสม | การตลาด | 19.0 | 2.11 | 0882903368 | 2026-06-01 |
| 1 | S002 | อรุณ ศรีสุข | คอมพิวเตอร์ธุรกิจ | 22.0 | 3.61 | 0845046288 | 2026-06-09 |
| 2 | S003 | วรรณา สุขสม | คอมพิวเตอร์ธุรกิจ | 18.0 | 2.92 | 0877470852 | 2026-06-06 |
| 3 | S004 | ชัย สุขสม | การตลาด | 18.0 | ว่าง | 0863778945 | 2026-06-04 |
| 4 | S005 | กมล ศรีสุข | คอมพิวเตอร์ธุรกิจ | 19.0 | 3.34 | 0813749650 | 2026-06-05 |
| 5 | S006 | ศิริ ทองคำ | เทคโนโลยีสารสนเทศ | 22.0 | 3.07 | 0856208603 | 2026-06-08 |
| 6 | S007 | อรุณ บุญมา | คอมพิวเตอร์ธุรกิจ | 19.0 | 1.97 | 0823711300 | 2026-06-04 |
| 7 | S008 | ศิริ สุขสม | คอมพิวเตอร์ธุรกิจ | 150.0 | 2.81 | 0891907998 | 2026-06-01 |
| 8 | S009 | ศิริ บุญมา | คอมพิวเตอร์ธุรกิจ | 22.0 | 1.98 | 0898662305 | 2026-06-02 |
| 9 | S010 | ภูมิ แก้วมณี | การตลาด | 18.0 | 2.8 | 0833960779 | 2026-06-07 |

ได้ตาราง 42 แถว 7 คอลัมน์; phone รักษาศูนย์นำหน้า

**ข้อควรระวังในการเขียนคำสั่ง:** อย่าอ่าน phone เป็นจำนวนเต็ม เพราะศูนย์นำหน้าอาจหาย

**คำถามตรวจสอบความเข้าใจ:** พบ phone เริ่มด้วย 0 และคอลัมน์ age, gpa

## ขั้นตอนที่ 3: ดูห้าแถวแรก

ตรวจว่าอ่านทะเบียนถูกไฟล์

```python
df.head()
```

- `.head()`: แสดงห้าแถวแรก

พิมพ์คำสั่งและกดปุ่ม Shift + Enter เพื่อรันคำสั่งและตรวจสอบผลลัพธ์

In [3]:
df.head()

  student_id         name              major  ...   gpa       phone updated_date
0       S001  สมชาย สุขสม            การตลาด  ...  2.11  0882903368   2026-06-01
1       S002  อรุณ ศรีสุข  คอมพิวเตอร์ธุรกิจ  ...  3.61  0845046288   2026-06-09
2       S003  วรรณา สุขสม  คอมพิวเตอร์ธุรกิจ  ...  2.92  0877470852   2026-06-06
3       S004    ชัย สุขสม            การตลาด  ...   NaN  0863778945   2026-06-04
4       S005   กมล ศรีสุข  คอมพิวเตอร์ธุรกิจ  ...  3.34  0813749650   2026-06-05

[5 rows x 7 columns]

### ผลลัพธ์และคำอธิบาย

| ลำดับแถว | student_id | name | major | age | gpa | phone | updated_date |
| --- | --- | --- | --- | --- | --- | --- | --- |
| 0 | S001 | สมชาย สุขสม | การตลาด | 19.0 | 2.11 | 0882903368 | 2026-06-01 |
| 1 | S002 | อรุณ ศรีสุข | คอมพิวเตอร์ธุรกิจ | 22.0 | 3.61 | 0845046288 | 2026-06-09 |
| 2 | S003 | วรรณา สุขสม | คอมพิวเตอร์ธุรกิจ | 18.0 | 2.92 | 0877470852 | 2026-06-06 |
| 3 | S004 | ชัย สุขสม | การตลาด | 18.0 | ว่าง | 0863778945 | 2026-06-04 |
| 4 | S005 | กมล ศรีสุข | คอมพิวเตอร์ธุรกิจ | 19.0 | 3.34 | 0813749650 | 2026-06-05 |

เห็น S001–S005; gpa ของ S004 เป็น NaN ซึ่งหมายถึงค่าว่าง

**ข้อควรระวังในการเขียนคำสั่ง:** NaN ไม่ใช่คะแนนศูนย์

**คำถามตรวจสอบความเข้าใจ:** ชี้ค่าว่างของ S004 ได้

## ขั้นตอนที่ 4: ตรวจชนิดข้อมูล

ตรวจชนิดข้อมูลก่อนตั้งเกณฑ์

```python
df.dtypes
```

- `.dtypes`: ชนิดข้อมูลของแต่ละคอลัมน์

พิมพ์คำสั่งและกดปุ่ม Shift + Enter เพื่อรันคำสั่งและตรวจสอบผลลัพธ์

In [4]:
df.dtypes

student_id              object
name                    object
major                   object
age                    float64
gpa                    float64
phone           string[python]
updated_date            object
dtype: object

### ผลลัพธ์และคำอธิบาย

```text
student_id              object
name                    object
major                   object
age                    float64
gpa                    float64
phone           string[python]
updated_date            object
```

age และ gpa เป็น float64; phone เป็น string; updated_date ยังเป็น object

**ข้อควรระวังในการเขียนคำสั่ง:** ชนิด float64 อาจเกิดจากการมีค่าว่าง ไม่ได้แปลว่าอายุมีเศษปีเสมอ

**คำถามตรวจสอบความเข้าใจ:** ระบุคอลัมน์ตัวเลขและข้อความได้

## ขั้นตอนที่ 5: ตรวจตำแหน่งค่าว่าง

สร้างตาราง True/False สำหรับค่าว่าง

```python
missing = df.isna()
missing
```

- `.isna()`: ให้ True เมื่อเป็นค่าว่าง
- `False`: ไม่เป็นค่าว่างตามการตรวจนี้

พิมพ์คำสั่งและกดปุ่ม Shift + Enter เพื่อรันคำสั่งและตรวจสอบผลลัพธ์

In [5]:
missing = df.isna()
missing

    student_id   name  major    age    gpa  phone  updated_date
0        False  False  False  False  False  False         False
1        False  False  False  False  False  False         False
2        False  False  False  False  False  False         False
3        False  False  False  False   True  False         False
4        False  False  False  False  False  False         False
5        False  False  False  False  False  False         False
6        False  False  False  False  False  False         False
7        False  False  False  False  False  False         False
8        False  False  False  False  False  False         False
9        False  False  False  False  False  False         False
10       False  False  False   True  False  False         False
11       False  False  False  False  False  False         False
12       False  False  False  False  False  False         False
13       False  False  False  False  False  False         False
14       False  False  False  False  False  False         False
15       False  False  False  False  False   True         False
16       False  False  False  False  False  False         False
17       False  False  False  False  False  False         False
18       False  False  False  False  False  False         False
19       False  False  False  False  False  False         False
20       False  False  False  False  False  False         False
21       False  False  False  False  False  False         False
22       False  False  False  False   True  False         False
23       False  False  False  False  False  False         False
24       False  False  False  False  False  False         False
25       False  False  False  False  False  False         False
26       False  False  False  False  False  False         False
27       False  False  False  False  False  False         False
28       False  False  False  False  False  False         False
29       False  False  False  False  False  False         False
30       False  False  False  False  False  False         False
31       False  False  False  False  False  False         False
32       False  False  False  False  False  False         False
33       False  False  False  False  False  False         False
34       False  False  False  False  False  False         False
35       False  False  False  False  False  False         False
36       False  False  False  False  False  False         False
37       False  False  False  False  False  False         False
38       False  False  False  False  False  False         False
39       False  False  False  False  False  False         False
40       False  False  False  False  False  False         False
41       False  False  False  False  False  False         False

### ผลลัพธ์และคำอธิบาย

| ลำดับแถว | student_id | name | major | age | gpa | phone | updated_date |
| --- | --- | --- | --- | --- | --- | --- | --- |
| 0 | False | False | False | False | False | False | False |
| 1 | False | False | False | False | False | False | False |
| 2 | False | False | False | False | False | False | False |
| 3 | False | False | False | False | True | False | False |
| 4 | False | False | False | False | False | False | False |
| 5 | False | False | False | False | False | False | False |
| 6 | False | False | False | False | False | False | False |
| 7 | False | False | False | False | False | False | False |
| 8 | False | False | False | False | False | False | False |
| 9 | False | False | False | False | False | False | False |

ตาราง True/False มีขนาดเท่า df; gpa ของ S004 เป็น True

**ข้อควรระวังในการเขียนคำสั่ง:** True ในตารางนี้หมายถึงค่าว่าง ไม่ใช่ค่าถูกต้อง

**คำถามตรวจสอบความเข้าใจ:** หา True ในคอลัมน์ gpa ได้

## ขั้นตอนที่ 6: นับค่าว่างแยกคอลัมน์

รวมค่า True ในแต่ละคอลัมน์

```python
missing_count = missing.sum()
missing_count
```

- `.sum()`: รวม True เป็น 1 และ False เป็น 0

พิมพ์คำสั่งและกดปุ่ม Shift + Enter เพื่อรันคำสั่งและตรวจสอบผลลัพธ์

In [6]:
missing_count = missing.sum()
missing_count

student_id      0
name            0
major           0
age             1
gpa             2
phone           1
updated_date    0
dtype: int64

### ผลลัพธ์และคำอธิบาย

```text
student_id      0
name            0
major           0
age             1
gpa             2
phone           1
updated_date    0
```

age ว่าง 1, gpa ว่าง 2, phone ว่าง 1; คอลัมน์อื่นว่าง 0

**ข้อควรระวังในการเขียนคำสั่ง:** จำนวนค่าว่างหลายคอลัมน์อาจอยู่ในคนเดียวกัน จึงห้ามรวมเป็นจำนวนคนทันที

**คำถามตรวจสอบความเข้าใจ:** อ่านจำนวนค่าว่างของ gpa ได้ 2

## ขั้นตอนที่ 7: ตรวจแถวซ้ำ

ระบุแถวที่ซ้ำกับแถวก่อนหน้าทุกคอลัมน์

```python
duplicate_rows = df.duplicated()
duplicate_rows
```

- `.duplicated()`: ให้ True กับสำเนาซ้ำ โดยเก็บรายการแรกเป็น False

พิมพ์คำสั่งและกดปุ่ม Shift + Enter เพื่อรันคำสั่งและตรวจสอบผลลัพธ์

In [7]:
duplicate_rows = df.duplicated()
duplicate_rows

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30    False
31    False
32    False
33    False
34    False
35    False
36    False
37    False
38    False
39    False
40     True
41     True
dtype: bool

### ผลลัพธ์และคำอธิบาย

```text
0     False
1     False
2     False
3     False
4     False
5     False
6     False
      ...  
35    False
36    False
37    False
38    False
39    False
40     True
41     True
```

True อยู่ที่ดัชนี 40 และ 41; เป็นสำเนาของแถวก่อนหน้า

**ข้อควรระวังในการเขียนคำสั่ง:** การมีชื่อเหมือนกันอย่างเดียวไม่เท่ากับซ้ำทั้งแถว

**คำถามตรวจสอบความเข้าใจ:** หา True สองตำแหน่งได้

## ขั้นตอนที่ 8: นับสำเนาซ้ำ

นับแถวซ้ำที่เกินจากรายการแรก

```python
duplicate_rows.sum()
```

- `.sum()`: รวม True เพื่อหาจำนวนสำเนาซ้ำ

พิมพ์คำสั่งและกดปุ่ม Shift + Enter เพื่อรันคำสั่งและตรวจสอบผลลัพธ์

In [8]:
duplicate_rows.sum()

2

### ผลลัพธ์และคำอธิบาย

```text
2
```

ได้ 2 หมายถึงมีสำเนาซ้ำเกินมา 2 แถว

**ข้อควรระวังในการเขียนคำสั่ง:** ผลไม่ใช่จำนวนสมาชิกทั้งหมดของกลุ่มที่ซ้ำ

**คำถามตรวจสอบความเข้าใจ:** อธิบายได้ว่าเป็นสำเนาที่เกินมา 2 แถว

## ขั้นตอนที่ 9: ดูแถวที่ถูกระบุว่าซ้ำ

เลือกเฉพาะแถวที่หน้ากากเป็น True

```python
df.loc[duplicate_rows]
```

- `.loc[]`: เลือกแถวตามเงื่อนไขในวงเล็บเหลี่ยม
- `duplicate_rows`: หน้ากาก True/False ที่มีดัชนีตรงกับ df

พิมพ์คำสั่งและกดปุ่ม Shift + Enter เพื่อรันคำสั่งและตรวจสอบผลลัพธ์

In [9]:
df.loc[duplicate_rows]

   student_id            name              major  ...   gpa       phone updated_date
40       S006      ศิริ ทองคำ  เทคโนโลยีสารสนเทศ  ...  3.07  0856208603   2026-06-08
41       S021  อนันต์ แก้วมณี            การตลาด  ...  2.05  0818288654   2026-06-06

[2 rows x 7 columns]

### ผลลัพธ์และคำอธิบาย

| ลำดับแถว | student_id | name | major | age | gpa | phone | updated_date |
| --- | --- | --- | --- | --- | --- | --- | --- |
| 40 | S006 | ศิริ ทองคำ | เทคโนโลยีสารสนเทศ | 22.0 | 3.07 | 0856208603 | 2026-06-08 |
| 41 | S021 | อนันต์ แก้วมณี | การตลาด | 22.0 | 2.05 | 0818288654 | 2026-06-06 |

แสดงดัชนี 40 และ 41 คือ S006 และ S021

**ข้อควรระวังในการเขียนคำสั่ง:** ยังเป็นการตรวจสอบ ไม่มีแถวถูกลบ

**คำถามตรวจสอบความเข้าใจ:** พบ S006 และ S021 ในผลลัพธ์

## ขั้นตอนที่ 10: แยกอายุที่มีค่า

ตรวจว่ามีข้อมูลอายุหรือไม่

```python
age_present = df['age'].notna()
age_present
```

- `df['age']`: เลือกหนึ่งคอลัมน์เป็น Series
- `.notna()`: ให้ True เมื่อไม่ว่าง

พิมพ์คำสั่งและกดปุ่ม Shift + Enter เพื่อรันคำสั่งและตรวจสอบผลลัพธ์

In [10]:
age_present = df['age'].notna()
age_present

0      True
1      True
2      True
3      True
4      True
5      True
6      True
7      True
8      True
9      True
10    False
11     True
12     True
13     True
14     True
15     True
16     True
17     True
18     True
19     True
20     True
21     True
22     True
23     True
24     True
25     True
26     True
27     True
28     True
29     True
30     True
31     True
32     True
33     True
34     True
35     True
36     True
37     True
38     True
39     True
40     True
41     True
Name: age, dtype: bool

### ผลลัพธ์และคำอธิบาย

```text
0     True
1     True
2     True
3     True
4     True
5     True
6     True
      ... 
35    True
36    True
37    True
38    True
39    True
40    True
41    True
```

True 41 แถว และ False 1 แถว

**ข้อควรระวังในการเขียนคำสั่ง:** notna ตรวจการมีค่า ยังไม่ตรวจว่าค่าอยู่ในช่วง

**คำถามตรวจสอบความเข้าใจ:** อธิบายความต่างระหว่างมีค่าและค่าถูกช่วงได้

## ขั้นตอนที่ 11: ตรวจอายุในเกณฑ์

ใช้ช่วงอายุ 15–60 ปีเป็นเกณฑ์สมมติสำหรับตรวจข้อมูล

```python
age_valid = df['age'].between(15, 60)
age_valid
```

- `.between(15, 60)`: ให้ True เมื่อค่าตั้งแต่ 15 ถึง 60 รวมขอบช่วง

พิมพ์คำสั่งและกดปุ่ม Shift + Enter เพื่อรันคำสั่งและตรวจสอบผลลัพธ์

In [11]:
age_valid = df['age'].between(15, 60)
age_valid

0      True
1      True
2      True
3      True
4      True
5      True
6      True
7     False
8      True
9      True
10    False
11     True
12     True
13     True
14     True
15     True
16     True
17     True
18     True
19     True
20     True
21     True
22     True
23     True
24     True
25     True
26     True
27     True
28     True
29     True
30     True
31     True
32     True
33     True
34     True
35     True
36     True
37     True
38     True
39     True
40     True
41     True
Name: age, dtype: bool

### ผลลัพธ์และคำอธิบาย

```text
0     True
1     True
2     True
3     True
4     True
5     True
6     True
      ... 
35    True
36    True
37    True
38    True
39    True
40    True
41    True
```

False 2 แถว: อายุ 150 และอายุที่ว่าง; จึงยังนับเป็นค่าผิดช่วงทั้งหมดไม่ได้

**ข้อควรระวังในการเขียนคำสั่ง:** False อาจมาจากค่าว่าง ต้องแยกตรวจ

**คำถามตรวจสอบความเข้าใจ:** บอกได้ว่า 15 และ 60 อยู่ในเกณฑ์

## ขั้นตอนที่ 12: สร้างหน้ากากอายุผิดช่วง

เลือกอายุที่อยู่นอกเกณฑ์และมีค่าจริง

```python
age_bad = ~age_valid & age_present
age_bad
```

- `~`: กลับ True/False
- `&`: ต้องเป็น True ทั้งสองเงื่อนไข

พิมพ์คำสั่งและกดปุ่ม Shift + Enter เพื่อรันคำสั่งและตรวจสอบผลลัพธ์

In [12]:
age_bad = ~age_valid & age_present
age_bad

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7      True
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30    False
31    False
32    False
33    False
34    False
35    False
36    False
37    False
38    False
39    False
40    False
41    False
Name: age, dtype: bool

### ผลลัพธ์และคำอธิบาย

```text
0     False
1     False
2     False
3     False
4     False
5     False
6     False
      ...  
35    False
36    False
37    False
38    False
39    False
40    False
41    False
```

เหลือ True 1 แถว คืออายุ 150; ค่าว่างไม่ถูกนับรวม

**ข้อควรระวังในการเขียนคำสั่ง:** ใช้ & กับหน้ากาก ไม่ใช้คำว่า and

**คำถามตรวจสอบความเข้าใจ:** อธิบายได้ว่าทำไมค่าว่างไม่อยู่ใน age_bad

---

# คาบเรียนที่ 2 (ขั้นตอนที่ 1–12)

## ขั้นตอนที่ 13: เปิดแถวอายุผิดช่วง

ดูรหัสและอายุเฉพาะรายการผิดช่วง

```python
df.loc[age_bad, ['student_id', 'age']]
```

- `.loc[แถว, คอลัมน์]`: เลือกแถวและคอลัมน์พร้อมกัน
- `['student_id', 'age']`: list ชื่อคอลัมน์ที่ต้องการ

พิมพ์คำสั่งและกดปุ่ม Shift + Enter เพื่อรันคำสั่งและตรวจสอบผลลัพธ์

In [13]:
df.loc[age_bad, ['student_id', 'age']]

  student_id    age
7       S008  150.0

### ผลลัพธ์และคำอธิบาย

| ลำดับแถว | student_id | age |
| --- | --- | --- |
| 7 | S008 | 150.0 |

แสดง S008 อายุ 150.0 เพียงแถวเดียว

**ข้อควรระวังในการเขียนคำสั่ง:** เกณฑ์นี้เป็นสัญญาณให้ตรวจต้นทาง ยังไม่ยืนยันอายุจริง

**คำถามตรวจสอบความเข้าใจ:** ระบุรหัสที่ควรตรวจสอบได้

## ขั้นตอนที่ 14: นับอายุผิดช่วง

นับรายการที่มีอายุอยู่นอกเกณฑ์

```python
age_bad.sum()
```

- `.sum()`: รวม True ในหน้ากาก

พิมพ์คำสั่งและกดปุ่ม Shift + Enter เพื่อรันคำสั่งและตรวจสอบผลลัพธ์

In [14]:
age_bad.sum()

1

### ผลลัพธ์และคำอธิบาย

```text
1
```

ได้ 1 โดยไม่รวมอายุว่าง

**ข้อควรระวังในการเขียนคำสั่ง:** อย่านับจาก ~age_valid โดยไม่แยกค่าว่าง

**คำถามตรวจสอบความเข้าใจ:** ได้ผล 1 และอธิบายตัวนับได้

## ขั้นตอนที่ 15: แยก GPA ที่มีค่า

ตรวจตำแหน่งที่ GPA ไม่ว่าง

```python
gpa_present = df['gpa'].notna()
gpa_present
```

- `.notna()`: ให้ True เมื่อมีค่า

พิมพ์คำสั่งและกดปุ่ม Shift + Enter เพื่อรันคำสั่งและตรวจสอบผลลัพธ์

In [15]:
gpa_present = df['gpa'].notna()
gpa_present

0      True
1      True
2      True
3     False
4      True
5      True
6      True
7      True
8      True
9      True
10     True
11     True
12     True
13     True
14     True
15     True
16     True
17     True
18     True
19     True
20     True
21     True
22    False
23     True
24     True
25     True
26     True
27     True
28     True
29     True
30     True
31     True
32     True
33     True
34     True
35     True
36     True
37     True
38     True
39     True
40     True
41     True
Name: gpa, dtype: bool

### ผลลัพธ์และคำอธิบาย

```text
0      True
1      True
2      True
3     False
4      True
5      True
6      True
      ...  
35     True
36     True
37     True
38     True
39     True
40     True
41     True
```

True 40 แถว และ False 2 แถว

**ข้อควรระวังในการเขียนคำสั่ง:** GPA ว่างไม่ใช่ 0.00

**คำถามตรวจสอบความเข้าใจ:** ยืนยันว่ามี GPA ว่าง 2 แถว

## ขั้นตอนที่ 16: ตรวจ GPA ในเกณฑ์

ตรวจ GPA ตามช่วง 0.00–4.00

```python
gpa_valid = df['gpa'].between(0, 4)
gpa_valid
```

- `.between(0, 4)`: รวมค่าขอบ 0 และ 4

พิมพ์คำสั่งและกดปุ่ม Shift + Enter เพื่อรันคำสั่งและตรวจสอบผลลัพธ์

In [16]:
gpa_valid = df['gpa'].between(0, 4)
gpa_valid

0      True
1      True
2      True
3     False
4      True
5      True
6      True
7      True
8      True
9      True
10     True
11     True
12     True
13     True
14     True
15     True
16     True
17     True
18    False
19     True
20     True
21     True
22    False
23     True
24     True
25     True
26     True
27     True
28     True
29     True
30     True
31     True
32     True
33     True
34     True
35     True
36     True
37     True
38     True
39     True
40     True
41     True
Name: gpa, dtype: bool

### ผลลัพธ์และคำอธิบาย

```text
0      True
1      True
2      True
3     False
4      True
5      True
6      True
      ...  
35     True
36     True
37     True
38     True
39     True
40     True
41     True
```

False 3 แถว: ค่าว่าง 2 แถว และ GPA 4.75 หนึ่งแถว

**ข้อควรระวังในการเขียนคำสั่ง:** ค่า 0 เป็นค่าที่อยู่ในเกณฑ์ ไม่ใช่ค่าว่าง

**คำถามตรวจสอบความเข้าใจ:** อธิบายเหตุผลที่ False มี 3 แถวได้

## ขั้นตอนที่ 17: สร้างหน้ากาก GPA ผิดช่วง

เลือก GPA ที่มีค่าและอยู่นอกเกณฑ์

```python
gpa_bad = ~gpa_valid & gpa_present
gpa_bad
```

- `~gpa_valid`: ไม่อยู่ในช่วง
- `& gpa_present`: และต้องมีค่า

พิมพ์คำสั่งและกดปุ่ม Shift + Enter เพื่อรันคำสั่งและตรวจสอบผลลัพธ์

In [17]:
gpa_bad = ~gpa_valid & gpa_present
gpa_bad

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18     True
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30    False
31    False
32    False
33    False
34    False
35    False
36    False
37    False
38    False
39    False
40    False
41    False
Name: gpa, dtype: bool

### ผลลัพธ์และคำอธิบาย

```text
0     False
1     False
2     False
3     False
4     False
5     False
6     False
      ...  
35    False
36    False
37    False
38    False
39    False
40    False
41    False
```

True 1 แถว; แถว GPA ว่างเป็น False

**ข้อควรระวังในการเขียนคำสั่ง:** ต้องใช้หน้ากากจาก df เดียวกัน

**คำถามตรวจสอบความเข้าใจ:** แยก GPA ว่างกับ GPA ผิดช่วงได้

## ขั้นตอนที่ 18: เปิดแถว GPA ผิดช่วง

แสดงหลักฐานของค่า GPA ผิดช่วง

```python
df.loc[gpa_bad, ['student_id', 'gpa']]
```

- `.loc[]`: เลือกแถวและคอลัมน์ตามที่ระบุ

พิมพ์คำสั่งและกดปุ่ม Shift + Enter เพื่อรันคำสั่งและตรวจสอบผลลัพธ์

In [18]:
df.loc[gpa_bad, ['student_id', 'gpa']]

   student_id   gpa
18       S019  4.75

### ผลลัพธ์และคำอธิบาย

| ลำดับแถว | student_id | gpa |
| --- | --- | --- |
| 18 | S019 | 4.75 |

แสดง S019 มี GPA 4.75

**ข้อควรระวังในการเขียนคำสั่ง:** ตรวจหลักฐานต้นทางก่อนแก้ค่า

**คำถามตรวจสอบความเข้าใจ:** ระบุ S019 และค่า 4.75 ได้

## ขั้นตอนที่ 19: นับ GPA ผิดช่วง

นับ GPA ที่มีค่าและอยู่นอกเกณฑ์

```python
gpa_bad.sum()
```

- `.sum()`: รวม True

พิมพ์คำสั่งและกดปุ่ม Shift + Enter เพื่อรันคำสั่งและตรวจสอบผลลัพธ์

In [19]:
gpa_bad.sum()

1

### ผลลัพธ์และคำอธิบาย

```text
1
```

ได้ 1; ค่าว่าง 2 แถวเป็นอีกปัญหาหนึ่ง

**ข้อควรระวังในการเขียนคำสั่ง:** อย่ารวมจำนวนปัญหาเป็นจำนวนผู้เรียนโดยไม่ตรวจการซ้อนกัน

**คำถามตรวจสอบความเข้าใจ:** รายงานได้ว่า GPA ผิดช่วง 1 และว่าง 2

## ขั้นตอนที่ 20: อ่านวันที่ต้นทาง

ตรวจตัวอย่างข้อความวันที่ก่อนเรียนการแปลงวันที่

```python
df['updated_date']
```

- `['updated_date']`: เลือกคอลัมน์วันที่ต้นทาง

พิมพ์คำสั่งและกดปุ่ม Shift + Enter เพื่อรันคำสั่งและตรวจสอบผลลัพธ์

In [20]:
df['updated_date']

0     2026-06-01
1     2026-06-09
2     2026-06-06
3     2026-06-04
4     2026-06-05
5     2026-06-08
6     2026-06-04
7     2026-06-01
8     2026-06-02
9     2026-06-07
10    2026-06-08
11    2026-06-01
12    2026-06-08
13    2026-06-01
14    2026-06-07
15    2026-06-09
16    2026-06-01
17    2026-06-07
18    2026-06-01
19    2026-06-03
20    2026-06-06
21    2026-06-09
22    2026-06-09
23    2026-06-09
24    2026-06-09
25    2026-06-09
26    2026-06-08
27    2026-06-05
28    2026-06-03
29    2026-06-07
30    2020-06-05
31    2026-06-02
32    2026-06-01
33    2020-06-02
34    2026-06-03
35    2026-06-07
36    2026-06-02
37    2026-06-05
38    2026-06-02
39    2026-06-07
40    2026-06-08
41    2026-06-06
Name: updated_date, dtype: object

### ผลลัพธ์และคำอธิบาย

```text
0     2026-06-01
1     2026-06-09
2     2026-06-06
3     2026-06-04
4     2026-06-05
5     2026-06-08
6     2026-06-04
         ...    
35    2026-06-07
36    2026-06-02
37    2026-06-05
38    2026-06-02
39    2026-06-07
40    2026-06-08
41    2026-06-06
```

เห็นข้อความวันที่ปี 2026 และ 2020; ยังไม่ใช่ผลตรวจความเป็นปัจจุบัน

**ข้อควรระวังในการเขียนคำสั่ง:** อย่าสรุปว่าเก่าหรือผิดโดยยังไม่มีวันอ้างอิงและเกณฑ์

**คำถามตรวจสอบความเข้าใจ:** บันทึกได้ว่าต้องมีวันอ้างอิงก่อนตรวจความเป็นปัจจุบัน

## สรุป

อธิบายคำสั่ง ผลลัพธ์ หน่วย และข้อจำกัด บันทึก Notebook สำหรับทบทวน