# W04 — ETL รายงานผลการตรวจสอบคุณภาพข้อมูล

## จุดประสงค์การเรียนรู้
- จัดทำรายงานจำนวน ร้อยละ และตัวหารได้
- สร้างตารางรายงานด้วย pd.DataFrame ได้
- ส่งออก CSV โดยรักษาชื่อคอลัมน์และดัชนีที่มีความหมายได้

## การเตรียมไฟล์ข้อมูล
- student_register_dirty.csv

อัปโหลดไฟล์ข้อมูลผ่านเมนู Files ในโปรแกรม Google Colab แล้วพิมพ์คำสั่งและรันผลลัพธ์ตามลำดับทีละขั้นตอน

## โครงสร้างชุดข้อมูล
- ไฟล์ student_register_dirty.csv: จำนวน 42 แถว 7 คอลัมน์ ได้แก่ student_id, name, major, age, gpa, phone, updated_date

## ขั้นตอนที่ 1: เรียกใช้ pandas

นำเข้าเครื่องมือจัดการตาราง และตั้งชื่อย่อว่า pd

```python
import pandas as pd
```

- `import`: นำเข้าไลบรารี
- `as pd`: กำหนดชื่อย่อสำหรับคำสั่งต่อไป

พิมพ์คำสั่งและกดปุ่ม Shift + Enter เพื่อรันคำสั่งและตรวจสอบผลลัพธ์

In [1]:
import pandas as pd

### ผลลัพธ์และคำอธิบาย

```text
รันคำสั่งสำเร็จ (ไม่มีข้อความแจ้งข้อผิดพลาด)
```

เมื่อสำเร็จจะไม่มีตารางปรากฏ และสามารถใช้ pd ได้

**ข้อควรระวังในการเขียนคำสั่ง:** เขียน pandas และ pd ด้วยตัวพิมพ์เล็ก

**คำถามตรวจสอบความเข้าใจ:** รันแล้วไม่มีข้อความผิดพลาด

## ขั้นตอนที่ 2: อ่านข้อมูลสำหรับรายงาน

อ่านข้อมูลต้นทางโดยยังไม่ทำความสะอาด

```python
df = pd.read_csv('student_register_dirty.csv', dtype={'phone': 'string'})
df
```

- `pd.read_csv`: อ่าน CSV
- `dtype`: รักษา phone เป็นข้อความ

พิมพ์คำสั่งและกดปุ่ม Shift + Enter เพื่อรันคำสั่งและตรวจสอบผลลัพธ์

In [2]:
df = pd.read_csv('student_register_dirty.csv', dtype={'phone': 'string'})
df

   student_id            name  ...       phone  updated_date
0        S001     สมชาย สุขสม  ...  0882903368    2026-06-01
1        S002     อรุณ ศรีสุข  ...  0845046288    2026-06-09
2        S003     วรรณา สุขสม  ...  0877470852    2026-06-06
3        S004       ชัย สุขสม  ...  0863778945    2026-06-04
4        S005      กมล ศรีสุข  ...  0813749650    2026-06-05
5        S006      ศิริ ทองคำ  ...  0856208603    2026-06-08
6        S007      อรุณ บุญมา  ...  0823711300    2026-06-04
7        S008      ศิริ สุขสม  ...  0891907998    2026-06-01
8        S009      ศิริ บุญมา  ...  0898662305    2026-06-02
9        S010    ภูมิ แก้วมณี  ...  0833960779    2026-06-07
10       S011      อรุณ บุญมา  ...  0863128543    2026-06-08
11       S012       ธนา บุญมา  ...  0827050801    2026-06-01
12       S013   อนันต์ ศรีสุข  ...  0889976351    2026-06-08
13       S014       ชัย ทองคำ  ...  0812871813    2026-06-01
14       S015      อรุณ บุญมา  ...  0828689916    2026-06-07
15       S016      จิรา สุขสม  ...        <NA>    2026-06-09
16       S017      กมล ศรีสุข  ...  0827592411    2026-06-01
17       S018      ภูมิ บุญมา  ...  0879358465    2026-06-07
18       S019     จิรา ศรีสุข  ...  0878524460    2026-06-01
19       S020    จิรา แก้วมณี  ...  0830106149    2026-06-03
20       S021  อนันต์ แก้วมณี  ...  0818288654    2026-06-06
21       S022      ชัย ศรีสุข  ...  0824241764    2026-06-09
22       S023     สมชาย สุขสม  ...  0823119148    2026-06-09
23       S024     ศิริ ศรีสุข  ...  0892212100    2026-06-09
24       S025       พร ศรีสุข  ...  0878203564    2026-06-09
25       S026    อรุณ แก้วมณี  ...        0812    2026-06-09
26       S027      ภูมิ สุขสม  ...  0862662255    2026-06-08
27       S028      วรรณา ใจดี  ...  0838546741    2026-06-05
28       S029       อรุณ ใจดี  ...  0859148289    2026-06-03
29       S030      ปิยะ สุขสม  ...  0822633303    2026-06-07
30       S031    ภูมิ แก้วมณี  ...  0831671607    2020-06-05
31       S032     ณัฐ แก้วมณี  ...  0852751778    2026-06-02
32       S033      มาลี ทองคำ  ...  0869117285    2026-06-01
33       S034       ธนา ทองคำ  ...  0818628964    2020-06-02
34       S035      ภูมิ สุขสม  ...  0815313436    2026-06-03
35       S036      ปิยะ สุขสม  ...  0844709914    2026-06-07
36       S037   อนันต์ ศรีสุข  ...  0853895707    2026-06-02
37       S038       ปิยะ ใจดี  ...  0819719255    2026-06-05
38       S039     สมชาย บุญมา  ...  0839851095    2026-06-02
39       S040       ปิยะ ใจดี  ...  0884231009    2026-06-07
40       S006      ศิริ ทองคำ  ...  0856208603    2026-06-08
41       S021  อนันต์ แก้วมณี  ...  0818288654    2026-06-06

[42 rows x 7 columns]

### ผลลัพธ์และคำอธิบาย

| ลำดับแถว | student_id | name | major | age | gpa | phone | updated_date |
| --- | --- | --- | --- | --- | --- | --- | --- |
| 0 | S001 | สมชาย สุขสม | การตลาด | 19.0 | 2.11 | 0882903368 | 2026-06-01 |
| 1 | S002 | อรุณ ศรีสุข | คอมพิวเตอร์ธุรกิจ | 22.0 | 3.61 | 0845046288 | 2026-06-09 |
| 2 | S003 | วรรณา สุขสม | คอมพิวเตอร์ธุรกิจ | 18.0 | 2.92 | 0877470852 | 2026-06-06 |
| 3 | S004 | ชัย สุขสม | การตลาด | 18.0 | ว่าง | 0863778945 | 2026-06-04 |
| 4 | S005 | กมล ศรีสุข | คอมพิวเตอร์ธุรกิจ | 19.0 | 3.34 | 0813749650 | 2026-06-05 |
| 5 | S006 | ศิริ ทองคำ | เทคโนโลยีสารสนเทศ | 22.0 | 3.07 | 0856208603 | 2026-06-08 |
| 6 | S007 | อรุณ บุญมา | คอมพิวเตอร์ธุรกิจ | 19.0 | 1.97 | 0823711300 | 2026-06-04 |
| 7 | S008 | ศิริ สุขสม | คอมพิวเตอร์ธุรกิจ | 150.0 | 2.81 | 0891907998 | 2026-06-01 |
| 8 | S009 | ศิริ บุญมา | คอมพิวเตอร์ธุรกิจ | 22.0 | 1.98 | 0898662305 | 2026-06-02 |
| 9 | S010 | ภูมิ แก้วมณี | การตลาด | 18.0 | 2.8 | 0833960779 | 2026-06-07 |

ตารางมี 42 แถว 7 คอลัมน์

**ข้อควรระวังในการเขียนคำสั่ง:** ต้องใช้ไฟล์ dirty เพื่อรายงานก่อนแก้

**คำถามตรวจสอบความเข้าใจ:** จำนวนแถวยังเป็น 42

## ขั้นตอนที่ 3: ทบทวนส่วนต้นของข้อมูล

ตรวจว่าใช้ข้อมูลชุดเดียวกับสัปดาห์ก่อน

```python
df.head()
```

- `.head()`: แสดงห้าแถวแรก

พิมพ์คำสั่งและกดปุ่ม Shift + Enter เพื่อรันคำสั่งและตรวจสอบผลลัพธ์

In [3]:
df.head()

  student_id         name              major  ...   gpa       phone updated_date
0       S001  สมชาย สุขสม            การตลาด  ...  2.11  0882903368   2026-06-01
1       S002  อรุณ ศรีสุข  คอมพิวเตอร์ธุรกิจ  ...  3.61  0845046288   2026-06-09
2       S003  วรรณา สุขสม  คอมพิวเตอร์ธุรกิจ  ...  2.92  0877470852   2026-06-06
3       S004    ชัย สุขสม            การตลาด  ...   NaN  0863778945   2026-06-04
4       S005   กมล ศรีสุข  คอมพิวเตอร์ธุรกิจ  ...  3.34  0813749650   2026-06-05

[5 rows x 7 columns]

### ผลลัพธ์และคำอธิบาย

| ลำดับแถว | student_id | name | major | age | gpa | phone | updated_date |
| --- | --- | --- | --- | --- | --- | --- | --- |
| 0 | S001 | สมชาย สุขสม | การตลาด | 19.0 | 2.11 | 0882903368 | 2026-06-01 |
| 1 | S002 | อรุณ ศรีสุข | คอมพิวเตอร์ธุรกิจ | 22.0 | 3.61 | 0845046288 | 2026-06-09 |
| 2 | S003 | วรรณา สุขสม | คอมพิวเตอร์ธุรกิจ | 18.0 | 2.92 | 0877470852 | 2026-06-06 |
| 3 | S004 | ชัย สุขสม | การตลาด | 18.0 | ว่าง | 0863778945 | 2026-06-04 |
| 4 | S005 | กมล ศรีสุข | คอมพิวเตอร์ธุรกิจ | 19.0 | 3.34 | 0813749650 | 2026-06-05 |

เห็น S001–S005 และ GPA ว่างของ S004

**ข้อควรระวังในการเขียนคำสั่ง:** การแสดงห้าแถวไม่ใช่การเลือกใช้เพียงห้าแถวในการรายงาน

**คำถามตรวจสอบความเข้าใจ:** พบค่าว่างของ S004

## ขั้นตอนที่ 4: กำหนดตัวหาร

เก็บจำนวนแถวต้นทางสำหรับคำนวณร้อยละ

```python
row_count = len(df)
row_count
```

- `len(df)`: จำนวนแถวในตาราง
- `row_count`: ตัวหารที่ใช้ทั้งรายงาน

พิมพ์คำสั่งและกดปุ่ม Shift + Enter เพื่อรันคำสั่งและตรวจสอบผลลัพธ์

In [4]:
row_count = len(df)
row_count

42

### ผลลัพธ์และคำอธิบาย

```text
42
```

ได้ 42 ซึ่งรวมสำเนาซ้ำด้วย

**ข้อควรระวังในการเขียนคำสั่ง:** รายงานนี้ใช้ 42 แถวเป็นตัวหาร ไม่ใช่จำนวนผู้เรียนไม่ซ้ำ

**คำถามตรวจสอบความเข้าใจ:** อธิบายตัวหาร 42 ได้

## ขั้นตอนที่ 5: ทบทวนตารางค่าว่าง

สร้างหน้ากากค่าว่างและดูส่วนต้น

```python
missing = df.isna()
missing.head()
```

- `.isna()`: ตรวจค่าว่างทุกคอลัมน์
- `.head()`: แสดงตัวอย่างห้าแถว

พิมพ์คำสั่งและกดปุ่ม Shift + Enter เพื่อรันคำสั่งและตรวจสอบผลลัพธ์

In [5]:
missing = df.isna()
missing.head()

   student_id   name  major    age    gpa  phone  updated_date
0       False  False  False  False  False  False         False
1       False  False  False  False  False  False         False
2       False  False  False  False  False  False         False
3       False  False  False  False   True  False         False
4       False  False  False  False  False  False         False

### ผลลัพธ์และคำอธิบาย

| ลำดับแถว | student_id | name | major | age | gpa | phone | updated_date |
| --- | --- | --- | --- | --- | --- | --- | --- |
| 0 | False | False | False | False | False | False | False |
| 1 | False | False | False | False | False | False | False |
| 2 | False | False | False | False | False | False | False |
| 3 | False | False | False | False | True | False | False |
| 4 | False | False | False | False | False | False | False |

เห็น True ที่ gpa ของ S004; missing ยังมีหน้ากากครบ 42 แถว

**ข้อควรระวังในการเขียนคำสั่ง:** head ใช้ตรวจตัวอย่าง ไม่ได้ลดข้อมูลใน missing

**คำถามตรวจสอบความเข้าใจ:** บอกได้ว่าการนับถัดไปใช้ครบทุกแถว

## ขั้นตอนที่ 6: คำนวณจำนวนค่าว่าง

นับค่าว่างแต่ละคอลัมน์

```python
missing_count = missing.sum()
missing_count
```

- `.sum()`: รวม True แยกตามคอลัมน์

พิมพ์คำสั่งและกดปุ่ม Shift + Enter เพื่อรันคำสั่งและตรวจสอบผลลัพธ์

In [6]:
missing_count = missing.sum()
missing_count

student_id      0
name            0
major           0
age             1
gpa             2
phone           1
updated_date    0
dtype: int64

### ผลลัพธ์และคำอธิบาย

```text
student_id      0
name            0
major           0
age             1
gpa             2
phone           1
updated_date    0
```

age 1, gpa 2, phone 1; คอลัมน์อื่น 0

**ข้อควรระวังในการเขียนคำสั่ง:** อย่าสับสนค่าว่างกับค่าผิดช่วง

**คำถามตรวจสอบความเข้าใจ:** อ่านจำนวนทั้งสามได้

## ขั้นตอนที่ 7: คำนวณร้อยละค่าว่าง

ใช้จำนวนปัญหาหารจำนวนแถว แล้วคูณ 100

```python
missing_percent = missing_count / row_count * 100
missing_percent
```

- `/ row_count`: หารด้วยจำนวนแถวต้นทาง
- `* 100`: เปลี่ยนสัดส่วนเป็นร้อยละ

พิมพ์คำสั่งและกดปุ่ม Shift + Enter เพื่อรันคำสั่งและตรวจสอบผลลัพธ์

In [7]:
missing_percent = missing_count / row_count * 100
missing_percent

student_id      0.000000
name            0.000000
major           0.000000
age             2.380952
gpa             4.761905
phone           2.380952
updated_date    0.000000
dtype: float64

### ผลลัพธ์และคำอธิบาย

```text
student_id      0.000000
name            0.000000
major           0.000000
age             2.380952
gpa             4.761905
phone           2.380952
updated_date    0.000000
```

age และ phone ประมาณ 2.380952%; gpa ประมาณ 4.761905%; คอลัมน์อื่น 0%

**ข้อควรระวังในการเขียนคำสั่ง:** ไม่คูณ 100 ซ้ำ และระบุว่าตัวหารคือ 42 แถว

**คำถามตรวจสอบความเข้าใจ:** อธิบายได้ว่า gpa คือ 2 ÷ 42 × 100

## ขั้นตอนที่ 8: สร้างตารางรายงานค่าว่าง

รวม Series จำนวนและร้อยละเป็น DataFrame

```python
quality = pd.DataFrame({'missing_count': missing_count, 'missing_percent': missing_percent})
quality
```

- `pd.DataFrame`: สร้างตารางจาก dict
- `missing_count, missing_percent`: Series ที่มีชื่อคอลัมน์ต้นทางเป็นดัชนี

พิมพ์คำสั่งและกดปุ่ม Shift + Enter เพื่อรันคำสั่งและตรวจสอบผลลัพธ์

In [8]:
quality = pd.DataFrame({'missing_count': missing_count, 'missing_percent': missing_percent})
quality

              missing_count  missing_percent
student_id                0         0.000000
name                      0         0.000000
major                     0         0.000000
age                       1         2.380952
gpa                       2         4.761905
phone                     1         2.380952
updated_date              0         0.000000

### ผลลัพธ์และคำอธิบาย

| ลำดับแถว | missing_count | missing_percent |
| --- | --- | --- |
| student_id | 0.0 | 0.0 |
| name | 0.0 | 0.0 |
| major | 0.0 | 0.0 |
| age | 1.0 | 2.380952380952381 |
| gpa | 2.0 | 4.761904761904762 |
| phone | 1.0 | 2.380952380952381 |
| updated_date | 0.0 | 0.0 |

ได้ 7 แถว 2 คอลัมน์; ดัชนีคือชื่อคอลัมน์ต้นทาง เช่น age และ gpa

**ข้อควรระวังในการเขียนคำสั่ง:** ดัชนีชื่อคอลัมน์มีความหมาย ต้องรักษาไว้ตอนส่งออก

**คำถามตรวจสอบความเข้าใจ:** พบแถว gpa จำนวน 2 และร้อยละประมาณ 4.76

## ขั้นตอนที่ 9: บันทึกรายงานค่าว่าง

บันทึกรายงานและตั้งชื่อดัชนีใน CSV ว่า column

```python
quality.to_csv('quality_report.csv', index_label='column', encoding='utf-8-sig')
```

- `.to_csv`: เขียนตารางเป็นไฟล์ CSV
- `index_label='column'`: เก็บดัชนีที่เป็นชื่อคอลัมน์ต้นทาง พร้อมหัวชื่อ
- `encoding='utf-8-sig'`: การเข้ารหัสที่สะดวกต่อการเปิดข้อความไทยใน Excel

พิมพ์คำสั่งและกดปุ่ม Shift + Enter เพื่อรันคำสั่งและตรวจสอบผลลัพธ์

In [9]:
quality.to_csv('quality_report.csv', index_label='column', encoding='utf-8-sig')

### ผลลัพธ์และคำอธิบาย

```text
รันคำสั่งสำเร็จ (ไม่มีข้อความแจ้งข้อผิดพลาด)
```

เซลล์ไม่มีตารางแสดง; สร้างไฟล์ quality_report.csv ที่มี column, missing_count และ missing_percent

**ข้อควรระวังในการเขียนคำสั่ง:** ห้ามใช้ index=False ในรายงานนี้ เพราะจะทำชื่อคอลัมน์ต้นทางหาย

**คำถามตรวจสอบความเข้าใจ:** พบไฟล์ quality_report.csv ในแถบ Files

## ขั้นตอนที่ 10: เปิดไฟล์รายงานเพื่อตรวจ

อ่านรายงานที่เพิ่งบันทึกเพื่อตรวจความครบถ้วน

```python
quality_saved = pd.read_csv('quality_report.csv')
quality_saved
```

- `pd.read_csv`: อ่าน CSV ที่สร้างแล้ว

พิมพ์คำสั่งและกดปุ่ม Shift + Enter เพื่อรันคำสั่งและตรวจสอบผลลัพธ์

In [10]:
quality_saved = pd.read_csv('quality_report.csv')
quality_saved

         column  missing_count  missing_percent
0    student_id              0         0.000000
1          name              0         0.000000
2         major              0         0.000000
3           age              1         2.380952
4           gpa              2         4.761905
5         phone              1         2.380952
6  updated_date              0         0.000000

### ผลลัพธ์และคำอธิบาย

| ลำดับแถว | column | missing_count | missing_percent |
| --- | --- | --- | --- |
| 0 | student_id | 0 | 0.0 |
| 1 | name | 0 | 0.0 |
| 2 | major | 0 | 0.0 |
| 3 | age | 1 | 2.380952380952381 |
| 4 | gpa | 2 | 4.761904761904762 |
| 5 | phone | 1 | 2.380952380952381 |
| 6 | updated_date | 0 | 0.0 |

ตารางมี 7 แถว 3 คอลัมน์; column เก็บชื่อ student_id ถึง updated_date

**ข้อควรระวังในการเขียนคำสั่ง:** หากหาไฟล์ไม่พบ ต้องรันเซลล์บันทึกก่อน

**คำถามตรวจสอบความเข้าใจ:** พบ column ชื่อ gpa และจำนวน 2

## ขั้นตอนที่ 11: นับสำเนาซ้ำสำหรับรายงาน

ทบทวนการนับสำเนาซ้ำทั้งหมด

```python
duplicate_count = df.duplicated().sum()
duplicate_count
```

- `.duplicated()`: หน้ากากสำเนาซ้ำ
- `.sum()`: จำนวน True

พิมพ์คำสั่งและกดปุ่ม Shift + Enter เพื่อรันคำสั่งและตรวจสอบผลลัพธ์

In [11]:
duplicate_count = df.duplicated().sum()
duplicate_count

2

### ผลลัพธ์และคำอธิบาย

```text
2
```

ได้ 2; เป็นจำนวนสำเนาที่เกินจากรายการแรก

**ข้อควรระวังในการเขียนคำสั่ง:** ยังไม่ลบแถวซ้ำก่อนจัดทำรายงานต้นทาง

**คำถามตรวจสอบความเข้าใจ:** จำนวนตรงกับผลสัปดาห์ที่ 3

## ขั้นตอนที่ 12: ทบทวนช่วงอายุ

ตรวจอายุในเกณฑ์เดิมเพื่อให้รายงานเปรียบเทียบกันได้

```python
age_valid = df['age'].between(15, 60)
age_valid
```

- `.between(15, 60)`: ช่วงรวมขอบ 15 และ 60

พิมพ์คำสั่งและกดปุ่ม Shift + Enter เพื่อรันคำสั่งและตรวจสอบผลลัพธ์

In [12]:
age_valid = df['age'].between(15, 60)
age_valid

0      True
1      True
2      True
3      True
4      True
5      True
6      True
7     False
8      True
9      True
10    False
11     True
12     True
13     True
14     True
15     True
16     True
17     True
18     True
19     True
20     True
21     True
22     True
23     True
24     True
25     True
26     True
27     True
28     True
29     True
30     True
31     True
32     True
33     True
34     True
35     True
36     True
37     True
38     True
39     True
40     True
41     True
Name: age, dtype: bool

### ผลลัพธ์และคำอธิบาย

```text
0     True
1     True
2     True
3     True
4     True
5     True
6     True
      ... 
35    True
36    True
37    True
38    True
39    True
40    True
41    True
```

False มี 2 ตำแหน่ง รวมทั้งอายุว่าง

**ข้อควรระวังในการเขียนคำสั่ง:** False ยังไม่ใช่จำนวนค่าผิดช่วง

**คำถามตรวจสอบความเข้าใจ:** จำได้ว่าต้องตัดค่าว่างออกจากการนับผิดช่วง

---

# วันอังคาร

## ขั้นตอนที่ 13: แยกอายุผิดช่วง

ใช้หน้ากากนอกช่วงร่วมกับหน้ากากมีค่า

```python
age_bad = ~age_valid & df['age'].notna()
age_bad
```

- `~age_valid`: ไม่อยู่ในช่วง
- `.notna()`: มีค่า
- `&`: ทั้งสองเงื่อนไขต้องเป็น True

พิมพ์คำสั่งและกดปุ่ม Shift + Enter เพื่อรันคำสั่งและตรวจสอบผลลัพธ์

In [13]:
age_bad = ~age_valid & df['age'].notna()
age_bad

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7      True
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30    False
31    False
32    False
33    False
34    False
35    False
36    False
37    False
38    False
39    False
40    False
41    False
Name: age, dtype: bool

### ผลลัพธ์และคำอธิบาย

```text
0     False
1     False
2     False
3     False
4     False
5     False
6     False
      ...  
35    False
36    False
37    False
38    False
39    False
40    False
41    False
```

True 1 แถว คือ S008; อายุว่างไม่ถูกนับ

**ข้อควรระวังในการเขียนคำสั่ง:** เขียน & สำหรับหน้ากาก ไม่ใช้ and

**คำถามตรวจสอบความเข้าใจ:** หน้ากากระบุค่าผิดช่วงเพียง 1 แถว

## ขั้นตอนที่ 14: นับอายุผิดช่วง

เก็บจำนวนอายุผิดช่วงเพื่อสร้างรายงาน

```python
age_count = age_bad.sum()
age_count
```

- `.sum()`: นับ True

พิมพ์คำสั่งและกดปุ่ม Shift + Enter เพื่อรันคำสั่งและตรวจสอบผลลัพธ์

In [14]:
age_count = age_bad.sum()
age_count

1

### ผลลัพธ์และคำอธิบาย

```text
1
```

ได้ 1

**ข้อควรระวังในการเขียนคำสั่ง:** ต้องใช้ age_bad ไม่ใช้ age_valid

**คำถามตรวจสอบความเข้าใจ:** ได้จำนวน 1

## ขั้นตอนที่ 15: ทบทวนช่วง GPA

ตรวจ GPA ด้วยเกณฑ์ 0.00–4.00

```python
gpa_valid = df['gpa'].between(0, 4)
gpa_valid
```

- `.between(0, 4)`: ช่วง GPA ที่ยอมรับในโจทย์

พิมพ์คำสั่งและกดปุ่ม Shift + Enter เพื่อรันคำสั่งและตรวจสอบผลลัพธ์

In [15]:
gpa_valid = df['gpa'].between(0, 4)
gpa_valid

0      True
1      True
2      True
3     False
4      True
5      True
6      True
7      True
8      True
9      True
10     True
11     True
12     True
13     True
14     True
15     True
16     True
17     True
18    False
19     True
20     True
21     True
22    False
23     True
24     True
25     True
26     True
27     True
28     True
29     True
30     True
31     True
32     True
33     True
34     True
35     True
36     True
37     True
38     True
39     True
40     True
41     True
Name: gpa, dtype: bool

### ผลลัพธ์และคำอธิบาย

```text
0      True
1      True
2      True
3     False
4      True
5      True
6      True
      ...  
35     True
36     True
37     True
38     True
39     True
40     True
41     True
```

False 3 ตำแหน่ง รวมค่าว่าง 2 แถว

**ข้อควรระวังในการเขียนคำสั่ง:** ยังต้องแยกค่าว่างก่อนนับค่าผิดช่วง

**คำถามตรวจสอบความเข้าใจ:** ระบุได้ว่า False รวมหลายสาเหตุ

## ขั้นตอนที่ 16: แยก GPA ผิดช่วง

แยกค่า GPA ที่มีค่าและอยู่นอกเกณฑ์

```python
gpa_bad = ~gpa_valid & df['gpa'].notna()
gpa_bad
```

- `~`: กลับหน้ากากในช่วง
- `&`: ใช้ทั้งสองเงื่อนไข
- `.notna()`: ตัดค่าว่างออกจากการนับผิดช่วง

พิมพ์คำสั่งและกดปุ่ม Shift + Enter เพื่อรันคำสั่งและตรวจสอบผลลัพธ์

In [16]:
gpa_bad = ~gpa_valid & df['gpa'].notna()
gpa_bad

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18     True
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30    False
31    False
32    False
33    False
34    False
35    False
36    False
37    False
38    False
39    False
40    False
41    False
Name: gpa, dtype: bool

### ผลลัพธ์และคำอธิบาย

```text
0     False
1     False
2     False
3     False
4     False
5     False
6     False
      ...  
35    False
36    False
37    False
38    False
39    False
40    False
41    False
```

True 1 แถว คือ S019

**ข้อควรระวังในการเขียนคำสั่ง:** หน้ากากต้องมาจาก df ที่ยังไม่ได้แก้ข้อมูล

**คำถามตรวจสอบความเข้าใจ:** แยกผิดช่วง 1 จากค่าว่าง 2 ได้

## ขั้นตอนที่ 17: นับ GPA ผิดช่วง

เก็บจำนวน GPA ผิดช่วง

```python
gpa_count = gpa_bad.sum()
gpa_count
```

- `.sum()`: นับ True

พิมพ์คำสั่งและกดปุ่ม Shift + Enter เพื่อรันคำสั่งและตรวจสอบผลลัพธ์

In [17]:
gpa_count = gpa_bad.sum()
gpa_count

1

### ผลลัพธ์และคำอธิบาย

```text
1
```

ได้ 1

**ข้อควรระวังในการเขียนคำสั่ง:** ใช้ gpa_bad เพื่อไม่นับค่าว่างปน

**คำถามตรวจสอบความเข้าใจ:** ได้จำนวน 1

## ขั้นตอนที่ 18: สร้างรายงานปัญหาอื่น

สร้างตารางชนิดปัญหา จำนวน และตัวหาร

```python
issue_report = pd.DataFrame({
    'issue': ['สำเนาซ้ำทั้งแถว', 'อายุผิดช่วง', 'GPA ผิดช่วง'],
    'count': [duplicate_count, age_count, gpa_count],
    'denominator': [row_count, row_count, row_count]
})
issue_report
```

- `{}`: dict จับหัวคอลัมน์กับ list
- `[]`: แต่ละ list มีสามสมาชิกตามลำดับปัญหา

พิมพ์คำสั่งและกดปุ่ม Shift + Enter เพื่อรันคำสั่งและตรวจสอบผลลัพธ์

In [18]:
issue_report = pd.DataFrame({
    'issue': ['สำเนาซ้ำทั้งแถว', 'อายุผิดช่วง', 'GPA ผิดช่วง'],
    'count': [duplicate_count, age_count, gpa_count],
    'denominator': [row_count, row_count, row_count]
})
issue_report

             issue  count  denominator
0  สำเนาซ้ำทั้งแถว      2           42
1      อายุผิดช่วง      1           42
2      GPA ผิดช่วง      1           42

### ผลลัพธ์และคำอธิบาย

| ลำดับแถว | issue | count | denominator |
| --- | --- | --- | --- |
| 0 | สำเนาซ้ำทั้งแถว | 2 | 42 |
| 1 | อายุผิดช่วง | 1 | 42 |
| 2 | GPA ผิดช่วง | 1 | 42 |

ได้สามแถว จำนวน 2, 1 และ 1; ตัวหารทุกแถวเป็น 42

**ข้อควรระวังในการเขียนคำสั่ง:** ต้องเรียงจำนวนให้ตรงกับชื่อปัญหา

**คำถามตรวจสอบความเข้าใจ:** อ่านจำนวนและตัวหารของแต่ละแถวได้

## ขั้นตอนที่ 19: เพิ่มร้อยละในรายงาน

คำนวณร้อยละแยกตามแถวของรายงาน

```python
issue_report['percent'] = issue_report['count'] / issue_report['denominator'] * 100
issue_report
```

- `['percent']`: คอลัมน์ใหม่สำหรับร้อยละ
- `/ และ *`: หารตัวหารแล้วคูณ 100

พิมพ์คำสั่งและกดปุ่ม Shift + Enter เพื่อรันคำสั่งและตรวจสอบผลลัพธ์

In [19]:
issue_report['percent'] = issue_report['count'] / issue_report['denominator'] * 100
issue_report

             issue  count  denominator   percent
0  สำเนาซ้ำทั้งแถว      2           42  4.761905
1      อายุผิดช่วง      1           42  2.380952
2      GPA ผิดช่วง      1           42  2.380952

### ผลลัพธ์และคำอธิบาย

| ลำดับแถว | issue | count | denominator | percent |
| --- | --- | --- | --- | --- |
| 0 | สำเนาซ้ำทั้งแถว | 2 | 42 | 4.761904761904762 |
| 1 | อายุผิดช่วง | 1 | 42 | 2.380952380952381 |
| 2 | GPA ผิดช่วง | 1 | 42 | 2.380952380952381 |

สำเนาซ้ำประมาณ 4.761905%; อายุและ GPA ผิดช่วงอย่างละ 2.380952%

**ข้อควรระวังในการเขียนคำสั่ง:** ร้อยละปัญหาอาจซ้อนกัน ห้ามบวกเป็นร้อยละผู้เรียนที่มีปัญหาทันที

**คำถามตรวจสอบความเข้าใจ:** อธิบาย 1 ÷ 42 × 100 ได้

## ขั้นตอนที่ 20: บันทึกรายงานชนิดปัญหา

บันทึกรายงานที่มีชื่อปัญหาอยู่ในคอลัมน์แล้ว

```python
issue_report.to_csv('quality_issues.csv', index=False, encoding='utf-8-sig')
```

- `index=False`: ไม่บันทึกเลขดัชนี 0, 1, 2 ที่ไม่มีความหมายในรายงาน
- `.to_csv`: สร้างไฟล์ CSV

พิมพ์คำสั่งและกดปุ่ม Shift + Enter เพื่อรันคำสั่งและตรวจสอบผลลัพธ์

In [20]:
issue_report.to_csv('quality_issues.csv', index=False, encoding='utf-8-sig')

### ผลลัพธ์และคำอธิบาย

```text
รันคำสั่งสำเร็จ (ไม่มีข้อความแจ้งข้อผิดพลาด)
```

เซลล์ไม่มีตารางแสดง; สร้าง quality_issues.csv มี issue, count, denominator และ percent

**ข้อควรระวังในการเขียนคำสั่ง:** รายงานนี้ใช้ index=False ได้ เพราะชื่อปัญหาอยู่ใน issue แล้ว

**คำถามตรวจสอบความเข้าใจ:** พบไฟล์ทั้ง quality_report.csv และ quality_issues.csv

## สรุป

อธิบายคำสั่ง ผลลัพธ์ หน่วย และข้อจำกัด บันทึก Notebook สำหรับทบทวน