# W05 — ETL ทำความสะอาดและลดความเสี่ยงข้อมูล

## เป้าหมาย
- ทำความสะอาดสำเนาโดยรักษาข้อมูลต้นทางได้
- แก้รูปแบบข้อความ แถวซ้ำ และค่าผิดช่วงอย่างมีเหตุผลได้
- แปลงวันที่ บันทึกการเปลี่ยน และเผยแพร่เฉพาะข้อมูลสรุปที่ไม่ระบุตัวบุคคลได้

## เตรียมไฟล์
- student_register_dirty.csv

อัปโหลดไฟล์ผ่าน Files ใน Colab ผู้สอนและผู้เรียนเขียนคำสั่งพร้อมกันทีละขั้น ใช้หนึ่งเซลล์ต่อขั้น และตรวจผลก่อนทำต่อ

## โครงสร้างข้อมูล
- student_register_dirty.csv: 42 แถว 7 คอลัมน์ — student_id, name, major, age, gpa, phone, updated_date

## ขั้นที่ 1: เรียกใช้ pandas

นำเข้าเครื่องมือจัดการตาราง และตั้งชื่อย่อว่า pd

```python
import pandas as pd
```

- `import`: นำเข้าไลบรารี
- `as pd`: กำหนดชื่อย่อสำหรับคำสั่งต่อไป

เขียนคำสั่งและกด Shift + Enter ก่อนอ่านผลด้านล่าง

In [1]:
import pandas as pd

### การตรวจผล

```text
ไม่มีผลลัพธ์แสดงใต้เซลล์ และไม่มีข้อความผิดพลาด
```

เมื่อสำเร็จจะไม่มีตารางปรากฏ และสามารถใช้ pd ได้

**เมื่อเกิดข้อผิดพลาด:** เขียน pandas และ pd ด้วยตัวพิมพ์เล็ก

**ตรวจความเข้าใจ:** รันแล้วไม่มีข้อความผิดพลาด

## ขั้นที่ 2: อ่านข้อมูลต้นทาง

อ่านต้นทางและรักษาหมายเลขโทรศัพท์เป็นข้อความ

```python
df = pd.read_csv('student_register_dirty.csv', dtype={'phone': 'string'})
df
```

- `dtype`: กำหนดชนิดขณะอ่าน
- `'string'`: ข้อความที่รักษาศูนย์นำหน้า

เขียนคำสั่งและกด Shift + Enter ก่อนอ่านผลด้านล่าง

In [2]:
df = pd.read_csv('student_register_dirty.csv', dtype={'phone': 'string'})
df

   student_id            name  ...       phone  updated_date
0        S001     สมชาย สุขสม  ...  0882903368    2026-06-01
1        S002     อรุณ ศรีสุข  ...  0845046288    2026-06-09
2        S003     วรรณา สุขสม  ...  0877470852    2026-06-06
3        S004       ชัย สุขสม  ...  0863778945    2026-06-04
4        S005      กมล ศรีสุข  ...  0813749650    2026-06-05
5        S006      ศิริ ทองคำ  ...  0856208603    2026-06-08
6        S007      อรุณ บุญมา  ...  0823711300    2026-06-04
7        S008      ศิริ สุขสม  ...  0891907998    2026-06-01
8        S009      ศิริ บุญมา  ...  0898662305    2026-06-02
9        S010    ภูมิ แก้วมณี  ...  0833960779    2026-06-07
10       S011      อรุณ บุญมา  ...  0863128543    2026-06-08
11       S012       ธนา บุญมา  ...  0827050801    2026-06-01
12       S013   อนันต์ ศรีสุข  ...  0889976351    2026-06-08
13       S014       ชัย ทองคำ  ...  0812871813    2026-06-01
14       S015      อรุณ บุญมา  ...  0828689916    2026-06-07
15       S016      จิรา สุขสม  ...        <NA>    2026-06-09
16       S017      กมล ศรีสุข  ...  0827592411    2026-06-01
17       S018      ภูมิ บุญมา  ...  0879358465    2026-06-07
18       S019     จิรา ศรีสุข  ...  0878524460    2026-06-01
19       S020    จิรา แก้วมณี  ...  0830106149    2026-06-03
20       S021  อนันต์ แก้วมณี  ...  0818288654    2026-06-06
21       S022      ชัย ศรีสุข  ...  0824241764    2026-06-09
22       S023     สมชาย สุขสม  ...  0823119148    2026-06-09
23       S024     ศิริ ศรีสุข  ...  0892212100    2026-06-09
24       S025       พร ศรีสุข  ...  0878203564    2026-06-09
25       S026    อรุณ แก้วมณี  ...        0812    2026-06-09
26       S027      ภูมิ สุขสม  ...  0862662255    2026-06-08
27       S028      วรรณา ใจดี  ...  0838546741    2026-06-05
28       S029       อรุณ ใจดี  ...  0859148289    2026-06-03
29       S030      ปิยะ สุขสม  ...  0822633303    2026-06-07
30       S031    ภูมิ แก้วมณี  ...  0831671607    2020-06-05
31       S032     ณัฐ แก้วมณี  ...  0852751778    2026-06-02
32       S033      มาลี ทองคำ  ...  0869117285    2026-06-01
33       S034       ธนา ทองคำ  ...  0818628964    2020-06-02
34       S035      ภูมิ สุขสม  ...  0815313436    2026-06-03
35       S036      ปิยะ สุขสม  ...  0844709914    2026-06-07
36       S037   อนันต์ ศรีสุข  ...  0853895707    2026-06-02
37       S038       ปิยะ ใจดี  ...  0819719255    2026-06-05
38       S039     สมชาย บุญมา  ...  0839851095    2026-06-02
39       S040       ปิยะ ใจดี  ...  0884231009    2026-06-07
40       S006      ศิริ ทองคำ  ...  0856208603    2026-06-08
41       S021  อนันต์ แก้วมณี  ...  0818288654    2026-06-06

[42 rows x 7 columns]

### การตรวจผล

| ดัชนี | student_id | name | major | age | gpa | phone | updated_date |
| --- | --- | --- | --- | --- | --- | --- | --- |
| 0 | S001 | สมชาย สุขสม | การตลาด | 19.0 | 2.11 | 0882903368 | 2026-06-01 |
| 1 | S002 | อรุณ ศรีสุข | คอมพิวเตอร์ธุรกิจ | 22.0 | 3.61 | 0845046288 | 2026-06-09 |
| 2 | S003 | วรรณา สุขสม | คอมพิวเตอร์ธุรกิจ | 18.0 | 2.92 | 0877470852 | 2026-06-06 |
| 3 | S004 | ชัย สุขสม | การตลาด | 18.0 | ว่าง | 0863778945 | 2026-06-04 |
| 4 | S005 | กมล ศรีสุข | คอมพิวเตอร์ธุรกิจ | 19.0 | 3.34 | 0813749650 | 2026-06-05 |
| 5 | S006 | ศิริ ทองคำ | เทคโนโลยีสารสนเทศ | 22.0 | 3.07 | 0856208603 | 2026-06-08 |
| 6 | S007 | อรุณ บุญมา | คอมพิวเตอร์ธุรกิจ | 19.0 | 1.97 | 0823711300 | 2026-06-04 |
| 7 | S008 | ศิริ สุขสม | คอมพิวเตอร์ธุรกิจ | 150.0 | 2.81 | 0891907998 | 2026-06-01 |
| 8 | S009 | ศิริ บุญมา | คอมพิวเตอร์ธุรกิจ | 22.0 | 1.98 | 0898662305 | 2026-06-02 |
| 9 | S010 | ภูมิ แก้วมณี | การตลาด | 18.0 | 2.8 | 0833960779 | 2026-06-07 |

ได้ 42 แถว 7 คอลัมน์ พร้อมค่าว่างและสำเนาซ้ำ

**เมื่อเกิดข้อผิดพลาด:** ใช้ต้นทางเดิมเพื่อเปรียบเทียบก่อนและหลัง

**ตรวจความเข้าใจ:** ยังมี 42 แถว

## ขั้นที่ 3: ทบทวนข้อมูลก่อนแก้

ตรวจตัวอย่างและค่าว่างก่อนทำความสะอาด

```python
df.head()
```

- `.head()`: แสดงห้าแถวแรก

เขียนคำสั่งและกด Shift + Enter ก่อนอ่านผลด้านล่าง

In [3]:
df.head()

  student_id         name              major  ...   gpa       phone updated_date
0       S001  สมชาย สุขสม            การตลาด  ...  2.11  0882903368   2026-06-01
1       S002  อรุณ ศรีสุข  คอมพิวเตอร์ธุรกิจ  ...  3.61  0845046288   2026-06-09
2       S003  วรรณา สุขสม  คอมพิวเตอร์ธุรกิจ  ...  2.92  0877470852   2026-06-06
3       S004    ชัย สุขสม            การตลาด  ...   NaN  0863778945   2026-06-04
4       S005   กมล ศรีสุข  คอมพิวเตอร์ธุรกิจ  ...  3.34  0813749650   2026-06-05

[5 rows x 7 columns]

### การตรวจผล

| ดัชนี | student_id | name | major | age | gpa | phone | updated_date |
| --- | --- | --- | --- | --- | --- | --- | --- |
| 0 | S001 | สมชาย สุขสม | การตลาด | 19.0 | 2.11 | 0882903368 | 2026-06-01 |
| 1 | S002 | อรุณ ศรีสุข | คอมพิวเตอร์ธุรกิจ | 22.0 | 3.61 | 0845046288 | 2026-06-09 |
| 2 | S003 | วรรณา สุขสม | คอมพิวเตอร์ธุรกิจ | 18.0 | 2.92 | 0877470852 | 2026-06-06 |
| 3 | S004 | ชัย สุขสม | การตลาด | 18.0 | ว่าง | 0863778945 | 2026-06-04 |
| 4 | S005 | กมล ศรีสุข | คอมพิวเตอร์ธุรกิจ | 19.0 | 3.34 | 0813749650 | 2026-06-05 |

เห็น S004 มี GPA ว่าง; ข้อมูลต้นทางยังไม่ถูกเปลี่ยน

**เมื่อเกิดข้อผิดพลาด:** อย่าแทนค่าว่างด้วยศูนย์โดยไม่มีเหตุผล

**ตรวจความเข้าใจ:** อธิบายได้ว่าค่าว่างแตกต่างจากคะแนนศูนย์

## ขั้นที่ 4: สร้างสำเนาสำหรับแก้

สร้างตารางใหม่แยกจากต้นทาง

```python
clean = df.copy()
clean.head()
```

- `.copy()`: สร้างสำเนา DataFrame
- `clean`: ตารางที่ใช้แก้ไข

เขียนคำสั่งและกด Shift + Enter ก่อนอ่านผลด้านล่าง

In [4]:
clean = df.copy()
clean.head()

  student_id         name              major  ...   gpa       phone updated_date
0       S001  สมชาย สุขสม            การตลาด  ...  2.11  0882903368   2026-06-01
1       S002  อรุณ ศรีสุข  คอมพิวเตอร์ธุรกิจ  ...  3.61  0845046288   2026-06-09
2       S003  วรรณา สุขสม  คอมพิวเตอร์ธุรกิจ  ...  2.92  0877470852   2026-06-06
3       S004    ชัย สุขสม            การตลาด  ...   NaN  0863778945   2026-06-04
4       S005   กมล ศรีสุข  คอมพิวเตอร์ธุรกิจ  ...  3.34  0813749650   2026-06-05

[5 rows x 7 columns]

### การตรวจผล

| ดัชนี | student_id | name | major | age | gpa | phone | updated_date |
| --- | --- | --- | --- | --- | --- | --- | --- |
| 0 | S001 | สมชาย สุขสม | การตลาด | 19.0 | 2.11 | 0882903368 | 2026-06-01 |
| 1 | S002 | อรุณ ศรีสุข | คอมพิวเตอร์ธุรกิจ | 22.0 | 3.61 | 0845046288 | 2026-06-09 |
| 2 | S003 | วรรณา สุขสม | คอมพิวเตอร์ธุรกิจ | 18.0 | 2.92 | 0877470852 | 2026-06-06 |
| 3 | S004 | ชัย สุขสม | การตลาด | 18.0 | ว่าง | 0863778945 | 2026-06-04 |
| 4 | S005 | กมล ศรีสุข | คอมพิวเตอร์ธุรกิจ | 19.0 | 3.34 | 0813749650 | 2026-06-05 |

ห้าแถวแรกยังเหมือน df; clean มีข้อมูลครบ 42 แถว

**เมื่อเกิดข้อผิดพลาด:** ใช้ copy ไม่เขียน clean = df ซึ่งอ้างถึงตารางเดิม

**ตรวจความเข้าใจ:** ระบุได้ว่า df เก็บต้นทาง และ clean ใช้แก้

## ขั้นที่ 5: ลบเฉพาะสำเนาซ้ำ

ลบแถวที่ซ้ำทุกคอลัมน์โดยเก็บรายการแรก

```python
clean = clean.drop_duplicates()
clean
```

- `.drop_duplicates()`: คืนตารางที่ตัดสำเนาซ้ำทั้งแถวออก

เขียนคำสั่งและกด Shift + Enter ก่อนอ่านผลด้านล่าง

In [5]:
clean = clean.drop_duplicates()
clean

   student_id            name  ...       phone  updated_date
0        S001     สมชาย สุขสม  ...  0882903368    2026-06-01
1        S002     อรุณ ศรีสุข  ...  0845046288    2026-06-09
2        S003     วรรณา สุขสม  ...  0877470852    2026-06-06
3        S004       ชัย สุขสม  ...  0863778945    2026-06-04
4        S005      กมล ศรีสุข  ...  0813749650    2026-06-05
5        S006      ศิริ ทองคำ  ...  0856208603    2026-06-08
6        S007      อรุณ บุญมา  ...  0823711300    2026-06-04
7        S008      ศิริ สุขสม  ...  0891907998    2026-06-01
8        S009      ศิริ บุญมา  ...  0898662305    2026-06-02
9        S010    ภูมิ แก้วมณี  ...  0833960779    2026-06-07
10       S011      อรุณ บุญมา  ...  0863128543    2026-06-08
11       S012       ธนา บุญมา  ...  0827050801    2026-06-01
12       S013   อนันต์ ศรีสุข  ...  0889976351    2026-06-08
13       S014       ชัย ทองคำ  ...  0812871813    2026-06-01
14       S015      อรุณ บุญมา  ...  0828689916    2026-06-07
15       S016      จิรา สุขสม  ...        <NA>    2026-06-09
16       S017      กมล ศรีสุข  ...  0827592411    2026-06-01
17       S018      ภูมิ บุญมา  ...  0879358465    2026-06-07
18       S019     จิรา ศรีสุข  ...  0878524460    2026-06-01
19       S020    จิรา แก้วมณี  ...  0830106149    2026-06-03
20       S021  อนันต์ แก้วมณี  ...  0818288654    2026-06-06
21       S022      ชัย ศรีสุข  ...  0824241764    2026-06-09
22       S023     สมชาย สุขสม  ...  0823119148    2026-06-09
23       S024     ศิริ ศรีสุข  ...  0892212100    2026-06-09
24       S025       พร ศรีสุข  ...  0878203564    2026-06-09
25       S026    อรุณ แก้วมณี  ...        0812    2026-06-09
26       S027      ภูมิ สุขสม  ...  0862662255    2026-06-08
27       S028      วรรณา ใจดี  ...  0838546741    2026-06-05
28       S029       อรุณ ใจดี  ...  0859148289    2026-06-03
29       S030      ปิยะ สุขสม  ...  0822633303    2026-06-07
30       S031    ภูมิ แก้วมณี  ...  0831671607    2020-06-05
31       S032     ณัฐ แก้วมณี  ...  0852751778    2026-06-02
32       S033      มาลี ทองคำ  ...  0869117285    2026-06-01
33       S034       ธนา ทองคำ  ...  0818628964    2020-06-02
34       S035      ภูมิ สุขสม  ...  0815313436    2026-06-03
35       S036      ปิยะ สุขสม  ...  0844709914    2026-06-07
36       S037   อนันต์ ศรีสุข  ...  0853895707    2026-06-02
37       S038       ปิยะ ใจดี  ...  0819719255    2026-06-05
38       S039     สมชาย บุญมา  ...  0839851095    2026-06-02
39       S040       ปิยะ ใจดี  ...  0884231009    2026-06-07

[40 rows x 7 columns]

### การตรวจผล

| ดัชนี | student_id | name | major | age | gpa | phone | updated_date |
| --- | --- | --- | --- | --- | --- | --- | --- |
| 0 | S001 | สมชาย สุขสม | การตลาด | 19.0 | 2.11 | 0882903368 | 2026-06-01 |
| 1 | S002 | อรุณ ศรีสุข | คอมพิวเตอร์ธุรกิจ | 22.0 | 3.61 | 0845046288 | 2026-06-09 |
| 2 | S003 | วรรณา สุขสม | คอมพิวเตอร์ธุรกิจ | 18.0 | 2.92 | 0877470852 | 2026-06-06 |
| 3 | S004 | ชัย สุขสม | การตลาด | 18.0 | ว่าง | 0863778945 | 2026-06-04 |
| 4 | S005 | กมล ศรีสุข | คอมพิวเตอร์ธุรกิจ | 19.0 | 3.34 | 0813749650 | 2026-06-05 |
| 5 | S006 | ศิริ ทองคำ | เทคโนโลยีสารสนเทศ | 22.0 | 3.07 | 0856208603 | 2026-06-08 |
| 6 | S007 | อรุณ บุญมา | คอมพิวเตอร์ธุรกิจ | 19.0 | 1.97 | 0823711300 | 2026-06-04 |
| 7 | S008 | ศิริ สุขสม | คอมพิวเตอร์ธุรกิจ | 150.0 | 2.81 | 0891907998 | 2026-06-01 |
| 8 | S009 | ศิริ บุญมา | คอมพิวเตอร์ธุรกิจ | 22.0 | 1.98 | 0898662305 | 2026-06-02 |
| 9 | S010 | ภูมิ แก้วมณี | การตลาด | 18.0 | 2.8 | 0833960779 | 2026-06-07 |

clean เหลือ 40 แถว; df ยังมี 42 แถว

**เมื่อเกิดข้อผิดพลาด:** ใช้เกณฑ์ซ้ำทั้งแถวตามชุดนี้ ไม่ลบจากชื่อเหมือนกันเพียงคอลัมน์เดียว

**ตรวจความเข้าใจ:** อธิบายได้ว่าตัดสำเนาเกินมา 2 แถว

## ขั้นที่ 6: ตัดช่องว่างหัวท้ายชื่อสาขา

ทำให้ชื่อสาขาไม่มีช่องว่างต้นหรือท้ายข้อความ

```python
clean['major'] = clean['major'].str.strip()
clean['major']
```

- `.str`: เครื่องมือสำหรับข้อความใน Series
- `.strip()`: ตัดช่องว่างหัวท้าย

เขียนคำสั่งและกด Shift + Enter ก่อนอ่านผลด้านล่าง

In [6]:
clean['major'] = clean['major'].str.strip()
clean['major']

0                การตลาด
1      คอมพิวเตอร์ธุรกิจ
2      คอมพิวเตอร์ธุรกิจ
3                การตลาด
4      คอมพิวเตอร์ธุรกิจ
5      เทคโนโลยีสารสนเทศ
6      คอมพิวเตอร์ธุรกิจ
7      คอมพิวเตอร์ธุรกิจ
8      คอมพิวเตอร์ธุรกิจ
9                การตลาด
10     คอมพิวเตอร์ธุรกิจ
11     เทคโนโลยีสารสนเทศ
12                    IT
13     เทคโนโลยีสารสนเทศ
14               การตลาด
15     เทคโนโลยีสารสนเทศ
16     คอมพิวเตอร์ธุรกิจ
17     คอมพิวเตอร์ธุรกิจ
18     เทคโนโลยีสารสนเทศ
19     เทคโนโลยีสารสนเทศ
20               การตลาด
21               การตลาด
22     เทคโนโลยีสารสนเทศ
23     เทคโนโลยีสารสนเทศ
24     เทคโนโลยีสารสนเทศ
25               การตลาด
26     คอมพิวเตอร์ธุรกิจ
27    เทคโนโลยี สารสนเทศ
28     เทคโนโลยีสารสนเทศ
29     คอมพิวเตอร์ธุรกิจ
30     เทคโนโลยีสารสนเทศ
31     คอมพิวเตอร์ธุรกิจ
32     เทคโนโลยีสารสนเทศ
33               การตลาด
34     เทคโนโลยีสารสนเทศ
35     คอมพิวเตอร์ธุรกิจ
36               การตลาด
37               การตลาด
38     เทคโนโลยีสารสนเทศ
39     คอมพิวเตอร์ธุรกิจ
Name: major, dtype: object

### การตรวจผล

```text
0               การตลาด
1     คอมพิวเตอร์ธุรกิจ
2     คอมพิวเตอร์ธุรกิจ
3               การตลาด
4     คอมพิวเตอร์ธุรกิจ
5     เทคโนโลยีสารสนเทศ
6     คอมพิวเตอร์ธุรกิจ
            ...        
33              การตลาด
34    เทคโนโลยีสารสนเทศ
35    คอมพิวเตอร์ธุรกิจ
36              การตลาด
37              การตลาด
38    เทคโนโลยีสารสนเทศ
39    คอมพิวเตอร์ธุรกิจ
```

ชุดนี้ไม่มีช่องว่างหัวท้าย จึงยังเห็นค่าเดิม; ช่องว่างภายใน เทคโนโลยี สารสนเทศ ยังอยู่

**เมื่อเกิดข้อผิดพลาด:** strip ไม่ลบช่องว่างภายในข้อความ

**ตรวจความเข้าใจ:** บอกได้ว่าช่องว่างภายในต้องแก้ด้วยวิธีอื่น

## ขั้นที่ 7: กำหนดชื่อสาขาให้ตรงกัน

แทนชื่อที่หมายถึงสาขาเดียวกันตามข้อตกลงของชุดฝึก

```python
clean['major'] = clean['major'].replace({'IT': 'เทคโนโลยีสารสนเทศ', 'เทคโนโลยี สารสนเทศ': 'เทคโนโลยีสารสนเทศ'})
clean['major']
```

- `.replace()`: แทนค่าที่ตรงตามคู่ใน dict
- `:`: ด้านซ้ายคือค่าเดิม ด้านขวาคือค่าใหม่

เขียนคำสั่งและกด Shift + Enter ก่อนอ่านผลด้านล่าง

In [7]:
clean['major'] = clean['major'].replace({'IT': 'เทคโนโลยีสารสนเทศ', 'เทคโนโลยี สารสนเทศ': 'เทคโนโลยีสารสนเทศ'})
clean['major']

0               การตลาด
1     คอมพิวเตอร์ธุรกิจ
2     คอมพิวเตอร์ธุรกิจ
3               การตลาด
4     คอมพิวเตอร์ธุรกิจ
5     เทคโนโลยีสารสนเทศ
6     คอมพิวเตอร์ธุรกิจ
7     คอมพิวเตอร์ธุรกิจ
8     คอมพิวเตอร์ธุรกิจ
9               การตลาด
10    คอมพิวเตอร์ธุรกิจ
11    เทคโนโลยีสารสนเทศ
12    เทคโนโลยีสารสนเทศ
13    เทคโนโลยีสารสนเทศ
14              การตลาด
15    เทคโนโลยีสารสนเทศ
16    คอมพิวเตอร์ธุรกิจ
17    คอมพิวเตอร์ธุรกิจ
18    เทคโนโลยีสารสนเทศ
19    เทคโนโลยีสารสนเทศ
20              การตลาด
21              การตลาด
22    เทคโนโลยีสารสนเทศ
23    เทคโนโลยีสารสนเทศ
24    เทคโนโลยีสารสนเทศ
25              การตลาด
26    คอมพิวเตอร์ธุรกิจ
27    เทคโนโลยีสารสนเทศ
28    เทคโนโลยีสารสนเทศ
29    คอมพิวเตอร์ธุรกิจ
30    เทคโนโลยีสารสนเทศ
31    คอมพิวเตอร์ธุรกิจ
32    เทคโนโลยีสารสนเทศ
33              การตลาด
34    เทคโนโลยีสารสนเทศ
35    คอมพิวเตอร์ธุรกิจ
36              การตลาด
37              การตลาด
38    เทคโนโลยีสารสนเทศ
39    คอมพิวเตอร์ธุรกิจ
Name: major, dtype: object

### การตรวจผล

```text
0               การตลาด
1     คอมพิวเตอร์ธุรกิจ
2     คอมพิวเตอร์ธุรกิจ
3               การตลาด
4     คอมพิวเตอร์ธุรกิจ
5     เทคโนโลยีสารสนเทศ
6     คอมพิวเตอร์ธุรกิจ
            ...        
33              การตลาด
34    เทคโนโลยีสารสนเทศ
35    คอมพิวเตอร์ธุรกิจ
36              การตลาด
37              การตลาด
38    เทคโนโลยีสารสนเทศ
39    คอมพิวเตอร์ธุรกิจ
```

IT และ เทคโนโลยี สารสนเทศ เปลี่ยนเป็น เทคโนโลยีสารสนเทศ; สาขาอื่นคงเดิม

**เมื่อเกิดข้อผิดพลาด:** ต้องยืนยันความหมายก่อนรวมชื่อสาขา ข้อตกลงนี้ใช้กับชุดฝึก

**ตรวจความเข้าใจ:** ไม่พบ IT หรือชื่อที่มีช่องว่างภายในในผลลัพธ์

## ขั้นที่ 8: ทำเครื่องหมายหมายเลขโทรศัพท์ที่ไม่ระบุ

แทนค่าว่างด้วยข้อความสถานะโดยไม่สร้างหมายเลขโทรศัพท์ขึ้นมา

```python
clean['phone'] = clean['phone'].fillna('ไม่ระบุ')
clean['phone']
```

- `.fillna()`: แทนเฉพาะค่าว่าง
- `'ไม่ระบุ'`: สถานะที่ไม่ใช่หมายเลขโทรศัพท์

เขียนคำสั่งและกด Shift + Enter ก่อนอ่านผลด้านล่าง

In [8]:
clean['phone'] = clean['phone'].fillna('ไม่ระบุ')
clean['phone']

0     0882903368
1     0845046288
2     0877470852
3     0863778945
4     0813749650
5     0856208603
6     0823711300
7     0891907998
8     0898662305
9     0833960779
10    0863128543
11    0827050801
12    0889976351
13    0812871813
14    0828689916
15       ไม่ระบุ
16    0827592411
17    0879358465
18    0878524460
19    0830106149
20    0818288654
21    0824241764
22    0823119148
23    0892212100
24    0878203564
25          0812
26    0862662255
27    0838546741
28    0859148289
29    0822633303
30    0831671607
31    0852751778
32    0869117285
33    0818628964
34    0815313436
35    0844709914
36    0853895707
37    0819719255
38    0839851095
39    0884231009
Name: phone, dtype: string

### การตรวจผล

```text
0     0882903368
1     0845046288
2     0877470852
3     0863778945
4     0813749650
5     0856208603
6     0823711300
         ...    
33    0818628964
34    0815313436
35    0844709914
36    0853895707
37    0819719255
38    0839851095
39    0884231009
```

หนึ่งรายการเปลี่ยนจากค่าว่างเป็น ไม่ระบุ; หมายเลขโทรศัพท์อื่นคงเดิม

**เมื่อเกิดข้อผิดพลาด:** ข้อความ ไม่ระบุ ไม่ได้ทำให้มีหมายเลขโทรศัพท์จริง ต้องบันทึกการเปลี่ยนนี้

**ตรวจความเข้าใจ:** พบ ไม่ระบุ 1 รายการ และไม่ตีความเป็นข้อมูลครบถ้วน

## ขั้นที่ 9: ตรวจช่วงอายุอีกครั้ง

สร้างหน้ากากช่วงอายุจากตาราง clean

```python
age_valid = clean['age'].between(15, 60)
age_valid
```

- `.between(15, 60)`: ตรวจช่วงรวมขอบ

เขียนคำสั่งและกด Shift + Enter ก่อนอ่านผลด้านล่าง

In [9]:
age_valid = clean['age'].between(15, 60)
age_valid

0      True
1      True
2      True
3      True
4      True
5      True
6      True
7     False
8      True
9      True
10    False
11     True
12     True
13     True
14     True
15     True
16     True
17     True
18     True
19     True
20     True
21     True
22     True
23     True
24     True
25     True
26     True
27     True
28     True
29     True
30     True
31     True
32     True
33     True
34     True
35     True
36     True
37     True
38     True
39     True
Name: age, dtype: bool

### การตรวจผล

```text
0     True
1     True
2     True
3     True
4     True
5     True
6     True
      ... 
33    True
34    True
35    True
36    True
37    True
38    True
39    True
```

False 2 แถว รวมอายุ 150 และอายุว่าง

**เมื่อเกิดข้อผิดพลาด:** ต้องสร้างหน้ากากใหม่จาก clean หลังตัดแถวซ้ำ

**ตรวจความเข้าใจ:** หน้ากากอ้างอิงดัชนีของ clean

## ขั้นที่ 10: แยกอายุผิดช่วงก่อนแก้

ระบุอายุที่มีค่าแต่ผิดเกณฑ์

```python
age_bad = ~age_valid & clean['age'].notna()
age_bad
```

- `~`: กลับหน้ากากช่วง
- `&`: และต้องมีค่า
- `.notna()`: แยกค่าว่างเดิมออก

เขียนคำสั่งและกด Shift + Enter ก่อนอ่านผลด้านล่าง

In [10]:
age_bad = ~age_valid & clean['age'].notna()
age_bad

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7      True
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30    False
31    False
32    False
33    False
34    False
35    False
36    False
37    False
38    False
39    False
Name: age, dtype: bool

### การตรวจผล

```text
0     False
1     False
2     False
3     False
4     False
5     False
6     False
      ...  
33    False
34    False
35    False
36    False
37    False
38    False
39    False
```

True หนึ่งแถว คือ S008 อายุ 150

**เมื่อเกิดข้อผิดพลาด:** อย่าใช้หน้ากากที่ยังอ้างอิง df 42 แถว

**ตรวจความเข้าใจ:** ตรวจว่าระบุเฉพาะ S008

## ขั้นที่ 11: พักค่าอายุที่ยังยืนยันไม่ได้

เปลี่ยนอายุผิดช่วงเป็นค่าว่างรอการตรวจต้นทาง

```python
clean.loc[age_bad, 'age'] = pd.NA
clean['age']
```

- `.loc[age_bad, 'age']`: เลือกเฉพาะอายุในแถวที่หน้ากากเป็น True
- `pd.NA`: ค่าว่างของ pandas

เขียนคำสั่งและกด Shift + Enter ก่อนอ่านผลด้านล่าง

In [11]:
clean.loc[age_bad, 'age'] = pd.NA
clean['age']

0     19.0
1     22.0
2     18.0
3     18.0
4     19.0
5     22.0
6     19.0
7      NaN
8     22.0
9     18.0
10     NaN
11    22.0
12    22.0
13    21.0
14    17.0
15    17.0
16    19.0
17    20.0
18    21.0
19    21.0
20    22.0
21    21.0
22    19.0
23    17.0
24    22.0
25    18.0
26    18.0
27    18.0
28    22.0
29    18.0
30    22.0
31    20.0
32    19.0
33    21.0
34    17.0
35    22.0
36    21.0
37    18.0
38    19.0
39    17.0
Name: age, dtype: float64

### การตรวจผล

```text
0     19.0
1     22.0
2     18.0
3     18.0
4     19.0
5     22.0
6     19.0
      ... 
33    21.0
34    17.0
35    22.0
36    21.0
37    18.0
38    19.0
39    17.0
```

อายุ 150 ถูกเปลี่ยนเป็นค่าว่าง; อายุว่างรวมเป็น 2 รายการ

**เมื่อเกิดข้อผิดพลาด:** ไม่แทนด้วยค่าเฉลี่ยหรือมัธยฐาน เพราะยังไม่มีหลักฐานยืนยันอายุจริง

**ตรวจความเข้าใจ:** เห็น S008 เป็นค่าว่าง และอายุอื่นไม่เปลี่ยน

## ขั้นที่ 12: ตรวจช่วง GPA อีกครั้ง

สร้างหน้ากาก GPA จากตาราง clean

```python
gpa_valid = clean['gpa'].between(0, 4)
gpa_valid
```

- `.between(0, 4)`: ตรวจ GPA 0.00–4.00

เขียนคำสั่งและกด Shift + Enter ก่อนอ่านผลด้านล่าง

In [12]:
gpa_valid = clean['gpa'].between(0, 4)
gpa_valid

0      True
1      True
2      True
3     False
4      True
5      True
6      True
7      True
8      True
9      True
10     True
11     True
12     True
13     True
14     True
15     True
16     True
17     True
18    False
19     True
20     True
21     True
22    False
23     True
24     True
25     True
26     True
27     True
28     True
29     True
30     True
31     True
32     True
33     True
34     True
35     True
36     True
37     True
38     True
39     True
Name: gpa, dtype: bool

### การตรวจผล

```text
0      True
1      True
2      True
3     False
4      True
5      True
6      True
      ...  
33     True
34     True
35     True
36     True
37     True
38     True
39     True
```

False 3 แถว รวม GPA 4.75 และค่าว่างเดิม 2 แถว

**เมื่อเกิดข้อผิดพลาด:** False ไม่ได้แปลว่าผิดช่วงทั้งหมด

**ตรวจความเข้าใจ:** อธิบายสาเหตุของ False ทั้งสามตำแหน่งได้

## วันอังคาร

## ขั้นที่ 13: แยก GPA ผิดช่วงก่อนแก้

เลือก GPA ที่มีค่าและผิดเกณฑ์

```python
gpa_bad = ~gpa_valid & clean['gpa'].notna()
gpa_bad
```

- `~gpa_valid`: อยู่นอกช่วง
- `& clean['gpa'].notna()`: และไม่เป็นค่าว่าง

เขียนคำสั่งและกด Shift + Enter ก่อนอ่านผลด้านล่าง

In [13]:
gpa_bad = ~gpa_valid & clean['gpa'].notna()
gpa_bad

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18     True
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30    False
31    False
32    False
33    False
34    False
35    False
36    False
37    False
38    False
39    False
Name: gpa, dtype: bool

### การตรวจผล

```text
0     False
1     False
2     False
3     False
4     False
5     False
6     False
      ...  
33    False
34    False
35    False
36    False
37    False
38    False
39    False
```

True หนึ่งแถว คือ S019 GPA 4.75

**เมื่อเกิดข้อผิดพลาด:** แยกค่าว่างเดิมออกจากการแก้ค่าผิดช่วง

**ตรวจความเข้าใจ:** ระบุเฉพาะ S019

## ขั้นที่ 14: พักค่า GPA ที่ยังยืนยันไม่ได้

เปลี่ยน GPA ผิดช่วงเป็นค่าว่างโดยไม่เดาคะแนน

```python
clean.loc[gpa_bad, 'gpa'] = pd.NA
clean['gpa']
```

- `pd.NA`: ค่าว่างรอตรวจต้นทาง
- `.loc[] =`: แก้เฉพาะตำแหน่งที่เลือก

เขียนคำสั่งและกด Shift + Enter ก่อนอ่านผลด้านล่าง

In [14]:
clean.loc[gpa_bad, 'gpa'] = pd.NA
clean['gpa']

0     2.11
1     3.61
2     2.92
3      NaN
4     3.34
5     3.07
6     1.97
7     2.81
8     1.98
9     2.80
10    3.48
11    2.13
12    2.11
13    2.95
14    2.91
15    2.33
16    2.94
17    3.19
18     NaN
19    1.81
20    2.05
21    2.81
22     NaN
23    2.73
24    2.38
25    3.27
26    2.67
27    2.70
28    3.15
29    3.37
30    3.55
31    2.21
32    2.96
33    2.42
34    2.36
35    3.52
36    2.84
37    2.69
38    1.98
39    2.51
Name: gpa, dtype: float64

### การตรวจผล

```text
0     2.11
1     3.61
2     2.92
3      NaN
4     3.34
5     3.07
6     1.97
      ... 
33    2.42
34    2.36
35    3.52
36    2.84
37    2.69
38    1.98
39    2.51
```

GPA 4.75 กลายเป็นค่าว่าง; GPA ว่างรวมเป็น 3 รายการ

**เมื่อเกิดข้อผิดพลาด:** การเพิ่มค่าว่างเป็นการบันทึกความไม่แน่นอน ไม่ใช่การยืนยันค่าจริง

**ตรวจความเข้าใจ:** เห็น S019 เป็นค่าว่าง และไม่เติมคะแนนแทน

## ขั้นที่ 15: แปลงวันที่เป็นชนิดวันที่

แปลงข้อความวันที่ ค.ศ. รูปแบบปี-เดือน-วัน

```python
clean['updated_date'] = pd.to_datetime(clean['updated_date'], format='%Y-%m-%d', errors='coerce')
clean['updated_date']
```

- `pd.to_datetime`: แปลงเป็นชนิด datetime
- `format='%Y-%m-%d'`: Y คือปี ค.ศ. สี่หลัก m คือเดือน d คือวัน
- `errors='coerce'`: ค่าที่แปลงไม่ได้จะเป็น NaT

เขียนคำสั่งและกด Shift + Enter ก่อนอ่านผลด้านล่าง

In [15]:
clean['updated_date'] = pd.to_datetime(clean['updated_date'], format='%Y-%m-%d', errors='coerce')
clean['updated_date']

0    2026-06-01
1    2026-06-09
2    2026-06-06
3    2026-06-04
4    2026-06-05
5    2026-06-08
6    2026-06-04
7    2026-06-01
8    2026-06-02
9    2026-06-07
10   2026-06-08
11   2026-06-01
12   2026-06-08
13   2026-06-01
14   2026-06-07
15   2026-06-09
16   2026-06-01
17   2026-06-07
18   2026-06-01
19   2026-06-03
20   2026-06-06
21   2026-06-09
22   2026-06-09
23   2026-06-09
24   2026-06-09
25   2026-06-09
26   2026-06-08
27   2026-06-05
28   2026-06-03
29   2026-06-07
30   2020-06-05
31   2026-06-02
32   2026-06-01
33   2020-06-02
34   2026-06-03
35   2026-06-07
36   2026-06-02
37   2026-06-05
38   2026-06-02
39   2026-06-07
Name: updated_date, dtype: datetime64[ns]

### การตรวจผล

```text
0    2026-06-01
1    2026-06-09
2    2026-06-06
3    2026-06-04
4    2026-06-05
5    2026-06-08
6    2026-06-04
        ...    
33   2020-06-02
34   2026-06-03
35   2026-06-07
36   2026-06-02
37   2026-06-05
38   2026-06-02
39   2026-06-07
```

ได้ dtype datetime64[ns]; วันที่ทั้งหมดแปลงได้ รวมปี 2020 และ 2026

**เมื่อเกิดข้อผิดพลาด:** การแปลงสำเร็จไม่ยืนยันว่าวันที่ทันสมัย ต้องมีวันอ้างอิงและเกณฑ์เพิ่ม

**ตรวจความเข้าใจ:** เห็นชนิด datetime64[ns] ในผลลัพธ์

## ขั้นที่ 16: ตรวจค่าว่างหลังแก้

ทบทวนจำนวนค่าว่างหลังทำความสะอาด

```python
clean.isna().sum()
```

- `.isna().sum()`: ตรวจแล้วนับค่าว่างแยกคอลัมน์

เขียนคำสั่งและกด Shift + Enter ก่อนอ่านผลด้านล่าง

In [16]:
clean.isna().sum()

student_id      0
name            0
major           0
age             2
gpa             3
phone           0
updated_date    0
dtype: int64

### การตรวจผล

```text
student_id      0
name            0
major           0
age             2
gpa             3
phone           0
updated_date    0
```

age ว่าง 2, gpa ว่าง 3; phone ว่าง 0 เพราะใช้สถานะ ไม่ระบุ; updated_date ว่าง 0

**เมื่อเกิดข้อผิดพลาด:** phone ว่าง 0 ไม่ได้แปลว่ามีหมายเลขโทรศัพท์ครบทุกคน

**ตรวจความเข้าใจ:** รายงานได้ว่า age/GPA ยังรอตรวจต้นทาง

## ขั้นที่ 17: สร้างบันทึกการเปลี่ยนแบบสรุป

บันทึกผลก่อนและหลังเป็นจำนวนรวม พร้อมอธิบายวิธีแก้ในข้อความของ Notebook

```python
cleaning_log = pd.DataFrame({
    'item': ['จำนวนแถว', 'อายุว่าง', 'GPA ว่าง', 'หมายเลขโทรศัพท์ว่างตาม isna'],
    'before': [len(df), df['age'].isna().sum(), df['gpa'].isna().sum(), df['phone'].isna().sum()],
    'after': [len(clean), clean['age'].isna().sum(), clean['gpa'].isna().sum(), clean['phone'].isna().sum()]
})
cleaning_log
```

- `pd.DataFrame`: สร้างตารางสรุปจาก dict
- `before และ after`: จำนวนก่อนและหลังที่เรียงตรงกับ item

เขียนคำสั่งและกด Shift + Enter ก่อนอ่านผลด้านล่าง

In [17]:
cleaning_log = pd.DataFrame({
    'item': ['จำนวนแถว', 'อายุว่าง', 'GPA ว่าง', 'หมายเลขโทรศัพท์ว่างตาม isna'],
    'before': [len(df), df['age'].isna().sum(), df['gpa'].isna().sum(), df['phone'].isna().sum()],
    'after': [len(clean), clean['age'].isna().sum(), clean['gpa'].isna().sum(), clean['phone'].isna().sum()]
})
cleaning_log

                          item  before  after
0                     จำนวนแถว      42     40
1                     อายุว่าง       1      2
2                     GPA ว่าง       2      3
3  หมายเลขโทรศัพท์ว่างตาม isna       1      0

### การตรวจผล

| ดัชนี | item | before | after |
| --- | --- | --- | --- |
| 0 | จำนวนแถว | 42 | 40 |
| 1 | อายุว่าง | 1 | 2 |
| 2 | GPA ว่าง | 2 | 3 |
| 3 | หมายเลขโทรศัพท์ว่างตาม isna | 1 | 0 |

จำนวนแถว 42→40; อายุว่าง 1→2; GPA ว่าง 2→3; หมายเลขโทรศัพท์ว่างตาม isna 1→0

**เมื่อเกิดข้อผิดพลาด:** บันทึกเพิ่มเติมว่า phone 1 รายการใช้ข้อความสถานะ และ age/GPA ไม่ได้เติมค่ากลาง

**ตรวจความเข้าใจ:** อธิบายเหตุผลของการเปลี่ยนตัวเลขทั้งสี่แถวได้

## ขั้นที่ 18: เตรียมตารางสรุปสำหรับเผยแพร่

เลือกเผยแพร่เฉพาะจำนวนรวมจากบันทึกการเปลี่ยน

```python
public = cleaning_log.copy()
public
```

- `.copy()`: สร้างสำเนาตารางสรุป
- `public`: ตารางที่จะส่งออก

เขียนคำสั่งและกด Shift + Enter ก่อนอ่านผลด้านล่าง

In [18]:
public = cleaning_log.copy()
public

                          item  before  after
0                     จำนวนแถว      42     40
1                     อายุว่าง       1      2
2                     GPA ว่าง       2      3
3  หมายเลขโทรศัพท์ว่างตาม isna       1      0

### การตรวจผล

| ดัชนี | item | before | after |
| --- | --- | --- | --- |
| 0 | จำนวนแถว | 42 | 40 |
| 1 | อายุว่าง | 1 | 2 |
| 2 | GPA ว่าง | 2 | 3 |
| 3 | หมายเลขโทรศัพท์ว่างตาม isna | 1 | 0 |

มีเพียง item, before และ after จำนวน 4 แถว; ไม่มีชื่อ รหัส หมายเลขโทรศัพท์ หรือข้อมูลรายบุคคล

**เมื่อเกิดข้อผิดพลาด:** อย่าใช้ clean เป็นไฟล์เผยแพร่ เพราะยังมีข้อมูลระดับบุคคล

**ตรวจความเข้าใจ:** ตรวจหัวคอลัมน์และยืนยันว่าเป็นจำนวนรวมทั้งหมด

## ขั้นที่ 19: บันทึกข้อมูลสรุปสำหรับเผยแพร่

ส่งออกเฉพาะตารางจำนวนรวม

```python
public.to_csv('clean_public.csv', index=False, encoding='utf-8-sig')
```

- `index=False`: ไม่เพิ่มเลขดัชนีที่ไม่มีความหมาย
- `.to_csv`: สร้างไฟล์ CSV

เขียนคำสั่งและกด Shift + Enter ก่อนอ่านผลด้านล่าง

In [19]:
public.to_csv('clean_public.csv', index=False, encoding='utf-8-sig')

### การตรวจผล

```text
ไม่มีผลลัพธ์แสดงใต้เซลล์ และไม่มีข้อความผิดพลาด
```

เซลล์ไม่มีตารางแสดง; เกิด clean_public.csv ที่มีเฉพาะบันทึกสรุป 4 แถว

**เมื่อเกิดข้อผิดพลาด:** การพรางหมายเลขโทรศัพท์อย่างเดียวไม่ยืนยันว่าไม่ระบุตัวบุคคล และไม่ใช่หลักฐานว่าทำตามกฎหมายครบ

**ตรวจความเข้าใจ:** พบไฟล์ clean_public.csv

## ขั้นที่ 20: ตรวจไฟล์ที่จะเผยแพร่

อ่านไฟล์ส่งออกกลับเพื่อตรวจเนื้อหาจริง

```python
public_saved = pd.read_csv('clean_public.csv')
public_saved
```

- `pd.read_csv`: อ่านไฟล์ที่เพิ่งบันทึก

เขียนคำสั่งและกด Shift + Enter ก่อนอ่านผลด้านล่าง

In [20]:
public_saved = pd.read_csv('clean_public.csv')
public_saved

                          item  before  after
0                     จำนวนแถว      42     40
1                     อายุว่าง       1      2
2                     GPA ว่าง       2      3
3  หมายเลขโทรศัพท์ว่างตาม isna       1      0

### การตรวจผล

| ดัชนี | item | before | after |
| --- | --- | --- | --- |
| 0 | จำนวนแถว | 42 | 40 |
| 1 | อายุว่าง | 1 | 2 |
| 2 | GPA ว่าง | 2 | 3 |
| 3 | หมายเลขโทรศัพท์ว่างตาม isna | 1 | 0 |

เห็น 4 แถว 3 คอลัมน์ item, before และ after; ไม่มีคอลัมน์ข้อมูลส่วนบุคคล

**เมื่อเกิดข้อผิดพลาด:** ตรวจไฟล์จริงทุกครั้งก่อนแบ่งปัน ไม่ตรวจเฉพาะชื่อตัวแปร

**ตรวจความเข้าใจ:** ส่งเฉพาะไฟล์สรุปนี้พร้อมคำอธิบาย และเก็บ clean ใน Notebook ฝึกส่วนตัว

## สรุป

อธิบายคำสั่ง ผลลัพธ์ หน่วย และข้อจำกัด บันทึก Notebook สำหรับทบทวน