# W07 — Data Model สถิติ ตัวชี้วัด และ GroupBy

## เป้าหมาย
- สร้างตารางขายที่เชื่อมแล้วก่อนคำนวณตัวชี้วัด
- หายอดเงินรวม กำไรขั้นต้นรวม จำนวนหน่วย และค่าเฉลี่ยต่อรายการ
- สรุปตามหมวดสินค้าและสร้างตารางวันคูณหมวดพร้อมอธิบายหน่วย

## เตรียมไฟล์
- nvc_store_sales.xlsx

อัปโหลดไฟล์ผ่าน Files ใน Colab ผู้สอนและผู้เรียนเขียนคำสั่งพร้อมกันทีละขั้น ใช้หนึ่งเซลล์ต่อขั้น และตรวจผลก่อนทำต่อ

## โครงสร้างข้อมูล
- nvc_store_sales.xlsx / Products: 6 แถว 5 คอลัมน์ — product_id, product_name, category, cost_price, selling_price
- nvc_store_sales.xlsx / Daily_Sales: 15 แถว 5 คอลัมน์ — order_id, product_id, quantity, payment_method, sale_date

## ขั้นที่ 1: เรียกเครื่องมือจัดการตาราง

เรียก pandas และตั้งชื่อย่อเพื่อใช้จัดการตาราง

```python
import pandas as pd
```

- `import pandas`: เรียกไลบรารี pandas
- `as pd`: ตั้งชื่อย่อ pd

เขียนคำสั่งและกด Shift + Enter ก่อนอ่านผลด้านล่าง

In [1]:
import pandas as pd

### การตรวจผล

```text
ไม่มีผลลัพธ์แสดงใต้เซลล์ และไม่มีข้อความผิดพลาด
```

ไม่มีตารางปรากฏเมื่อคำสั่งสำเร็จ

**เมื่อเกิดข้อผิดพลาด:** ใช้ pandas และ pd เป็นตัวพิมพ์เล็ก

**ตรวจความเข้าใจ:** รันเซลล์ได้โดยไม่เกิดข้อผิดพลาด แล้วชี้ชื่อย่อ pd

## ขั้นที่ 2: อ่านตารางสินค้า

อ่านแผ่นงานสินค้าและเก็บเป็นตาราง products

```python
products = pd.read_excel('nvc_store_sales.xlsx', sheet_name='Products')
```

- `products =`: เก็บตารางในตัวแปร
- `'nvc_store_sales.xlsx'`: ชื่อไฟล์ Excel ที่อัปโหลด
- `sheet_name='Products'`: เลือกแผ่นงาน Products

เขียนคำสั่งและกด Shift + Enter ก่อนอ่านผลด้านล่าง

In [2]:
products = pd.read_excel('nvc_store_sales.xlsx', sheet_name='Products')

### การตรวจผล

```text
ไม่มีผลลัพธ์แสดงใต้เซลล์ และไม่มีข้อความผิดพลาด
```

คำสั่งนี้เก็บตาราง แต่ยังไม่แสดงตาราง

**เมื่อเกิดข้อผิดพลาด:** ตรวจชื่อไฟล์และตัวพิมพ์ใหญ่ใน Products

**ตรวจความเข้าใจ:** รันได้โดยไม่เกิดข้อผิดพลาด แล้วทำขั้นแสดงตาราง

## ขั้นที่ 3: ตรวจตัวอย่างสินค้า

แสดงห้าแถวแรกของตารางสินค้า

```python
products.head()
```

- `products`: ตารางที่อ่านแล้ว
- `.head()`: แสดงห้าแถวแรกเมื่อไม่ระบุจำนวน

เขียนคำสั่งและกด Shift + Enter ก่อนอ่านผลด้านล่าง

In [3]:
products.head()

  product_id  product_name          category  cost_price  selling_price
0       P001     ชาไทยเย็น     เครื่องดื่มชง          15             30
1       P002     กาแฟโบราณ     เครื่องดื่มชง          18             35
2       P003       ชามะนาว  เครื่องดื่มผลไม้          12             25
3       P004  โกโก้เข้มข้น     เครื่องดื่มชง          18             35
4       P005   นมสดคาราเมล     เครื่องดื่มนม          20             35

### การตรวจผล

| ดัชนี | product_id | product_name | category | cost_price | selling_price |
| --- | --- | --- | --- | --- | --- |
| 0 | P001 | ชาไทยเย็น | เครื่องดื่มชง | 15 | 30 |
| 1 | P002 | กาแฟโบราณ | เครื่องดื่มชง | 18 | 35 |
| 2 | P003 | ชามะนาว | เครื่องดื่มผลไม้ | 12 | 25 |
| 3 | P004 | โกโก้เข้มข้น | เครื่องดื่มชง | 18 | 35 |
| 4 | P005 | นมสดคาราเมล | เครื่องดื่มนม | 20 | 35 |

หนึ่งแถวคือหนึ่งสินค้า มีราคาทุนและราคาขายต่อหน่วยเป็นบาท

**เมื่อเกิดข้อผิดพลาด:** ต้องรันขั้นอ่าน Products ก่อน

**ตรวจความเข้าใจ:** พบ product_id, cost_price และ selling_price; แถว P001 มีราคาขาย 30 บาทต่อหน่วย

## ขั้นที่ 4: อ่านตารางรายการขาย

อ่านแผ่นงานรายการขายและเก็บเป็นตาราง sales

```python
sales = pd.read_excel('nvc_store_sales.xlsx', sheet_name='Daily_Sales')
```

- `sales =`: เก็บตารางรายการขาย
- `'nvc_store_sales.xlsx'`: ชื่อไฟล์เดิม
- `sheet_name='Daily_Sales'`: เลือกแผ่นงาน Daily_Sales

เขียนคำสั่งและกด Shift + Enter ก่อนอ่านผลด้านล่าง

In [4]:
sales = pd.read_excel('nvc_store_sales.xlsx', sheet_name='Daily_Sales')

### การตรวจผล

```text
ไม่มีผลลัพธ์แสดงใต้เซลล์ และไม่มีข้อความผิดพลาด
```

คำสั่งนี้ยังไม่แสดงตาราง ต้องตรวจด้วยขั้นถัดไป

**เมื่อเกิดข้อผิดพลาด:** Daily_Sales มีขีดล่างและตัวพิมพ์ใหญ่

**ตรวจความเข้าใจ:** รันได้โดยไม่เกิดข้อผิดพลาด

## ขั้นที่ 5: ตรวจตัวอย่างรายการขาย

แสดงห้าแถวแรกของรายการขาย

```python
sales.head()
```

- `sales`: ตารางรายการขาย
- `.head()`: แสดงห้าแถวแรก

เขียนคำสั่งและกด Shift + Enter ก่อนอ่านผลด้านล่าง

In [5]:
sales.head()

  order_id product_id  quantity payment_method   sale_date
0   ORD001       P001         2         เงินสด  2026-11-01
1   ORD002       P002         1      พร้อมเพย์  2026-11-01
2   ORD003       P001         3      พร้อมเพย์  2026-11-01
3   ORD004       P004         1         เงินสด  2026-11-01
4   ORD005       P003         2      พร้อมเพย์  2026-11-01

### การตรวจผล

| ดัชนี | order_id | product_id | quantity | payment_method | sale_date |
| --- | --- | --- | --- | --- | --- |
| 0 | ORD001 | P001 | 2 | เงินสด | 2026-11-01 |
| 1 | ORD002 | P002 | 1 | พร้อมเพย์ | 2026-11-01 |
| 2 | ORD003 | P001 | 3 | พร้อมเพย์ | 2026-11-01 |
| 3 | ORD004 | P004 | 1 | เงินสด | 2026-11-01 |
| 4 | ORD005 | P003 | 2 | พร้อมเพย์ | 2026-11-01 |

หนึ่งแถวเป็นรายการขายที่มีรหัส order_id; quantity เป็นจำนวนหน่วย

**เมื่อเกิดข้อผิดพลาด:** อย่าสับสน quantity กับจำนวนแถว

**ตรวจความเข้าใจ:** พบ order_id, product_id, quantity และ sale_date; ORD001 ขาย 2 หน่วย

## ขั้นที่ 6: ยืนยันระดับรายละเอียดก่อนหาค่าเฉลี่ย

ตรวจรหัสรายการขายเพื่อกำหนดความหมายของค่าเฉลี่ย

```python
sales['order_id'].is_unique
```

- `sales['order_id']`: รหัสรายการขาย
- `.is_unique`: ตรวจว่ารหัสไม่ซ้ำ

เขียนคำสั่งและกด Shift + Enter ก่อนอ่านผลด้านล่าง

In [6]:
sales['order_id'].is_unique

True

### การตรวจผล

```text
True
```

ได้ True จึงใช้หนึ่งแถวเป็นหนึ่งรายการขายในชุดฝึกนี้

**เมื่อเกิดข้อผิดพลาด:** คีย์สินค้าอาจซ้ำได้ จึงใช้ตรวจจำนวนรายการขายไม่ได้

**ตรวจความเข้าใจ:** ผลเป็น True และบอกได้ว่าค่าเฉลี่ยต่อรายการใช้หนึ่งแถวเป็นหนึ่งรายการ

## ขั้นที่ 7: เชื่อมรายการขายกับสินค้า

เติมชื่อสินค้าและราคาลงในแต่ละรายการขาย

```python
merged = sales.merge(products, on='product_id', how='left', validate='many_to_one')
```

- `sales.merge(products, ...)`: ใช้ sales เป็นตารางซ้ายและ products เป็นตารางขวา
- `on='product_id'`: จับคู่ด้วยรหัสสินค้าที่ชื่อเหมือนกันทั้งสองตาราง
- `how='left'`: เก็บทุกรายการจาก sales แม้หารหัสคู่ไม่พบ
- `validate='many_to_one'`: ตรวจว่าหลายรายการขายจับคู่กับสินค้าเพียงหนึ่งแถวต่อรหัส

เขียนคำสั่งและกด Shift + Enter ก่อนอ่านผลด้านล่าง

In [7]:
merged = sales.merge(products, on='product_id', how='left', validate='many_to_one')

### การตรวจผล

```text
ไม่มีผลลัพธ์แสดงใต้เซลล์ และไม่มีข้อความผิดพลาด
```

เก็บตาราง merged โดยยังไม่แสดง; หากคีย์สินค้าซ้ำจะเกิดข้อผิดพลาด

**เมื่อเกิดข้อผิดพลาด:** อย่าใช้ inner เพื่อซ่อนรายการที่ไม่มีคู่; ตรวจชื่อคีย์และคีย์ซ้ำเมื่อเชื่อมไม่ผ่าน

**ตรวจความเข้าใจ:** รันได้โดยไม่เกิดข้อผิดพลาด แล้วแสดง merged ในขั้นถัดไป

## ขั้นที่ 8: ตรวจตารางที่เชื่อมแล้ว

แสดงตัวอย่างผลการเชื่อม

```python
merged.head()
```

- `merged`: ตารางหลังเชื่อม
- `.head()`: แสดงห้าแถวแรก

เขียนคำสั่งและกด Shift + Enter ก่อนอ่านผลด้านล่าง

In [8]:
merged.head()

  order_id product_id  quantity  ...          category cost_price selling_price
0   ORD001       P001         2  ...     เครื่องดื่มชง         15            30
1   ORD002       P002         1  ...     เครื่องดื่มชง         18            35
2   ORD003       P001         3  ...     เครื่องดื่มชง         15            30
3   ORD004       P004         1  ...     เครื่องดื่มชง         18            35
4   ORD005       P003         2  ...  เครื่องดื่มผลไม้         12            25

[5 rows x 9 columns]

### การตรวจผล

| ดัชนี | order_id | product_id | quantity | payment_method | sale_date | product_name | category | cost_price | selling_price |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |
| 0 | ORD001 | P001 | 2 | เงินสด | 2026-11-01 | ชาไทยเย็น | เครื่องดื่มชง | 15 | 30 |
| 1 | ORD002 | P002 | 1 | พร้อมเพย์ | 2026-11-01 | กาแฟโบราณ | เครื่องดื่มชง | 18 | 35 |
| 2 | ORD003 | P001 | 3 | พร้อมเพย์ | 2026-11-01 | ชาไทยเย็น | เครื่องดื่มชง | 15 | 30 |
| 3 | ORD004 | P004 | 1 | เงินสด | 2026-11-01 | โกโก้เข้มข้น | เครื่องดื่มชง | 18 | 35 |
| 4 | ORD005 | P003 | 2 | พร้อมเพย์ | 2026-11-01 | ชามะนาว | เครื่องดื่มผลไม้ | 12 | 25 |

ORD001 จับคู่ P001 ได้ชื่อชาไทยเย็น ราคาขาย 30 บาทต่อหน่วย

**เมื่อเกิดข้อผิดพลาด:** อย่าใช้ผลจากตัวแปร sales แทน merged

**ตรวจความเข้าใจ:** พบข้อมูลรายการขายและราคาในตารางเดียวกัน

## ขั้นที่ 9: ทบทวนยอดเงินรายการ

สร้างยอดเงินจากจำนวนหน่วยคูณราคาขายต่อหน่วย

```python
merged['total_amount'] = merged['quantity'] * merged['selling_price']
```

- `merged['total_amount'] =`: คอลัมน์ยอดเงินที่สร้างขึ้น
- `merged['quantity']`: จำนวนหน่วย
- `* merged['selling_price']`: คูณราคาขายบาทต่อหน่วย

เขียนคำสั่งและกด Shift + Enter ก่อนอ่านผลด้านล่าง

In [9]:
merged['total_amount'] = merged['quantity'] * merged['selling_price']

### การตรวจผล

```text
ไม่มีผลลัพธ์แสดงใต้เซลล์ และไม่มีข้อความผิดพลาด
```

เก็บยอดเงินเป็นบาทต่อรายการ ยังไม่แสดงผล

**เมื่อเกิดข้อผิดพลาด:** ใช้วงเล็บเหลี่ยมเลือกชื่อคอลัมน์ให้ตรง

**ตรวจความเข้าใจ:** รันได้ แล้วทำสูตรกำไรขั้นต้น

## ขั้นที่ 10: ทบทวนกำไรขั้นต้นรายการ

คำนวณส่วนต่างราคาต่อหน่วยก่อนคูณจำนวนหน่วย

```python
merged['total_profit'] = merged['quantity'] * (merged['selling_price'] - merged['cost_price'])
```

- `merged['total_profit'] =`: คอลัมน์กำไรขั้นต้น
- `(merged['selling_price'] - merged['cost_price'])`: วงเล็บให้ลบราคาทุนจากราคาขายก่อน
- `merged['quantity'] *`: คูณส่วนต่างด้วยจำนวนหน่วย

เขียนคำสั่งและกด Shift + Enter ก่อนอ่านผลด้านล่าง

In [10]:
merged['total_profit'] = merged['quantity'] * (merged['selling_price'] - merged['cost_price'])

### การตรวจผล

```text
ไม่มีผลลัพธ์แสดงใต้เซลล์ และไม่มีข้อความผิดพลาด
```

เก็บกำไรขั้นต้นเป็นบาทต่อรายการ ยังไม่แสดงผล

**เมื่อเกิดข้อผิดพลาด:** หากลืมวงเล็บ ลำดับคำนวณจะเปลี่ยน

**ตรวจความเข้าใจ:** รันได้และอธิบายหน้าที่ของวงเล็บ

## ขั้นที่ 11: ตรวจผลคำนวณก่อนรวมยอด

ตรวจรายการขายกับยอดเงินและกำไรขั้นต้น

```python
merged[['order_id', 'total_amount', 'total_profit']].head()
```

- `[['order_id', 'total_amount', 'total_profit']]`: เลือกคอลัมน์ที่ต้องตรวจ
- `.head()`: แสดงห้าแถวแรก

เขียนคำสั่งและกด Shift + Enter ก่อนอ่านผลด้านล่าง

In [11]:
merged[['order_id', 'total_amount', 'total_profit']].head()

  order_id  total_amount  total_profit
0   ORD001            60            30
1   ORD002            35            17
2   ORD003            90            45
3   ORD004            35            17
4   ORD005            50            26

### การตรวจผล

| ดัชนี | order_id | total_amount | total_profit |
| --- | --- | --- | --- |
| 0 | ORD001 | 60 | 30 |
| 1 | ORD002 | 35 | 17 |
| 2 | ORD003 | 90 | 45 |
| 3 | ORD004 | 35 | 17 |
| 4 | ORD005 | 50 | 26 |

ORD001 มีรายได้ 60 บาท และกำไรขั้นต้น 30 บาท

**เมื่อเกิดข้อผิดพลาด:** อย่าอ่านผลจากตารางเก่าที่ไม่มีคอลัมน์คำนวณ

**ตรวจความเข้าใจ:** ผล ORD001 เป็น 60 และ 30

## ขั้นที่ 12: หายอดเงินรวม

รวมยอดเงินทั้งหมดเป็น KPI

```python
merged['total_amount'].sum()
```

- `merged['total_amount']`: ยอดเงินบาทต่อรายการ
- `.sum()`: บวกทุกค่าที่มีข้อมูล

เขียนคำสั่งและกด Shift + Enter ก่อนอ่านผลด้านล่าง

In [12]:
merged['total_amount'].sum()

np.int64(910)

### การตรวจผล

```text
np.int64(910)
```

ยอดเงินรวม 910 บาท ไม่ใช่ราคาต่อหน่วย

**เมื่อเกิดข้อผิดพลาด:** ผลรวมที่ข้ามค่าว่างอาจไม่ครบ ต้องตรวจข้อมูลก่อนใช้จริง

**ตรวจความเข้าใจ:** ตอบ 910 บาทพร้อมระบุว่าเป็นยอดเงินของข้อมูลชุดนี้

## ขั้นที่ 13: หากำไรขั้นต้นรวม

รวมกำไรขั้นต้นทุกแถว

```python
merged['total_profit'].sum()
```

- `merged['total_profit']`: กำไรขั้นต้นบาทต่อรายการ
- `.sum()`: บวกค่าทุกรายการ

เขียนคำสั่งและกด Shift + Enter ก่อนอ่านผลด้านล่าง

In [13]:
merged['total_profit'].sum()

np.int64(446)

### การตรวจผล

```text
np.int64(446)
```

กำไรขั้นต้นรวม 446 บาท ยังไม่ได้หักค่าใช้จ่ายอื่น

**เมื่อเกิดข้อผิดพลาด:** ห้ามตีความเป็นกำไรสุทธิ

**ตรวจความเข้าใจ:** ตอบ 446 บาทและบอกข้อจำกัด

## ขั้นที่ 14: หาจำนวนขายรวม

รวมจำนวนหน่วยที่ขาย

```python
merged['quantity'].sum()
```

- `merged['quantity']`: จำนวนหน่วยต่อรายการ
- `.sum()`: บวกจำนวนหน่วยทั้งหมด

เขียนคำสั่งและกด Shift + Enter ก่อนอ่านผลด้านล่าง

In [14]:
merged['quantity'].sum()

np.int64(28)

### การตรวจผล

```text
np.int64(28)
```

ขายรวม 28 หน่วย ซึ่งต่างจากจำนวนรายการขาย 15 รายการ

**เมื่อเกิดข้อผิดพลาด:** ห้ามใช้จำนวนแถวแทนจำนวนหน่วย

**ตรวจความเข้าใจ:** ตอบ 28 หน่วยและแยกหน่วยออกจากรายการ

## ขั้นที่ 15: หายอดเงินเฉลี่ยต่อรายการ

หาค่าเฉลี่ยยอดเงินของรายการขายในชุดที่ตรวจรหัสไม่ซ้ำแล้ว

```python
merged['total_amount'].mean()
```

- `merged['total_amount']`: ยอดเงินของแต่ละรายการขาย
- `.mean()`: หาค่าเฉลี่ยเลขคณิตของค่าที่มีข้อมูล

เขียนคำสั่งและกด Shift + Enter ก่อนอ่านผลด้านล่าง

In [15]:
merged['total_amount'].mean()

np.float64(60.666666666666664)

### การตรวจผล

```text
np.float64(60.666666666666664)
```

ได้ประมาณ 60.67 บาทต่อรายการ จาก 910 บาท ÷ 15 รายการ; ผลบนหน้าจออาจมีทศนิยมหลายตำแหน่ง

**เมื่อเกิดข้อผิดพลาด:** ค่านี้ไม่ใช่ราคาขายเฉลี่ยต่อหน่วย และไม่ใช่ค่าเฉลี่ยต่อบิลหากบิลมีหลายแถว

**ตรวจความเข้าใจ:** อ่านค่าเฉลี่ยพร้อมหน่วยบาทต่อรายการ

## วันอังคาร

## ขั้นที่ 16: แบ่งรายการตามหมวดสินค้า

สร้างกลุ่มรายการขายที่มีหมวดสินค้าเดียวกัน

```python
category_groups = merged.groupby('category')
```

- `category_groups =`: เก็บตัวแบ่งกลุ่ม
- `groupby('category')`: ใช้คอลัมน์ category เป็นเกณฑ์แบ่งกลุ่ม

เขียนคำสั่งและกด Shift + Enter ก่อนอ่านผลด้านล่าง

In [16]:
category_groups = merged.groupby('category')

### การตรวจผล

```text
ไม่มีผลลัพธ์แสดงใต้เซลล์ และไม่มีข้อความผิดพลาด
```

ยังไม่ได้ยอดรวมและยังไม่แสดงตารางสรุป

**เมื่อเกิดข้อผิดพลาด:** groupby เพียงอย่างเดียวไม่ได้บวกค่า

**ตรวจความเข้าใจ:** รันได้และบอกได้ว่ากำลังแบ่งด้วยหมวดสินค้า

## ขั้นที่ 17: เลือกตัวเลขที่จะสรุป

เลือกยอดเงินและกำไรขั้นต้นจากแต่ละกลุ่ม

```python
category_values = category_groups[['total_amount', 'total_profit']]
```

- `category_values =`: เก็บค่าที่เลือกจากกลุ่ม
- `[['total_amount', 'total_profit']]`: เลือกสองคอลัมน์ตัวเลขด้วยวงเล็บเหลี่ยมสองชั้น

เขียนคำสั่งและกด Shift + Enter ก่อนอ่านผลด้านล่าง

In [17]:
category_values = category_groups[['total_amount', 'total_profit']]

### การตรวจผล

```text
ไม่มีผลลัพธ์แสดงใต้เซลล์ และไม่มีข้อความผิดพลาด
```

ยังไม่รวมค่า ต้องสั่ง sum ในขั้นถัดไป

**เมื่อเกิดข้อผิดพลาด:** อย่าเลือก quantity หากโจทย์ต้องการหน่วยบาท

**ตรวจความเข้าใจ:** รันได้และชี้ได้ว่าสองคอลัมน์มีหน่วยบาท

## ขั้นที่ 18: รวมยอดตามหมวด

บวกยอดเงินและกำไรขั้นต้นภายในแต่ละหมวด

```python
category_values.sum()
```

- `category_values`: ข้อมูลสองคอลัมน์ที่แบ่งกลุ่มแล้ว
- `.sum()`: รวมแยกแต่ละกลุ่มและแต่ละคอลัมน์

เขียนคำสั่งและกด Shift + Enter ก่อนอ่านผลด้านล่าง

In [18]:
category_values.sum()

                  total_amount  total_profit
category
เครื่องดื่มชง              705           349
เครื่องดื่มนม              105            45
เครื่องดื่มผลไม้           100            52

### การตรวจผล

| ดัชนี | total_amount | total_profit |
| --- | --- | --- |
| เครื่องดื่มชง | 705 | 349 |
| เครื่องดื่มนม | 105 | 45 |
| เครื่องดื่มผลไม้ | 100 | 52 |

เครื่องดื่มชงมีรายได้ 705 บาท และกำไรขั้นต้น 349 บาท; เครื่องดื่มนม 105 และ 45 บาท; เครื่องดื่มผลไม้ 100 และ 52 บาท

**เมื่อเกิดข้อผิดพลาด:** อย่านำยอดของคนละคอลัมน์มาบวกกัน

**ตรวจความเข้าใจ:** อ่านหมวดเครื่องดื่มชงได้สองตัวชี้วัดพร้อมหน่วย

## ขั้นที่ 19: จัดตารางวันคูณหมวดสินค้า

สร้างตารางยอดเงินที่อ่านได้ทั้งตามวันและหมวด

```python
pivot = merged.pivot_table(index='sale_date', columns='category', values='total_amount', aggfunc='sum', fill_value=0)
```

- `pivot =`: เก็บตารางที่จัดแกนแล้ว
- `index='sale_date'`: แถวคือวันที่ขาย
- `columns='category'`: คอลัมน์คือหมวดสินค้า
- `values='total_amount'`: ใช้ยอดเงินบาทต่อรายการ
- `aggfunc='sum'`: บวกยอดเงินในคู่วันกับหมวดเดียวกัน
- `fill_value=0`: แทนช่องคู่วันกับหมวดที่ไม่มีรายการด้วยศูนย์

เขียนคำสั่งและกด Shift + Enter ก่อนอ่านผลด้านล่าง

In [19]:
pivot = merged.pivot_table(index='sale_date', columns='category', values='total_amount', aggfunc='sum', fill_value=0)

### การตรวจผล

```text
ไม่มีผลลัพธ์แสดงใต้เซลล์ และไม่มีข้อความผิดพลาด
```

คำสั่งเก็บ pivot ยังไม่แสดงตาราง

**เมื่อเกิดข้อผิดพลาด:** อย่าสลับแกนหรือใช้ mean แทน sum หากโจทย์ต้องการยอดรวม

**ตรวจความเข้าใจ:** รันได้และอธิบายพารามิเตอร์ทั้งห้ารายการ

## ขั้นที่ 20: อ่านตารางสองแกน

แสดงยอดเงินรายวันแยกหมวด

```python
pivot
```

- `pivot`: ตารางที่เก็บจาก pivot_table

เขียนคำสั่งและกด Shift + Enter ก่อนอ่านผลด้านล่าง

In [20]:
pivot

category    เครื่องดื่มชง  เครื่องดื่มนม  เครื่องดื่มผลไม้
sale_date
2026-11-01            380             35                50
2026-11-02            325             70                50

### การตรวจผล

| ดัชนี | เครื่องดื่มชง | เครื่องดื่มนม | เครื่องดื่มผลไม้ |
| --- | --- | --- | --- |
| 2026-11-01 | 380 | 35 | 50 |
| 2026-11-02 | 325 | 70 | 50 |

วันที่ 1 พ.ย. มีเครื่องดื่มชง 380 บาท นม 35 บาท ผลไม้ 50 บาท; วันที่ 2 พ.ย. มี 325, 70 และ 50 บาท

**เมื่อเกิดข้อผิดพลาด:** แต่ละช่องมีหน่วยบาท ไม่ใช่จำนวนรายการหรือจำนวนหน่วย

**ตรวจความเข้าใจ:** อ่านค่าหนึ่งช่องโดยระบุวัน หมวด และหน่วยได้ครบ

## สรุป

อธิบายคำสั่ง ผลลัพธ์ หน่วย และข้อจำกัด บันทึก Notebook สำหรับทบทวน