# W09 — Data Model อนุกรมเวลาและการคาดการณ์

## จุดประสงค์การเรียนรู้
- แปลงวันที่เป็น datetime ก่อนรวมยอดรายวัน
- เรียงวันและคำนวณค่าเฉลี่ยเคลื่อนที่สามรายการวันที่มีข้อมูล
- สร้างค่าฐานจากสามรายการล่าสุดและอธิบายข้อจำกัด

## การเตรียมไฟล์ข้อมูล
- drinks_shop.csv

อัปโหลดไฟล์ข้อมูลผ่านเมนู Files ในโปรแกรม Google Colab แล้วพิมพ์คำสั่งและรันผลลัพธ์ตามลำดับทีละขั้นตอน

## โครงสร้างชุดข้อมูล
- ไฟล์ drinks_shop.csv: จำนวน 40 แถว 5 คอลัมน์ ได้แก่ date, day, menu, cups, price

## ขั้นตอนที่ 1: เรียกเครื่องมือจัดการตาราง

เรียก pandas และตั้งชื่อย่อเพื่อใช้จัดการตาราง

```python
import pandas as pd
```

- `import pandas`: เรียกไลบรารี pandas
- `as pd`: ตั้งชื่อย่อ pd

พิมพ์คำสั่งและกดปุ่ม Shift + Enter เพื่อรันคำสั่งและตรวจสอบผลลัพธ์

In [1]:
import pandas as pd

### ผลลัพธ์และคำอธิบาย

```text
รันคำสั่งสำเร็จ (ไม่มีข้อความแจ้งข้อผิดพลาด)
```

ไม่มีตารางปรากฏเมื่อคำสั่งสำเร็จ

**ข้อควรระวังในการเขียนคำสั่ง:** ใช้ pandas และ pd เป็นตัวพิมพ์เล็ก

**คำถามตรวจสอบความเข้าใจ:** รันเซลล์ได้โดยไม่เกิดข้อผิดพลาด แล้วชี้ชื่อย่อ pd

## ขั้นตอนที่ 2: อ่านข้อมูลร้านเครื่องดื่ม

อ่านไฟล์ CSV และเก็บใน df

```python
df = pd.read_csv('drinks_shop.csv')
```

- `df =`: เก็บตารางไว้ใช้ต่อ
- `pd.read_csv(...)`: อ่านข้อมูล CSV
- `'drinks_shop.csv'`: ชื่อไฟล์ที่อยู่ในพื้นที่ทำงาน

พิมพ์คำสั่งและกดปุ่ม Shift + Enter เพื่อรันคำสั่งและตรวจสอบผลลัพธ์

In [2]:
df = pd.read_csv('drinks_shop.csv')

### ผลลัพธ์และคำอธิบาย

```text
รันคำสั่งสำเร็จ (ไม่มีข้อความแจ้งข้อผิดพลาด)
```

คำสั่งนี้ยังไม่แสดงข้อมูล

**ข้อควรระวังในการเขียนคำสั่ง:** ตรวจชื่อไฟล์และนามสกุล .csv

**คำถามตรวจสอบความเข้าใจ:** รันได้โดยไม่เกิดข้อผิดพลาด แล้วแสดงตารางในขั้นถัดไป

## ขั้นตอนที่ 3: ตรวจข้อมูลก่อนวิเคราะห์

แสดงห้าแถวแรกและตรวจความหมายของคอลัมน์

```python
df.head()
```

- `df`: ตารางร้านเครื่องดื่ม
- `.head()`: แสดงห้าแถวแรก

พิมพ์คำสั่งและกดปุ่ม Shift + Enter เพื่อรันคำสั่งและตรวจสอบผลลัพธ์

In [3]:
df.head()

         date      day        menu  cups  price
0  2026-11-01  อาทิตย์      ชาเย็น     2     60
1  2026-11-01  อาทิตย์    กาแฟเย็น     2     70
2  2026-11-01  อาทิตย์    กาแฟเย็น     1     35
3  2026-11-01  อาทิตย์  น้ำแดงโซดา     5    125
4  2026-11-02   จันทร์    กาแฟเย็น     3    105

### ผลลัพธ์และคำอธิบาย

| ลำดับแถว | date | day | menu | cups | price |
| --- | --- | --- | --- | --- | --- |
| 0 | 2026-11-01 | อาทิตย์ | ชาเย็น | 2 | 60 |
| 1 | 2026-11-01 | อาทิตย์ | กาแฟเย็น | 2 | 70 |
| 2 | 2026-11-01 | อาทิตย์ | กาแฟเย็น | 1 | 35 |
| 3 | 2026-11-01 | อาทิตย์ | น้ำแดงโซดา | 5 | 125 |
| 4 | 2026-11-02 | จันทร์ | กาแฟเย็น | 3 | 105 |

cups คือจำนวนแก้ว ส่วน price คือยอดเงินรวมของรายการเป็นบาท

**ข้อควรระวังในการเขียนคำสั่ง:** ห้ามนำ price คูณ cups ซ้ำ

**คำถามตรวจสอบความเข้าใจ:** พบ date, day, menu, cups และ price; แถวแรกขาย 2 แก้ว ยอดรวม 60 บาท

## ขั้นตอนที่ 4: แปลงวันที่เป็น datetime

แปลงข้อความวันที่เป็นชนิดวันที่แล้วเก็บกลับคอลัมน์เดิม

```python
df['date'] = pd.to_datetime(df['date'], format='%Y-%m-%d', errors='raise')
```

- `df['date'] =`: แทนคอลัมน์ date ด้วยผลแปลง
- `pd.to_datetime(...)`: แปลงข้อมูลเป็น datetime
- `df['date']`: ข้อมูลวันที่ที่จะนำมาแปลง
- `format='%Y-%m-%d'`: %Y คือปี ค.ศ. สี่หลัก %m คือเดือน %d คือวันที่ คั่นด้วยขีดกลาง
- `errors='raise'`: ให้เกิดข้อผิดพลาดเมื่อพบวันที่แปลงไม่ได้

พิมพ์คำสั่งและกดปุ่ม Shift + Enter เพื่อรันคำสั่งและตรวจสอบผลลัพธ์

In [4]:
df['date'] = pd.to_datetime(df['date'], format='%Y-%m-%d', errors='raise')

### ผลลัพธ์และคำอธิบาย

```text
รันคำสั่งสำเร็จ (ไม่มีข้อความแจ้งข้อผิดพลาด)
```

เก็บวันที่ชนิด datetime แล้ว โดยยังไม่แสดงตาราง

**ข้อควรระวังในการเขียนคำสั่ง:** ชุดพร้อมสอนเป็น ค.ศ. อยู่แล้ว ห้ามลบ 543 ซ้ำ

**คำถามตรวจสอบความเข้าใจ:** รันได้โดยไม่เกิดข้อผิดพลาดและอธิบายรูปแบบวันได้

## ขั้นตอนที่ 5: ตรวจตัวอย่างหลังแปลงวันที่

แสดงตารางเพื่อตรวจวันที่กับค่ารายการเดิม

```python
df.head()
```

- `df`: ตารางหลังแปลง date
- `.head()`: แสดงห้าแถวแรก

พิมพ์คำสั่งและกดปุ่ม Shift + Enter เพื่อรันคำสั่งและตรวจสอบผลลัพธ์

In [5]:
df.head()

        date      day        menu  cups  price
0 2026-11-01  อาทิตย์      ชาเย็น     2     60
1 2026-11-01  อาทิตย์    กาแฟเย็น     2     70
2 2026-11-01  อาทิตย์    กาแฟเย็น     1     35
3 2026-11-01  อาทิตย์  น้ำแดงโซดา     5    125
4 2026-11-02   จันทร์    กาแฟเย็น     3    105

### ผลลัพธ์และคำอธิบาย

| ลำดับแถว | date | day | menu | cups | price |
| --- | --- | --- | --- | --- | --- |
| 0 | 2026-11-01 00:00:00 | อาทิตย์ | ชาเย็น | 2 | 60 |
| 1 | 2026-11-01 00:00:00 | อาทิตย์ | กาแฟเย็น | 2 | 70 |
| 2 | 2026-11-01 00:00:00 | อาทิตย์ | กาแฟเย็น | 1 | 35 |
| 3 | 2026-11-01 00:00:00 | อาทิตย์ | น้ำแดงโซดา | 5 | 125 |
| 4 | 2026-11-02 00:00:00 | จันทร์ | กาแฟเย็น | 3 | 105 |

วันแรกยังเป็น 2026-11-01 และยอดแถวแรกยังเป็น 60 บาท

**ข้อควรระวังในการเขียนคำสั่ง:** รูปที่แสดงอาจคล้ายเดิม การแปลงชนิดเกิดจากคำสั่งก่อนหน้า

**คำถามตรวจสอบความเข้าใจ:** ตรวจปี 2026 และยืนยันว่าจำนวนแก้วกับยอดเงินไม่เปลี่ยน

## ขั้นตอนที่ 6: แบ่งรายการขายตามวันที่

รวบแถวที่มีวันที่ datetime เดียวกันเป็นกลุ่ม

```python
date_groups = df.groupby('date')
```

- `date_groups =`: เก็บตัวแบ่งกลุ่ม
- `groupby('date')`: ใช้คอลัมน์ datetime เป็นเกณฑ์แบ่งกลุ่ม

พิมพ์คำสั่งและกดปุ่ม Shift + Enter เพื่อรันคำสั่งและตรวจสอบผลลัพธ์

In [6]:
date_groups = df.groupby('date')

### ผลลัพธ์และคำอธิบาย

```text
รันคำสั่งสำเร็จ (ไม่มีข้อความแจ้งข้อผิดพลาด)
```

ยังไม่รวมยอดและยังไม่แสดงตารางสรุป

**ข้อควรระวังในการเขียนคำสั่ง:** ต้องแปลง date ก่อน ไม่ข้ามขั้นวันที่

**คำถามตรวจสอบความเข้าใจ:** รันได้และบอกได้ว่าหนึ่งกลุ่มคือหนึ่งวันที่มีข้อมูล

## ขั้นตอนที่ 7: เลือกยอดเงินในแต่ละวัน

เลือกยอดเงินรายการจากกลุ่มรายวัน

```python
date_revenue = date_groups['price']
```

- `date_revenue =`: เก็บคอลัมน์ที่เลือกจากกลุ่ม
- `date_groups['price']`: เลือก price ที่เป็นยอดรวมรายการบาท

พิมพ์คำสั่งและกดปุ่ม Shift + Enter เพื่อรันคำสั่งและตรวจสอบผลลัพธ์

In [7]:
date_revenue = date_groups['price']

### ผลลัพธ์และคำอธิบาย

```text
รันคำสั่งสำเร็จ (ไม่มีข้อความแจ้งข้อผิดพลาด)
```

ยังไม่ได้ยอดรวมรายวันจนกว่าจะใช้ sum

**ข้อควรระวังในการเขียนคำสั่ง:** ห้ามเลือก cups หากต้องการหน่วยบาท

**คำถามตรวจสอบความเข้าใจ:** รันได้และระบุหน่วยของ price เป็นบาท

## ขั้นตอนที่ 8: รวมยอดเงินรายวัน

บวกยอดเงินทุกรายการภายในแต่ละวัน

```python
daily_revenue = date_revenue.sum()
```

- `daily_revenue =`: เก็บชุดยอดเงินรายวัน
- `date_revenue`: ยอดเงินที่แบ่งกลุ่มแล้ว
- `.sum()`: รวมค่าภายในแต่ละวัน

พิมพ์คำสั่งและกดปุ่ม Shift + Enter เพื่อรันคำสั่งและตรวจสอบผลลัพธ์

In [8]:
daily_revenue = date_revenue.sum()

### ผลลัพธ์และคำอธิบาย

```text
รันคำสั่งสำเร็จ (ไม่มีข้อความแจ้งข้อผิดพลาด)
```

ผลเป็นหนึ่งค่าต่อวันที่มีข้อมูล โดยยังไม่แสดงค่า

**ข้อควรระวังในการเขียนคำสั่ง:** อย่ารวมทั้งชุดก่อน groupby เพราะจะเสียรายละเอียดรายวัน

**คำถามตรวจสอบความเข้าใจ:** รันได้และอธิบายว่าข้อมูลถูกลดเป็นยอดรายวัน

## ขั้นตอนที่ 9: เรียงวันที่จากเก่าไปใหม่

เรียงยอดรายวันตามดัชนีวันที่

```python
daily_revenue = daily_revenue.sort_index()
```

- `daily_revenue =`: เก็บผลเรียงกลับตัวแปรเดิม
- `.sort_index()`: เรียงดัชนีวันที่จากน้อยไปมากโดยค่าเริ่มต้น

พิมพ์คำสั่งและกดปุ่ม Shift + Enter เพื่อรันคำสั่งและตรวจสอบผลลัพธ์

In [9]:
daily_revenue = daily_revenue.sort_index()

### ผลลัพธ์และคำอธิบาย

```text
รันคำสั่งสำเร็จ (ไม่มีข้อความแจ้งข้อผิดพลาด)
```

ลำดับจะเริ่ม 1 พ.ย. และจบ 12 พ.ย. โดยไม่มีรายการวันที่ 6–7 พ.ย.

**ข้อควรระวังในการเขียนคำสั่ง:** ใช้ sort_index เพื่อเรียงวันที่; sort_values จะเรียงยอดเงิน

**คำถามตรวจสอบความเข้าใจ:** รันได้และบอกได้ว่าเรียงตามวัน ไม่ใช่ตามยอดเงิน

## ขั้นตอนที่ 10: สร้างตารางยอดรายวัน

แปลงชุดค่าเป็นตารางหนึ่งคอลัมน์

```python
daily = daily_revenue.to_frame(name='revenue')
```

- `daily =`: เก็บตารางใหม่
- `.to_frame(...)`: แปลง Series เป็น DataFrame
- `name='revenue'`: ตั้งชื่อคอลัมน์ยอดเงินรายวันว่า revenue

พิมพ์คำสั่งและกดปุ่ม Shift + Enter เพื่อรันคำสั่งและตรวจสอบผลลัพธ์

In [10]:
daily = daily_revenue.to_frame(name='revenue')

### ผลลัพธ์และคำอธิบาย

```text
รันคำสั่งสำเร็จ (ไม่มีข้อความแจ้งข้อผิดพลาด)
```

ยังไม่แสดงตาราง แต่มีคอลัมน์ revenue หน่วยบาทต่อวันที่มีข้อมูล

**ข้อควรระวังในการเขียนคำสั่ง:** ชื่อ revenue ต้องตรงกับคำสั่งที่ใช้ต่อ

**คำถามตรวจสอบความเข้าใจ:** รันได้แล้วแสดง daily ในขั้นถัดไป

## ขั้นตอนที่ 11: อ่านยอดรายวันก่อนคำนวณค่าเฉลี่ย

แสดงทุกวันที่มีข้อมูลเพื่อดูลำดับและวันขาด

```python
daily
```

- `daily`: ตารางยอดเงินรายวันที่เรียงแล้ว

พิมพ์คำสั่งและกดปุ่ม Shift + Enter เพื่อรันคำสั่งและตรวจสอบผลลัพธ์

In [11]:
daily

            revenue
date
2026-11-01      290
2026-11-02      380
2026-11-03      530
2026-11-04      415
2026-11-05      625
2026-11-08      505
2026-11-09      325
2026-11-10      805
2026-11-11      355
2026-11-12      655

### ผลลัพธ์และคำอธิบาย

| ลำดับแถว | revenue |
| --- | --- |
| 2026-11-01 00:00:00 | 290 |
| 2026-11-02 00:00:00 | 380 |
| 2026-11-03 00:00:00 | 530 |
| 2026-11-04 00:00:00 | 415 |
| 2026-11-05 00:00:00 | 625 |
| 2026-11-08 00:00:00 | 505 |
| 2026-11-09 00:00:00 | 325 |
| 2026-11-10 00:00:00 | 805 |
| 2026-11-11 00:00:00 | 355 |
| 2026-11-12 00:00:00 | 655 |

มี 10 วันที่บันทึก ยอดวันที่ 1 พ.ย. 290 บาท และ 12 พ.ย. 655 บาท; วันที่ 6–7 พ.ย. ไม่ปรากฏ

**ข้อควรระวังในการเขียนคำสั่ง:** วันไม่ปรากฏไม่ได้แปลว่ารายได้ศูนย์

**คำถามตรวจสอบความเข้าใจ:** อ่านสองวันที่กล่าวไว้ได้และระบุช่วงที่วันขาด

---

# คาบเรียนที่ 2 (ขั้นตอนที่ 1–12)

## ขั้นตอนที่ 12: กำหนดหน้าต่างสามรายการ

กำหนดการพิจารณาสามรายการย้อนหลังรวมรายการปัจจุบัน

```python
revenue_window = daily['revenue'].rolling(window=3, min_periods=3)
```

- `revenue_window =`: เก็บหน้าต่างข้อมูลเพื่อคำนวณ
- `daily['revenue']`: เลือกยอดเงินที่เรียงวันแล้ว
- `window=3`: ใช้สามรายการล่าสุดในแต่ละตำแหน่ง
- `min_periods=3`: ต้องมีค่าจริงครบสามรายการจึงให้ผล

พิมพ์คำสั่งและกดปุ่ม Shift + Enter เพื่อรันคำสั่งและตรวจสอบผลลัพธ์

In [12]:
revenue_window = daily['revenue'].rolling(window=3, min_periods=3)

### ผลลัพธ์และคำอธิบาย

```text
รันคำสั่งสำเร็จ (ไม่มีข้อความแจ้งข้อผิดพลาด)
```

ยังไม่คำนวณค่าเฉลี่ยและยังไม่แสดงตาราง

**ข้อควรระวังในการเขียนคำสั่ง:** สามรายการไม่ใช่สามวันต่อเนื่องเมื่อมีวันขาด

**คำถามตรวจสอบความเข้าใจ:** รันได้และอธิบายหน้าที่ window กับ min_periods

## ขั้นตอนที่ 13: หาค่าเฉลี่ยในแต่ละหน้าต่าง

หาค่าเฉลี่ยเลขคณิตของยอดเงินในหน้าต่างที่กำหนด

```python
moving_average = revenue_window.mean()
```

- `moving_average =`: เก็บชุดค่าเฉลี่ยเคลื่อนที่
- `revenue_window`: หน้าต่างสามรายการที่กำหนดแล้ว
- `.mean()`: หาค่าเฉลี่ยยอดเงินในแต่ละหน้าต่าง

พิมพ์คำสั่งและกดปุ่ม Shift + Enter เพื่อรันคำสั่งและตรวจสอบผลลัพธ์

In [13]:
moving_average = revenue_window.mean()

### ผลลัพธ์และคำอธิบาย

```text
รันคำสั่งสำเร็จ (ไม่มีข้อความแจ้งข้อผิดพลาด)
```

สองรายการแรกยังไม่มีค่าเฉลี่ยเพราะข้อมูลไม่ครบสามรายการ

**ข้อควรระวังในการเขียนคำสั่ง:** ห้ามใช้ sum หากโจทย์ต้องการค่าเฉลี่ย

**คำถามตรวจสอบความเข้าใจ:** รันได้และอธิบายเหตุผลของค่าว่างสองรายการแรก

## ขั้นตอนที่ 14: เพิ่มค่าเฉลี่ยลงในตาราง

นำผลค่าเฉลี่ยมาเป็นคอลัมน์ประกอบยอดรายวัน

```python
daily['MA_3observations'] = moving_average
```

- `daily['MA_3observations'] =`: สร้างคอลัมน์ค่าเฉลี่ยสามรายการ
- `moving_average`: ชุดค่าที่จับคู่ด้วยดัชนีวันที่

พิมพ์คำสั่งและกดปุ่ม Shift + Enter เพื่อรันคำสั่งและตรวจสอบผลลัพธ์

In [14]:
daily['MA_3observations'] = moving_average

### ผลลัพธ์และคำอธิบาย

```text
รันคำสั่งสำเร็จ (ไม่มีข้อความแจ้งข้อผิดพลาด)
```

เก็บคอลัมน์ใหม่โดยยังไม่แสดงตาราง

**ข้อควรระวังในการเขียนคำสั่ง:** ชื่อคอลัมน์หมายถึงสาม observations หรือสามรายการข้อมูล ไม่ใช่สามวันปฏิทิน

**คำถามตรวจสอบความเข้าใจ:** รันได้แล้วแสดง daily ในขั้นถัดไป

## ขั้นตอนที่ 15: อ่านยอดจริงเทียบกับค่าเฉลี่ย

แสดงรายได้กับค่าเฉลี่ยเคลื่อนที่เพื่อฝึกตีความ

```python
daily
```

- `daily`: ตารางรายได้และค่าเฉลี่ยที่คำนวณแล้ว

พิมพ์คำสั่งและกดปุ่ม Shift + Enter เพื่อรันคำสั่งและตรวจสอบผลลัพธ์

In [15]:
daily

            revenue  MA_3observations
date
2026-11-01      290               NaN
2026-11-02      380               NaN
2026-11-03      530        400.000000
2026-11-04      415        441.666667
2026-11-05      625        523.333333
2026-11-08      505        515.000000
2026-11-09      325        485.000000
2026-11-10      805        545.000000
2026-11-11      355        495.000000
2026-11-12      655        605.000000

### ผลลัพธ์และคำอธิบาย

| ลำดับแถว | revenue | MA_3observations |
| --- | --- | --- |
| 2026-11-01 00:00:00 | 290.0 | ว่าง |
| 2026-11-02 00:00:00 | 380.0 | ว่าง |
| 2026-11-03 00:00:00 | 530.0 | 400.0 |
| 2026-11-04 00:00:00 | 415.0 | 441.6666666666667 |
| 2026-11-05 00:00:00 | 625.0 | 523.3333333333334 |
| 2026-11-08 00:00:00 | 505.0 | 515.0 |
| 2026-11-09 00:00:00 | 325.0 | 485.0 |
| 2026-11-10 00:00:00 | 805.0 | 545.0 |
| 2026-11-11 00:00:00 | 355.0 | 495.0 |
| 2026-11-12 00:00:00 | 655.0 | 605.0 |

วันที่ 3 พ.ย. ค่าเฉลี่ยคือ 400 บาท; วันที่ 8 พ.ย. ใช้ 4, 5 และ 8 พ.ย.; ค่าเฉลี่ยรายการสุดท้าย 605 บาท

**ข้อควรระวังในการเขียนคำสั่ง:** ค่าเฉลี่ยเป็นค่าที่คำนวณจากอดีต ไม่ใช่ยอดเงินจริงของวันนั้น

**คำถามตรวจสอบความเข้าใจ:** พบ NaN สองแถวแรก และอธิบายวันขาดด้วยตัวอย่าง 8 พ.ย.

## ขั้นตอนที่ 16: เลือกสามรายการล่าสุด

เลือกยอดเงินจริงสามรายการท้ายเพื่อสร้างค่าฐาน

```python
last_three = daily['revenue'].tail(3)
```

- `last_three =`: เก็บยอดสามรายการล่าสุด
- `daily['revenue']`: เลือกยอดเงินจริง ไม่ใช่ค่าเฉลี่ยเคลื่อนที่
- `.tail(3)`: เลือกสามรายการท้ายตามลำดับที่เรียงแล้ว

พิมพ์คำสั่งและกดปุ่ม Shift + Enter เพื่อรันคำสั่งและตรวจสอบผลลัพธ์

In [16]:
last_three = daily['revenue'].tail(3)

### ผลลัพธ์และคำอธิบาย

```text
รันคำสั่งสำเร็จ (ไม่มีข้อความแจ้งข้อผิดพลาด)
```

เก็บข้อมูลวันที่ 10, 11 และ 12 พ.ย. โดยยังไม่แสดงค่า

**ข้อควรระวังในการเขียนคำสั่ง:** ต้องเรียงวันก่อนเลือกท้าย; อย่าใช้คอลัมน์ MA แทนรายได้จริง

**คำถามตรวจสอบความเข้าใจ:** รันได้และอธิบายเลข 3 ใน tail

## ขั้นตอนที่ 17: ตรวจสามรายการที่ใช้ทำค่าฐาน

แสดงข้อมูลที่เป็นหลักฐานของค่าฐาน

```python
last_three
```

- `last_three`: ยอดเงินจริงสามรายการล่าสุด

พิมพ์คำสั่งและกดปุ่ม Shift + Enter เพื่อรันคำสั่งและตรวจสอบผลลัพธ์

In [17]:
last_three

date
2026-11-10    805
2026-11-11    355
2026-11-12    655
Name: revenue, dtype: int64

### ผลลัพธ์และคำอธิบาย

```text
date
2026-11-10    805
2026-11-11    355
2026-11-12    655
```

วันที่ 10 พ.ย. 805 บาท 11 พ.ย. 355 บาท และ 12 พ.ย. 655 บาท

**ข้อควรระวังในการเขียนคำสั่ง:** ถ้าได้วันไม่ตรง ให้กลับไปตรวจการเรียงดัชนี

**คำถามตรวจสอบความเข้าใจ:** อ่านสามวันและสามยอดได้ครบ

## ขั้นตอนที่ 18: คำนวณค่าฐานจากสามรายการล่าสุด

หาค่าเฉลี่ยเพื่อใช้เป็น baseline ของรายการวันที่มีข้อมูลถัดไป

```python
forecast = last_three.mean()
```

- `forecast =`: เก็บค่าฐานที่คำนวณจากอดีต
- `last_three`: รายได้สามรายการล่าสุด
- `.mean()`: บวกสามค่าแล้วหารด้วยสาม

พิมพ์คำสั่งและกดปุ่ม Shift + Enter เพื่อรันคำสั่งและตรวจสอบผลลัพธ์

In [18]:
forecast = last_three.mean()

### ผลลัพธ์และคำอธิบาย

```text
รันคำสั่งสำเร็จ (ไม่มีข้อความแจ้งข้อผิดพลาด)
```

เก็บค่าฐานเป็นบาท โดยยังไม่แสดงผล; ชื่อตัวแปร forecast ไม่ได้ยืนยันความแม่นยำ

**ข้อควรระวังในการเขียนคำสั่ง:** อย่าเรียกค่านี้ว่ารายได้ที่จะเกิดแน่นอน

**คำถามตรวจสอบความเข้าใจ:** รันได้และบอกได้ว่าใช้ยอดจริงสามรายการเป็นฐาน

## ขั้นตอนที่ 19: แสดงค่าฐานและระบุข้อจำกัด

แสดงผลค่าเฉลี่ยที่ใช้เป็นค่าฐาน

```python
forecast
```

- `forecast`: ค่าฐานจากสามรายการล่าสุด

พิมพ์คำสั่งและกดปุ่ม Shift + Enter เพื่อรันคำสั่งและตรวจสอบผลลัพธ์

In [19]:
forecast

605.0

### ผลลัพธ์และคำอธิบาย

```text
605.0
```

ได้ 605.0 บาท; เป็นค่าฐานจากข้อมูลสั้น ยังไม่ทดสอบความแม่นยำและไม่รับรองรายได้ในอนาคต

**ข้อควรระวังในการเขียนคำสั่ง:** อย่าอ้างว่าได้ 605 บาทแน่นอนหรือถือว่าเป็นสามวันต่อเนื่องทุกกรณี

**คำถามตรวจสอบความเข้าใจ:** ผลเป็น 605.0 บาท พร้อมเขียนข้อจำกัดสองประการในเซลล์ข้อความ

## สรุป

อธิบายคำสั่ง ผลลัพธ์ หน่วย และข้อจำกัด บันทึก Notebook สำหรับทบทวน